/**
 * Curated question pools for English (spelling, synonyms, antonyms, idioms)
 * and General/Banking Awareness. Small, human-quality seed content that the
 * generator samples from. Extend these arrays to grow coverage.
 */
const SPELLING = [
  { word: 'ACCOMMODATION', wrong: ['ACCOMODATION', 'ACCOMMODATON', 'ACOMODATION'] },
  { word: 'NECESSARY', wrong: ['NECESARY', 'NEccessARY', 'NECESSARYY'] },
  { word: 'RECEIVE', wrong: ['RECIEVE', 'RECEIVE', 'REICEVE'] },
  { word: 'SEPARATE', wrong: ['SEPERATE', 'SEPARETE', 'SEPARATTE'] },
  { word: 'OCCURRENCE', wrong: ['OCCURENCE', 'OCCURRENCE', 'OCURRENCE'] },
  { word: 'COMMITTEE', wrong: ['COMITTEE', 'COMMITEE', 'COMMITTE'] },
  { word: 'EMBARRASS', wrong: ['EMBARASS', 'EMBARRAS', 'EMMBARRASS'] },
  { word: 'MILLENNIUM', wrong: ['MILENNIUM', 'MILLENIUM', 'MILLENNIUN'] },
  { word: 'VACUUM', wrong: ['VACUM', 'VACUMM', 'VACUUME'] },
  { word: 'POSSESSION', wrong: ['POSSESION', 'POSESSION', 'POSSESSION'] },
  { word: 'DEFINITELY', wrong: ['DEFINATELY', 'DEFINETELY', 'DEFINITLY'] },
  { word: 'OCCASION', wrong: ['OCCASION', 'OCASION', 'OCCATION'] },
  { word: 'GUARANTEE', wrong: ['GAURANTEE', 'GUARANTE', 'GARANTEE'] },
  { word: 'LIAISON', wrong: ['LIAISION', 'LIASION', 'LIASON'] },
  { word: 'WEIRD', wrong: ['WIERD', 'WEIRD', 'WERID'] },
  { word: 'CONSCIENCE', wrong: ['CONSCENCE', 'CONSCIENSE', 'CONSIENCE'] },
  { word: 'MAINTENANCE', wrong: ['MAINTANENCE', 'MAINTENENCE', 'MAINTAINANCE'] },
  { word: 'MISCHIEVOUS', wrong: ['MISCHIEVIOUS', 'MISCHIEVOS', 'MISCHEVOUS'] },
  { word: 'NOTICEABLE', wrong: ['NOTICABLE', 'NOTICEIBLE', 'NOTICEABLEE'] },
  { word: 'PRIVILEGE', wrong: ['PRIVELEDGE', 'PRIVILEDGE', 'PRIVILIGE'] },
  { word: 'QUESTIONNAIRE', wrong: ['QUESTIONAIRE', 'QUESTIONNARE', 'QUESTIONNAIRE'] },
  { word: 'RHYTHM', wrong: ['RHYTHM', 'RHYTHEM', 'RYTHM'] },
  { word: 'SUCCEED', wrong: ['SUCCEDE', 'SUCEED', 'SUCCEEDD'] },
  { word: 'TENDENCY', wrong: ['TENDENCY', 'TENDANcy', 'TENDENSY'] },
  { word: 'UNNECESSARY', wrong: ['UNNECESARY', 'UNNECESSARY', 'UNECESSARY'] },
  { word: 'VEGETABLE', wrong: ['VEGETABLE', 'VEGTABLE', 'VEGETEBLE'] },
  { word: 'BUREAUCRACY', wrong: ['BUREAUCracy', 'BUREUCRACY', 'BUROCRACY'] },
  { word: 'CEMETERY', wrong: ['CEMETARY', 'CEMETRY', 'SEMETERY'] },
  { word: 'DEVELOPMENT', wrong: ['DEVELOPEMENT', 'DEVELPMENT', 'DEVELOPMENT'] },
  { word: 'EXISTENCE', wrong: ['EXISTANCE', 'EXISTENCE', 'EXSISTENCE'] }
];

const SYNONYMS = [
  { word: 'ABANDON', ans: 'FORSAKE', wrong: ['KEEP', 'RETAIN', 'HOLD'] },
  { word: 'ABUNDANT', ans: 'PLENTIFUL', wrong: ['SCARCE', 'MEAGRE', 'RARE'] },
  { word: 'CANDID', ans: 'FRANK', wrong: ['SECRETIVE', 'DECEITFUL', 'SHY'] },
  { word: 'DILIGENT', ans: 'INDUSTRIOUS', wrong: ['LAZY', 'IDLE', 'INDIFFERENT'] },
  { word: 'ELATED', ans: 'THRILLED', wrong: ['DEJECTED', 'GLOOMY', 'DOWNCAST'] },
  { word: 'FRAGILE', ans: 'BRITTLE', wrong: ['STURDY', 'TOUGH', 'STRONG'] },
  { word: 'GENUINE', ans: 'AUTHENTIC', wrong: ['FAKE', 'SPURIOUS', 'FORGED'] },
  { word: 'HAZARD', ans: 'PERIL', wrong: ['SAFETY', 'SECURITY', 'SHELTER'] },
  { word: 'IMPLICIT', ans: 'TACIT', wrong: ['EXPLICIT', 'CLEAR', 'OBVIOUS'] },
  { word: 'JUBILANT', ans: 'EXULTANT', wrong: ['MOURNFUL', 'SAD', 'GLOOMY'] },
  { word: 'KINDLE', ans: 'IGNITE', wrong: ['EXTINGUISH', 'DAMPEN', 'QUENCH'] },
  { word: 'LAMENT', ans: 'MOURN', wrong: ['REJOICE', 'CELEBRATE', 'REVEL'] },
  { word: 'MALIGN', ans: 'SLANDER', wrong: ['PRAISE', 'COMMEND', 'APPLAUD'] },
  { word: 'NOTION', ans: 'IDEA', wrong: ['FACT', 'CERTAINTY', 'REALITY'] },
  { word: 'OPULENT', ans: 'AFFLUENT', wrong: ['POOR', 'DESTITUTE', 'IMPOVERISHED'] },
  { word: 'PLACID', ans: 'SERENE', wrong: ['TURBULENT', 'AGITATED', 'STORMY'] },
  { word: 'QUANDARY', ans: 'DILEMMA', wrong: ['SOLUTION', 'ANSWER', 'RESOLUTION'] },
  { word: 'RESILIENT', ans: 'ADAPTABLE', wrong: ['VULNERABLE', 'FRAGILE', 'WEAK'] },
  { word: 'SAGACIOUS', ans: 'WISE', wrong: ['FOOLISH', 'RASH', 'IGNORANT'] },
  { word: 'TURBULENT', ans: 'CHAOTIC', wrong: ['CALM', 'SERENE', 'PEACEFUL'] },
  { word: 'UMBRAGE', ans: 'RESENTMENT', wrong: ['PLEASURE', 'DELIGHT', 'CONTENT'] },
  { word: 'VERBOSE', ans: 'WORDY', wrong: ['CONCISE', 'BRIEF', 'SUCCINCT'] },
  { word: 'WARY', ans: 'CAUTIOUS', wrong: ['CARELESS', 'RECKLESS', 'NAIVE'] },
  { word: 'YIELD', ans: 'SURRENDER', wrong: ['RESIST', 'DEFY', 'CONTEST'] },
  { word: 'ZEALOUS', ans: 'ARDENT', wrong: ['APATHETIC', 'INDIFFERENT', 'LUKEWARM'] },
  { word: 'ADVERSITY', ans: 'MISFORTUNE', wrong: ['PROSPERITY', 'FORTUNE', 'BLESSING'] },
  { word: 'BRIEF', ans: 'CONCISE', wrong: ['LENGTHY', 'VERBOSE', 'PROLONGED'] },
  { word: 'CONCEAL', ans: 'HIDE', wrong: ['REVEAL', 'DISCLOSE', 'EXPOSE'] },
  { word: 'DEMEANOR', ans: 'BEHAVIOUR', wrong: ['MANNERISM', 'APPEARANCE', 'HEIGHT'] },
  { word: 'ELEVATE', ans: 'RAISE', wrong: ['LOWER', 'REDUCE', 'DEMOTE'] }
];

const ANTONYMS = [
  { word: 'ABUNDANT', ans: 'SCARCE', wrong: ['PLENTIFUL', 'AMPLE', 'RICH'] },
  { word: 'BLUNT', ans: 'SHARP', wrong: ['DULL', 'OBTUSE', 'EDGELESS'] },
  { word: 'CANDID', ans: 'DECEITFUL', wrong: ['FRANK', 'HONEST', 'OPEN'] },
  { word: 'DISMAL', ans: 'CHEERFUL', wrong: ['GLOOMY', 'DREARY', 'BLEAK'] },
  { word: 'ENMITY', ans: 'FRIENDSHIP', wrong: ['HOSTILITY', 'ANIMOSITY', 'HATRED'] },
  { word: 'FRAIL', ans: 'STURDY', wrong: ['WEAK', 'DELICATE', 'BRITTLE'] },
  { word: 'GENEROUS', ans: 'STINGY', wrong: ['CHARITABLE', 'BOUNTIFUL', 'LIBERAL'] },
  { word: 'HAUGHTY', ans: 'HUMBLE', wrong: ['ARROGANT', 'PROUD', 'CONCEITED'] },
  { word: 'IMPETUOUS', ans: 'CAUTIOUS', wrong: ['RECKLESS', 'RASH', 'HURRIED'] },
  { word: 'JUVENILE', ans: 'MATURE', wrong: ['YOUNG', 'IMMATURE', 'CHILDISH'] },
  { word: 'KNOTTY', ans: 'SIMPLE', wrong: ['COMPLEX', 'TRICKY', 'INTRICATE'] },
  { word: 'LUCID', ans: 'OBSCURE', wrong: ['CLEAR', 'TRANSPARENT', 'LIMPID'] },
  { word: 'MEAGRE', ans: 'AMPLE', wrong: ['SCANTY', 'SPARSE', 'SCARCE'] },
  { word: 'NAIVE', ans: 'WORLDLY', wrong: ['INNOCENT', 'GULLIBLE', 'SIMPLE'] },
  { word: 'OBSTINATE', ans: 'FLEXIBLE', wrong: ['STUBBORN', 'HEADSTRONG', 'RIGID'] },
  { word: 'PRUDENT', ans: 'RECKLESS', wrong: ['WISE', 'CAUTIOUS', 'SENSIBLE'] },
  { word: 'QUIESCENT', ans: 'RESTLESS', wrong: ['INACTIVE', 'DORMANT', 'CALM'] },
  { word: 'RELUCTANT', ans: 'EAGER', wrong: ['UNWILLING', 'HESITANT', 'LOATH'] },
  { word: 'SULLEN', ans: 'CHEERFUL', wrong: ['MOROSE', 'GLOOMY', 'SURLEY'] },
  { word: 'TRANQUIL', ans: 'AGITATED', wrong: ['PEACEFUL', 'SERENE', 'CALM'] },
  { word: 'USURIOUS', ans: 'LIBERAL', wrong: ['EXTORTIONATE', 'GREEDY', 'RAPACIOUS'] },
  { word: 'VIGILANT', ans: 'CARELESS', wrong: ['ALERT', 'WATCHFUL', 'ATTENTIVE'] },
  { word: 'WAN', ans: 'FLORID', wrong: ['PALE', 'SALLOW', 'ASHEN'] },
  { word: 'YIELDING', ans: 'STUBBORN', wrong: ['FLEXIBLE', 'SUBMISSIVE', 'COMPLIANT'] },
  { word: 'ZEALOTRY', ans: 'TOLERANCE', wrong: ['FANATICISM', 'EXTREMISM', 'PARTISANSHIP'] },
  { word: 'APATHY', ans: 'ENTHUSIASM', wrong: ['INDIFFERENCE', 'LETHARGY', 'UNCONCERN'] },
  { word: 'BENIGN', ans: 'MALIGNANT', wrong: ['HARMLESS', 'KIND', 'GENTLE'] },
  { word: 'CURTAIL', ans: 'EXTEND', wrong: ['REDUCE', 'TRIM', 'DIMINISH'] },
  { word: 'DIVULGE', ans: 'CONCEAL', wrong: ['REVEAL', 'DISCLOSE', 'EXPOSE'] },
  { word: 'EXPEDITE', ans: 'DELAY', wrong: ['HASTEN', 'ACCELERATE', 'SPEED'] }
];

const IDIOMS = [
  { idiom: 'A blessing in disguise', ans: 'Something good that is not recognized at first', wrong: ['A hidden curse', 'A lucky coincidence', 'A planned trick'] },
  { idiom: 'Beat around the bush', ans: 'Avoid the main topic', wrong: ['Move quickly', 'Hunt carefully', 'Speak loudly'] },
  { idiom: 'Bite the bullet', ans: 'Face a difficult situation bravely', wrong: ['Chew hard food', 'Make a sudden decision', 'Quit a task'] },
  { idiom: 'Break the ice', ans: 'Start a conversation to ease tension', wrong: ['Destroy a barrier', 'Get cold quickly', 'Change the subject'] },
  { idiom: 'Burn the midnight oil', ans: 'Work late into the night', wrong: ['Waste resources', 'Set something on fire', 'Sleep early'] },
  { idiom: 'Call it a day', ans: 'Stop working for the day', wrong: ['Name the date', 'Postpone a meeting', 'Start early'] },
  { idiom: 'Cost an arm and a leg', ans: 'Be very expensive', wrong: ['Lose a limb', 'Spend carefully', 'Bargain hard'] },
  { idiom: 'Cut corners', ans: 'Do something cheaply or poorly', wrong: ['Take a shortcut', 'Trim edges', 'Avoid work'] },
  { idiom: 'Hit the nail on the head', ans: 'Do or say exactly the right thing', wrong: ['Use a hammer carelessly', 'Make a loud noise', 'Miss the point'] },
  { idiom: 'Once in a blue moon', ans: 'Very rarely', wrong: ['Every night', 'During the day', 'Never again'] },
  { idiom: 'Piece of cake', ans: 'Something very easy', wrong: ['A small meal', 'A sweet dessert', 'A minor problem'] },
  { idiom: 'Spill the beans', ans: 'Reveal a secret', wrong: ['Cook a meal', 'Make a mess', 'Lose control'] },
  { idiom: 'Take with a grain of salt', ans: 'Be skeptical of something', wrong: ['Add seasoning', 'Be generous', 'Ignore completely'] },
  { idiom: 'The ball is in your court', ans: 'It is your turn to act', wrong: ['You have the ball', 'The game is over', 'You must score'] },
  { idiom: 'Under the weather', ans: 'Feeling ill', wrong: ['Standing in rain', 'Feeling lucky', 'Being cautious'] },
  { idiom: 'When pigs fly', ans: 'Something that will never happen', wrong: ['An unusual event', 'A flying animal', 'Soon'] },
  { idiom: 'A penny for your thoughts', ans: 'Asking someone what they are thinking', wrong: ['A cheap deal', 'A small payment', 'A quick opinion'] },
  { idiom: 'Actions speak louder than words', ans: 'What you do matters more than what you say', wrong: ['Words are useless', 'Shouting is effective', 'Action hurts'] },
  { idiom: 'Back to the drawing board', ans: 'Start over because something failed', wrong: ['Return to school', 'Redraw a picture', 'Go home'] },
  { idiom: 'Caught between two stools', ans: 'Unable to choose between two options', wrong: ['Sitting between chairs', 'In a narrow space', 'Moving quickly'] },
  { idiom: 'Devil\'s advocate', ans: 'Argue the opposite side to test a decision', wrong: ['A mischievous person', 'A religious leader', 'A fair judge'] },
  { idiom: 'Elephant in the room', ans: 'An obvious issue everyone ignores', wrong: ['A large object', 'A difficult animal', 'A hidden danger'] },
  { idiom: 'Go the extra mile', ans: 'Make more effort than required', wrong: ['Walk further', 'Run a race', 'Leave early'] },
  { idiom: 'Hold your horses', ans: 'Wait; be patient', wrong: ['Control animals', 'Run faster', 'Keep silent'] },
  { idiom: 'In the same boat', ans: 'In the same difficult situation', wrong: ['On a shared journey', 'Similar appearance', 'Competing equally'] },
  { idiom: 'Let the cat out of the bag', ans: 'Reveal a secret', wrong: ['Free a pet', 'Open a container', 'Admit defeat'] },
  { idiom: 'Miss the boat', ans: 'Miss an opportunity', wrong: ['Lose a ship', 'Arrive late', 'Forget the way'] },
  { idiom: 'Put your thinking cap on', ans: 'Think carefully', wrong: ['Wear a hat', 'Avoid work', 'Speak fast'] },
  { idiom: 'Raining cats and dogs', ans: 'Raining very heavily', wrong: ['Weather forecast', 'Pets outside', 'Light drizzle'] },
  { idiom: 'Steal someone\'s thunder', ans: 'Take credit for another\'s work', wrong: ['Steal goods', 'Cause a storm', 'Borrow ideas'] }
];

const GA = [
  { q: 'Who is known as the Father of the Indian Constitution?', ans: 'Dr. B. R. Ambedkar', wrong: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Sardar Patel'] },
  { q: 'What is the currency of Japan?', ans: 'Yen', wrong: ['Won', 'Dollar', 'Yuan'] },
  { q: 'Which bank is known as the central bank of India?', ans: 'Reserve Bank of India', wrong: ['State Bank of India', 'Punjab National Bank', 'Bank of Baroda'] },
  { q: 'The headquarters of the Reserve Bank of India is located in', ans: 'Mumbai', wrong: ['New Delhi', 'Kolkata', 'Chennai'] },
  { q: 'Which of these is a scheduled commercial bank in India?', ans: 'State Bank of India', wrong: ['NABARD', 'SIDBI', 'IFCI'] },
  { q: 'What does CRR stand for?', ans: 'Cash Reserve Ratio', wrong: ['Capital Reserve Ratio', 'Cash Reserve Rate', 'Central Reserve Rate'] },
  { q: 'Who appoints the Governor of the Reserve Bank of India?', ans: 'Government of India', wrong: ['Finance Minister', 'Parliament', 'President only'] },
  { q: 'NABARD was established in which year?', ans: '1982', wrong: ['1975', '1969', '1990'] },
  { q: 'Which is the oldest public sector bank in India?', ans: 'Allahabad Bank', wrong: ['State Bank of India', 'Bank of India', 'Canara Bank'] },
  { q: 'The concept of microfinance in India is closely associated with', ans: 'Grameen Bank', wrong: ['RBI', 'World Bank', 'IMF'] },
  { q: 'What is the full form of KYC?', ans: 'Know Your Customer', wrong: ['Know Your Company', 'Keep Your Cash', 'Know Your Client'] },
  { q: 'Which year was the RBI established?', ans: '1935', wrong: ['1947', '1920', '1950'] },
  { q: 'The Interest Rate at which RBI lends short-term funds to commercial banks is called', ans: 'Repo Rate', wrong: ['Reverse Repo Rate', 'SLR', 'Base Rate'] },
  { q: 'Which committee recommended the establishment of RRBs?', ans: 'Narasimham Committee', wrong: ['Kelkar Committee', 'Rangarajan Committee', 'Tandon Committee'] },
  { q: 'What is the full form of SLR?', ans: 'Statutory Liquidity Ratio', wrong: ['Statutory Lending Rate', 'Short-term Lending Ratio', 'State Liquidity Rate'] },
  { q: 'Which of the following is a development financial institution in India?', ans: 'NABARD', wrong: ['SBI', 'HDFC Bank', 'Axis Bank'] },
  { q: 'The minimum capital requirement for a scheduled commercial bank is decided by', ans: 'RBI', wrong: ['SEBI', 'Government', 'Finance Ministry'] },
  { q: 'Which bank launched the Aadhaar-enabled payment system?', ans: 'NABARD', wrong: ['SBI', 'RBI', 'PNB'] },
  { q: 'What is the statutory body that regulates insurance in India?', ans: 'IRDAI', wrong: ['SEBI', 'RBI', 'PFRDA'] },
  { q: 'The GST was implemented in India from', ans: '1 July 2017', wrong: ['1 April 2016', '1 January 2018', '1 August 2019'] },
  { q: 'Which is the largest bank in India by total assets?', ans: 'State Bank of India', wrong: ['HDFC Bank', 'ICICI Bank', 'Punjab National Bank'] },
  { q: 'What does UPI stand for?', ans: 'Unified Payments Interface', wrong: ['Universal Payment Index', 'United Payment Interface', 'Unified Payment Industry'] },
  { q: 'The National Payments Corporation of India is headquartered at', ans: 'Mumbai', wrong: ['New Delhi', 'Bengaluru', 'Hyderabad'] },
  { q: 'Which country hosts the headquarters of the World Bank?', ans: 'USA', wrong: ['UK', 'France', 'Switzerland'] },
  { q: 'Which of these is NOT a component of the Money Market in India?', ans: 'Stock Market', wrong: ['Treasury Bills', 'Call Money', 'Commercial Paper'] },
  { q: 'The first bank to be nationalized in India was', ans: 'Imperial Bank of India', wrong: ['Bank of India', 'Punjab National Bank', 'Canara Bank'] },
  { q: 'Basel III norms primarily aim to', ans: 'Strengthen bank capital requirements', wrong: ['Increase interest rates', 'Reduce bank profits', 'Abolish banking licences'] },
  { q: 'Which institution issues coins in India?', ans: 'Government of India', wrong: ['RBI', 'SBI', 'SEBI'] },
  { q: 'What is the full form of IFSC?', ans: 'Indian Financial System Code', wrong: ['Indian Financial Services Code', 'International Financial System Code', 'Indian Bank Fund Code'] },
  { q: 'The headquarters of the Securities and Exchange Board of India is at', ans: 'Mumbai', wrong: ['Kolkata', 'Chennai', 'New Delhi'] },
  { q: 'Which scheme provides insurance cover on bank deposits in India?', ans: 'DICGC', wrong: ['PMJJBY', 'PMSBY', 'SIDBI'] },
  { q: 'The Reserve Bank of India was nationalized in', ans: '1949', wrong: ['1947', '1955', '1969'] },
  { q: 'What is the full form of RTGS?', ans: 'Real Time Gross Settlement', wrong: ['Real Time Global Settlement', 'Rapid Transfer Gross System', 'Real Time General Settlement'] },
  { q: 'The term "Cheque Truncation" is related to', ans: 'Speedy clearing of cheques', wrong: ['Printing of cheques', 'Dishonouring of cheques', 'Issuing new cheques'] },
  { q: 'Which bank was merged with PNB in 2020?', ans: 'Oriental Bank of Commerce', wrong: ['Canara Bank', 'Syndicate Bank', 'Indian Overseas Bank'] },
  { q: 'The headquarters of the Asian Development Bank is at', ans: 'Manila', wrong: ['Tokyo', 'Singapore', 'Beijing'] }
];

module.exports = { SPELLING, SYNONYMS, ANTONYMS, IDIOMS, GA };
