module.exports = {
  ONEWORD: [
    { clue: 'A person who speaks many languages', ans: 'POLYGLOT', wrong: ['MONOLINGUAL', 'LINGUIST', 'ORATOR'] },
    { clue: 'A person who cannot read or write', ans: 'ILLITERATE', wrong: ['ILLEGIBLE', 'LITERATE', 'NAIVE'] },
    { clue: 'One who is present everywhere', ans: 'OMNIPRESENT', wrong: ['OMNIPOTENT', 'OMNISCIENT', 'OMNIVOROUS'] },
    { clue: 'One who knows everything', ans: 'OMNISCIENT', wrong: ['OMNIPOTENT', 'OMNIPRESENT', 'IGNORANT'] },
    { clue: 'One who is all-powerful', ans: 'OMNIPOTENT', wrong: ['OMNISCIENT', 'OMNIPRESENT', 'IMPOTENT'] },
    { clue: 'An animal that eats both plants and flesh', ans: 'OMNIVORE', wrong: ['HERBIVORE', 'CARNIVORE', 'VEGETARIAN'] },
    { clue: 'An animal that eats the flesh of other animals', ans: 'CARNIVORE', wrong: ['HERBIVORE', 'OMNIVORE', 'GRAZER'] },
    { clue: 'A place where bees are kept', ans: 'APIARY', wrong: ['AVIARY', 'AQUARIUM', 'STABLE'] },
    { clue: 'A place where birds are kept', ans: 'AVIARY', wrong: ['APIARY', 'AQUARIUM', 'MUSEUM'] },
    { clue: 'A place where weapons and ammunition are stored', ans: 'ARSENAL', wrong: ['GRANARY', 'GARRISON', 'MUSEUM'] },
    { clue: 'A place where grains are stored', ans: 'GRANARY', wrong: ['ARSENAL', 'MUSEUM', 'KENNEL'] },
    { clue: 'A place where ancient objects are kept', ans: 'MUSEUM', wrong: ['LIBRARY', 'GRANARY', 'AVIARY'] },
    { clue: 'A person who studies the stars and planets', ans: 'ASTRONOMER', wrong: ['ASTROLOGER', 'GEOGRAPHER', 'ARCHAEOLOGIST'] },
    { clue: 'A person who studies ancient remains', ans: 'ARCHAEOLOGIST', wrong: ['ASTRONOMER', 'GEOLOGIST', 'ZOOLOGIST'] },
    { clue: 'One who treats diseases of the eyes', ans: 'OPHTHALMOLOGIST', wrong: ['DERMATOLOGIST', 'DENTIST', 'PODIATRIST'] },
    { clue: 'One who treats diseases of the skin', ans: 'DERMATOLOGIST', wrong: ['CARDIOLOGIST', 'PEDIATRICIAN', 'OPHTHALMOLOGIST'] },
    { clue: 'A doctor who treats children', ans: 'PEDIATRICIAN', wrong: ['GERIATRICIAN', 'GYNECOLOGIST', 'DERMATOLOGIST'] },
    { clue: 'One who cuts hair and shaves beards', ans: 'BARBER', wrong: ['BUTCHER', 'BAKER', 'TAILOR'] },
    { clue: 'A person who makes and sells bread and cakes', ans: 'BAKER', wrong: ['BUTCHER', 'BARBER', 'CARPENTER'] },
    { clue: 'A person who mends shoes', ans: 'COBBLER', wrong: ['TAILOR', 'BARBER', 'BLACKSMITH'] },
    { clue: 'A person who works with iron and steel', ans: 'BLACKSMITH', wrong: ['GOLDSMITH', 'CARPENTER', 'COBBLER'] },
    { clue: 'A person who makes ornaments of gold', ans: 'GOLDSMITH', wrong: ['BLACKSMITH', 'SILVERSMITH', 'COBBLER'] },
    { clue: 'A person who makes wooden furniture', ans: 'CARPENTER', wrong: ['PLUMBER', 'MASON', 'BLACKSMITH'] },
    { clue: 'A person who repairs water pipes and fittings', ans: 'PLUMBER', wrong: ['MASON', 'CARPENTER', 'ELECTRICIAN'] },
    { clue: 'A person who writes plays', ans: 'DRAMATIST', wrong: ['NOVELIST', 'POET', 'CRITIC'] },
    { clue: 'A person who writes for newspapers', ans: 'JOURNALIST', wrong: ['NOVELIST', 'EDITOR', 'AUTHOR'] },
    { clue: 'A person who makes maps', ans: 'CARTOGRAPHER', wrong: ['CHOREOGRAPHER', 'PHOTOGRAPHER', 'ARCHIVIST'] },
    { clue: 'A person who designs buildings', ans: 'ARCHITECT', wrong: ['ENGINEER', 'SURVEYOR', 'SCULPTOR'] },
    { clue: 'A person who writes dictionaries', ans: 'LEXICOGRAPHER', wrong: ['CARTOGRAPHER', 'CHOREOGRAPHER', 'BIOGRAPHER'] },
    { clue: 'One who writes the life story of another', ans: 'BIOGRAPHER', wrong: ['LEXICOGRAPHER', 'CARTOGRAPHER', 'CRITIC'] },
    { clue: 'One who looks at the bright side of things', ans: 'OPTIMIST', wrong: ['PESSIMIST', 'REALIST', 'FATALIST'] },
    { clue: 'One who looks at the dark side of things', ans: 'PESSIMIST', wrong: ['OPTIMIST', 'REALIST', 'IDEALIST'] },
    { clue: 'One who is greedy for money', ans: 'MISER', wrong: ['SPENDTHRIFT', 'PHILANTHROPIST', 'PRODIGAL'] },
    { clue: 'One who spends money lavishly', ans: 'SPENDTHRIFT', wrong: ['MISER', 'PHILANTHROPIST', 'THRIFTY'] },
    { clue: 'One who loves mankind and does good to others', ans: 'PHILANTHROPIST', wrong: ['MISANTHROPE', 'MISER', 'SPENDTHRIFT'] },
    { clue: 'One who hates mankind', ans: 'MISANTHROPE', wrong: ['PHILANTHROPIST', 'MISOGYNIST', 'PATRIOT'] },
    { clue: 'One who loves his country', ans: 'PATRIOT', wrong: ['TRAITOR', 'MISANTHROPE', 'COWARD'] },
    { clue: 'One who betrays his country', ans: 'TRAITOR', wrong: ['PATRIOT', 'GUARDIAN', 'HERO'] },
    { clue: 'A person who lives in solitude away from people', ans: 'RECLUSE', wrong: ['SOCIALITE', 'ORATOR', 'PATRIOT'] },
    { clue: 'A person who talks too much', ans: 'GARRULOUS', wrong: ['TACITURN', 'RETICENT', 'QUIET'] },
    { clue: 'One who speaks very little', ans: 'TACITURN', wrong: ['GARRULOUS', 'LOQUACIOUS', 'VOLUBLE'] },
    { clue: 'A person who is easily cheated or deceived', ans: 'GULLIBLE', wrong: ['SHREWD', 'CUNNING', 'SCEPTICAL'] },
    { clue: 'One who is always suspicious of others', ans: 'SCEPTICAL', wrong: ['TRUSTING', 'GULLIBLE', 'NAIVE'] },
    { clue: 'Government by the people', ans: 'DEMOCRACY', wrong: ['AUTOCRACY', 'OLIGARCHY', 'MONARCHY'] },
    { clue: 'Government by one person with absolute power', ans: 'AUTOCRACY', wrong: ['DEMOCRACY', 'OLIGARCHY', 'BUREAUCRACY'] },
    { clue: 'Government by a king or a queen', ans: 'MONARCHY', wrong: ['DEMOCRACY', 'OLIGARCHY', 'PLUTOCRACY'] },
    { clue: 'Government by the rich', ans: 'PLUTOCRACY', wrong: ['DEMOCRACY', 'AUTOCRACY', 'THEOCRACY'] },
    { clue: 'A place where money and coins are made', ans: 'MINT', wrong: ['BANK', 'BUREAU', 'MUSEUM'] },
    { clue: 'A book containing maps of the world', ans: 'ATLAS', wrong: ['DICTIONARY', 'ALMANAC', 'ENCYCLOPEDIA'] },
    { clue: 'A collection of poems', ans: 'ANTHOLOGY', wrong: ['DICTIONARY', 'ATLAS', 'ALMANAC'] },
    { clue: 'One who studies birds', ans: 'ORNITHOLOGIST', wrong: ['ENTOMOLOGIST', 'ZOOLOGIST', 'ARCHAEOLOGIST'] },
    { clue: 'One who studies insects', ans: 'ENTOMOLOGIST', wrong: ['ORNITHOLOGIST', 'BOTANIST', 'GEOLOGIST'] },
    { clue: 'One who studies plants', ans: 'BOTANIST', wrong: ['ZOOLOGIST', 'ENTOMOLOGIST', 'ANTHROPOLOGIST'] },
    { clue: 'One who studies human beings and their culture', ans: 'ANTHROPOLOGIST', wrong: ['ZOOLOGIST', 'BOTANIST', 'GEOLOGIST'] },
    { clue: 'One who is forced to leave his country', ans: 'EXILE', wrong: ['TOURIST', 'CITIZEN', 'RESIDENT'] },
    { clue: 'One who is unable to pay his debts', ans: 'INSOLVENT', wrong: ['SOLVENT', 'PROSPEROUS', 'FLOURISHING'] },
    { clue: 'One who works without payment', ans: 'VOLUNTEER', wrong: ['EMPLOYEE', 'WORKER', 'SLAVE'] },
    { clue: 'A diplomatic representative of a country abroad', ans: 'AMBASSADOR', wrong: ['SPY', 'MINISTER', 'GOVERNOR'] },
    { clue: 'One who treats diseases of the teeth', ans: 'DENTIST', wrong: ['OPTICIAN', 'DERMATOLOGIST', 'PODIATRIST'] },
    { clue: 'A person who writes novels', ans: 'NOVELIST', wrong: ['DRAMATIST', 'POET', 'EDITOR'] },
    { clue: 'A person who studies the origin and history of words', ans: 'ETYMOLOGIST', wrong: ['GEOLOGIST', 'CARTOGRAPHER', 'ANTHROPOLOGIST'] },
    { clue: 'A person who can use both hands equally well', ans: 'AMBIDEXTROUS', wrong: ['AMBIGUOUS', 'DEXTROUS', 'AMBIVALENT'] },
    { clue: 'A person who believes in God', ans: 'THEIST', wrong: ['ATHEIST', 'AGNOSTIC', 'PANTHEIST'] },
    { clue: 'One who does not believe in God', ans: 'ATHEIST', wrong: ['THEIST', 'MYSTIC', 'DEIST'] },
    { clue: 'A person who lives on others and does no work', ans: 'PARASITE', wrong: ['HOST', 'GUEST', 'DONOR'] },
    { clue: 'One who is easily deceived or cheated', ans: 'GULLIBLE', wrong: ['CREDIBLE', 'SHREWD', 'SKEPTICAL'] },
    { clue: 'One who eats excessively', ans: 'GLUTTON', wrong: ['GOURMET', 'VEGETARIAN', 'ANOREXIC'] },
    { clue: 'One who abstains completely from alcoholic drinks', ans: 'TEETOTALLER', wrong: ['ALCOHOLIC', 'REVELER', 'EPICURE'] },
    { clue: 'One who never makes mistakes', ans: 'INFALLIBLE', wrong: ['FALLIBLE', 'ERRANT', 'UNRELIABLE'] },
    { clue: 'That which cannot be corrected', ans: 'INCORRIGIBLE', wrong: ['CORRIGIBLE', 'CORRECTABLE', 'REFORMABLE'] },
    { clue: 'That which cannot be avoided', ans: 'INEVITABLE', wrong: ['AVOIDABLE', 'PREVENTABLE', 'EVITABLE'] },
    { clue: 'That which cannot be conquered', ans: 'INVINCIBLE', wrong: ['VULNERABLE', 'CONQUERABLE', 'DEFENSIBLE'] },
    { clue: 'That which cannot be satisfied', ans: 'INSATIABLE', wrong: ['SATIABLE', 'CONTENTED', 'GRATIFIED'] },
    { clue: 'That which cannot be seen', ans: 'INVISIBLE', wrong: ['VISIBLE', 'APPARENT', 'PERCEPTIBLE'] },
    { clue: 'That which cannot be heard', ans: 'INAUDIBLE', wrong: ['AUDIBLE', 'DISTINCT', 'CLEAR'] },
    { clue: 'A speech made without preparation', ans: 'EXTEMPORE', wrong: ['PREPARED', 'REHEARSED', 'SCRIPTED'] },
    { clue: 'A word formed from the initial letters of other words', ans: 'ACRONYM', wrong: ['PSEUDONYM', 'SYNONYM', 'HOMONYM'] },
    { clue: 'A name assumed by an author to conceal his identity', ans: 'PSEUDONYM', wrong: ['ACRONYM', 'ANTONYM', 'EPITHET'] },
    { clue: 'A place where clothes are kept', ans: 'WARDROBE', wrong: ['ARSENAL', 'CELLAR', 'GRANARY'] },
    { clue: 'A place where coins are manufactured', ans: 'MINT', wrong: ['ARSENAL', 'FORGE', 'FACTORY'] },
    { clue: 'A place where ships are built or repaired', ans: 'DOCKYARD', wrong: ['AIRPORT', 'STABLE', 'KENNEL'] },
    { clue: 'A place where aircraft are kept', ans: 'HANGAR', wrong: ['DOCKYARD', 'GARAGE', 'DEPOT'] },
    { clue: 'A place where orphans are cared for', ans: 'ORPHANAGE', wrong: ['HERMITAGE', 'MONASTERY', 'CONVENT'] },
    { clue: 'A place where money and valuables are kept', ans: 'TREASURY', wrong: ['MUSEUM', 'ARCHIVE', 'LIBRARY'] },
    { clue: 'A person who travels from place to place without a fixed home', ans: 'NOMAD', wrong: ['SETTLER', 'RESIDENT', 'CITIZEN'] },
    { clue: 'One who dies for a noble cause', ans: 'MARTYR', wrong: ['HERETIC', 'TRAITOR', 'REBEL'] },
    { clue: 'One who is over-concerned with minor details', ans: 'PEDANT', wrong: ['LAYMAN', 'NOVICE', 'AMATEUR'] },
    { clue: 'A person who is exactly one hundred years old', ans: 'CENTENARIAN', wrong: ['DECENNIAL', 'JUVENILE', 'TEENAGER'] },
    { clue: 'A person who looks after horses', ans: 'GROOM', wrong: ['SHEPHERD', 'COWHERD', 'STEWARD'] },
    { clue: 'A place where books are kept for reading and reference', ans: 'LIBRARY', wrong: ['GRANARY', 'AVIARY', 'KENNEL'] },
    { clue: 'A person who makes a will before death', ans: 'TESTATOR', wrong: ['GUARDIAN', 'HEIR', 'BENEFICIARY'] },
    { clue: 'That which lasts for a very short time', ans: 'EPHEMERAL', wrong: ['ETERNAL', 'PERMANENT', 'ENDURING'] },
    { clue: 'Government by the richest people', ans: 'PLUTOCRACY', wrong: ['DEMOCRACY', 'BUREAUCRACY', 'THEOCRACY'] },
    { clue: 'Government by the nobility', ans: 'ARISTOCRACY', wrong: ['DEMOCRACY', 'PLUTOCRACY', 'MOBOCRACY'] }
  ],
  IDIOMS: [
    { idiom: 'A chip on your shoulder', ans: 'To be angry about something that happened in the past', wrong: ['A heavy responsibility', 'A hidden talent', 'A lucky charm'] },
    { idiom: 'A dime a dozen', ans: 'Something very common and easy to get', wrong: ['Something very rare', 'Something very costly', 'Something quite useless'] },
    { idiom: 'A hard nut to crack', ans: 'A difficult problem to solve', wrong: ['A very easy task', 'A sweet-natured person', 'A fragile object'] },
    { idiom: 'A leopard cannot change its spots', ans: 'People cannot change their basic character', wrong: ['Nature renews itself every season', 'Old habits die out quickly', 'Spots are hard to wash off'] },
    { idiom: 'A rolling stone gathers no moss', ans: 'A person who moves often never settles down', wrong: ['A wandering person grows wealthy', 'Stones on hillsides stay clean', 'Constant movement builds strong character'] },
    { idiom: 'A stone throw', ans: 'A very short distance', wrong: ['A very long distance', 'A heavy burden', 'An easy throw'] },
    { idiom: 'Add insult to injury', ans: 'To make a bad situation worse', wrong: ['To apologize after hurting someone', 'To cause harm by mistake', 'To forgive and forget'] },
    { idiom: 'All ears', ans: 'Listening very attentively', wrong: ['Hard of hearing', 'Wearing headphones', 'Pretending to listen'] },
    { idiom: 'At the drop of a hat', ans: 'Immediately without hesitation', wrong: ['Very reluctantly', 'After much delay', 'At the end of the day'] },
    { idiom: 'Back to square one', ans: 'To start again from the beginning', wrong: ['To return to a safe place', 'To move to a bigger house', 'To win another round'] },
    { idiom: 'Barking up the wrong tree', ans: 'Pursuing a wrong course of action', wrong: ['Making a dog bark loudly', 'Planting trees in the wrong season', 'Climbing the wrong branch'] },
    { idiom: 'Best of both worlds', ans: 'Enjoying the advantages of two different situations', wrong: ['Having two homes', 'Sharing everything equally', 'Being undecided between two choices'] },
    { idiom: 'Bite off more than you can chew', ans: 'To take on more than you can handle', wrong: ['To eat very quickly', 'To refuse to share food', 'To take on too little work'] },
    { idiom: 'Burn the candle at both ends', ans: 'To work so hard that you exhaust yourself', wrong: ['To waste money on candles', 'To be extremely efficient', 'To study late only sometimes'] },
    { idiom: 'By the skin of your teeth', ans: 'To barely manage to do something', wrong: ['With great ease', 'By brushing your teeth', 'Through hard practice'] },
    { idiom: 'Caught red-handed', ans: 'Caught in the act of doing something wrong', wrong: ['Caught with red paint', 'Caught after confessing', 'Punished for no reason'] },
    { idiom: 'Cold feet', ans: 'Nervousness before an important event', wrong: ['Feeling physically cold', 'A desire to run away', 'Firm determination'] },
    { idiom: 'Cry over spilt milk', ans: 'To regret something that cannot be undone', wrong: ['To clean up a messy kitchen', 'To complain about low salary', 'To celebrate small wins'] },
    { idiom: 'Curiosity killed the cat', ans: 'Being too inquisitive can bring trouble', wrong: ['Cats are naturally curious', 'Curiosity is always rewarded', 'Cats survive nine lives'] },
    { idiom: 'Cut to the chase', ans: 'To get to the point without wasting time', wrong: ['To reduce the budget', 'To hurry home quickly', 'To avoid the main topic'] },
    { idiom: 'Dark horse', ans: 'An unexpected winner or an unknown candidate', wrong: ['A person who never loses', 'A frightened competitor', 'A horse kept in the dark'] },
    { idiom: 'Every cloud has a silver lining', ans: 'Good can come out of bad situations', wrong: ['Clouds bring heavy rain', 'Every difficulty repeats itself', 'Silver is the most precious metal'] },
    { idiom: 'Face the music', ans: 'To accept the unpleasant consequences of your actions', wrong: ['To sing a pleasant song', 'To run away from trouble', 'To enjoy a concert'] },
    { idiom: 'Fish out of water', ans: 'Someone who is uncomfortable in a new situation', wrong: ['A skilled swimmer', 'A person away from home', 'A hungry fisherman'] },
    { idiom: 'Fit as a fiddle', ans: 'In very good health', wrong: ['Very rich', 'Extremely old', 'Slightly unwell'] },
    { idiom: 'Get the ball rolling', ans: 'To begin an activity', wrong: ['To stop an argument', 'To end a game', 'To miss an opportunity'] },
    { idiom: 'Give the benefit of the doubt', ans: 'To believe someone even when you are not sure', wrong: ['To doubt a person honesty', 'To punish without proof', 'To ask for evidence first'] },
    { idiom: 'Great minds think alike', ans: 'Clever people reach similar conclusions', wrong: ['Big people are very similar', 'Wise men never disagree', 'Similar thoughts bring bad luck'] },
    { idiom: 'Haste makes waste', ans: 'Acting too quickly leads to mistakes', wrong: ['Hurrying saves time', 'Slow work is useless', 'Waste is unavoidable'] },
    { idiom: 'Hit the books', ans: 'To study hard', wrong: ['To hit the shelves', 'To throw books away', 'To read for pleasure'] },
    { idiom: 'In hot water', ans: 'In trouble', wrong: ['In a warm bath', 'In a happy mood', 'In a comfortable situation'] },
    { idiom: 'In the nick of time', ans: 'Just in time', wrong: ['Far too late', 'Long before time', 'At regular intervals'] },
    { idiom: 'A blessing in disguise', ans: 'Something that seems bad but turns out to be good', wrong: ['An outright curse', 'A hidden gift from a stranger', 'A punishment for wrongdoing'] },
    { idiom: 'A piece of cake', ans: 'Something very easy to do', wrong: ['A delicious reward', 'A very difficult task', 'An expensive treat'] },
    { idiom: 'Once in a blue moon', ans: 'Very rarely', wrong: ['Every day', 'At midnight', 'During summer'] },
    { idiom: 'Break the ice', ans: 'To start a conversation in a friendly way', wrong: ['To damage a window', 'To end a friendship', 'To speak loudly'] },
    { idiom: 'Beat around the bush', ans: 'To avoid talking about the main issue', wrong: ['To work in a garden', 'To speak very directly', 'To move quickly'] },
    { idiom: 'Burn the midnight oil', ans: 'To work late into the night', wrong: ['To waste fuel', 'To stay awake from fear', 'To finish work early'] },
    { idiom: 'Hit the nail on the head', ans: 'To describe something exactly right', wrong: ['To hurt oneself', 'To be completely wrong', 'To act carelessly'] },
    { idiom: 'Let the cat out of the bag', ans: 'To reveal a secret unintentionally', wrong: ['To free a trapped animal', 'To buy an expensive pet', 'To hide the truth deliberately'] },
    { idiom: 'Spill the beans', ans: 'To disclose a secret', wrong: ['To drop food', 'To keep information hidden', 'To prepare a meal'] },
    { idiom: 'Under the weather', ans: 'Feeling unwell', wrong: ['Feeling happy', 'Standing in the rain', 'Working outdoors'] },
    { idiom: 'Cut corners', ans: 'To do something carelessly to save time or money', wrong: ['To take the shortest route', 'To be very thorough', 'To cut costs legally'] },
    { idiom: 'Bite the bullet', ans: 'To face a difficult situation bravely', wrong: ['To suffer a minor injury', 'To avoid a challenge', 'To eat quickly'] },
    { idiom: 'Back to the drawing board', ans: 'To start over after a failure', wrong: ['To return to school', 'To revisit old notes', 'To finish a drawing'] },
    { idiom: 'Call it a day', ans: 'To stop working for the day', wrong: ['To name a new holiday', 'To work all day', 'To start a new job'] },
    { idiom: 'A close shave', ans: 'A very narrow escape from danger', wrong: ['A clean haircut', 'A minor accident', 'A careful calculation'] },
    { idiom: 'To be in hot water', ans: 'To be in trouble', wrong: ['To be in a sauna', 'To be very thirsty', 'To be extremely wealthy'] },
    { idiom: "To pull someone's leg", ans: 'To tease someone playfully', wrong: ['To help someone walk', 'To injure someone', 'To praise someone'] },
    { idiom: 'Read between the lines', ans: 'To understand the hidden meaning', wrong: ['To read very quickly', 'To skip the difficult words', 'To correct mistakes'] },
    { idiom: 'Cost an arm and a leg', ans: 'To be very expensive', wrong: ['To be very cheap', 'To be priceless in value', 'To be dangerous'] },
    { idiom: 'Sit on the fence', ans: 'To avoid taking a side', wrong: ['To sit for a long time', 'To be indecisive about money', 'To climb a high wall'] },
    { idiom: 'Throw in the towel', ans: 'To give up', wrong: ['To win a match', 'To offer help', 'To begin a fight'] },
    { idiom: 'A storm in a teacup', ans: 'Great excitement over a trivial matter', wrong: ['A violent weather event', 'A serious national crisis', 'A delicious hot drink'] },
    { idiom: 'Keep your chin up', ans: 'To stay cheerful in difficult times', wrong: ['To look down in shame', 'To remain silent always', 'To walk with pride'] },
    { idiom: 'Take something with a pinch of salt', ans: 'To not believe something completely', wrong: ['To add flavour to food', 'To accept everything literally', 'To refuse to listen'] },
    { idiom: 'On cloud nine', ans: 'Extremely happy', wrong: ['Deeply sad', 'Very confused', 'Seriously ill'] }
  ],
  GRAMMAR: [
    { q: 'She has been living in Mumbai ____ 2010.', ans: 'since', wrong: ['for', 'from', 'by'] },
    { q: 'The meeting will be held ____ Monday.', ans: 'on', wrong: ['at', 'in', 'by'] },
    { q: 'He is good ____ mathematics.', ans: 'at', wrong: ['in', 'on', 'with'] },
    { q: 'She is afraid ____ dogs.', ans: 'of', wrong: ['from', 'by', 'to'] },
    { q: 'I am interested ____ learning French.', ans: 'in', wrong: ['at', 'on', 'for'] },
    { q: 'The cat is sitting ____ the table.', ans: 'under', wrong: ['above', 'at', 'from'] },
    { q: 'We arrived ____ the airport early.', ans: 'at', wrong: ['in', 'on', 'to'] },
    { q: 'They went ____ a walk after dinner.', ans: 'for', wrong: ['at', 'on', 'with'] },
    { q: 'He has been waiting here ____ two hours.', ans: 'for', wrong: ['since', 'from', 'by'] },
    { q: 'The book is kept ____ the shelf.', ans: 'on', wrong: ['at', 'in', 'between'] },
    { q: 'She is married ____ a doctor.', ans: 'to', wrong: ['with', 'by', 'of'] },
    { q: 'I will meet you ____ 5 pm.', ans: 'at', wrong: ['in', 'on', 'by'] },
    { q: 'The train departs ____ 7 am sharp.', ans: 'at', wrong: ['on', 'in', 'since'] },
    { q: 'He is fond ____ reading novels.', ans: 'of', wrong: ['in', 'at', 'to'] },
    { q: 'She was angry ____ me.', ans: 'with', wrong: ['at', 'on', 'to'] },
    { q: 'He apologized ____ being late.', ans: 'for', wrong: ['of', 'at', 'to'] },
    { q: 'The house is built ____ stone.', ans: 'of', wrong: ['by', 'from', 'in'] },
    { q: 'The bridge was built ____ the river.', ans: 'over', wrong: ['under', 'in', 'on'] },
    { q: 'She has been suffering ____ fever since Monday.', ans: 'from', wrong: ['with', 'of', 'by'] },
    { q: 'He is senior ____ me in the office.', ans: 'to', wrong: ['than', 'from', 'of'] },
    { q: 'She prefers tea ____ coffee.', ans: 'to', wrong: ['than', 'over', 'from'] },
    { q: 'He was absent ____ school yesterday.', ans: 'from', wrong: ['at', 'in', 'for'] },
    { q: 'The plane flew ____ the mountains.', ans: 'over', wrong: ['under', 'through', 'below'] },
    { q: 'We must abide ____ the rules.', ans: 'by', wrong: ['to', 'with', 'at'] },
    { q: 'He congratulated her ____ her success.', ans: 'on', wrong: ['for', 'at', 'with'] },
    { q: 'She is popular ____ her colleagues.', ans: 'with', wrong: ['among', 'for', 'to'] },
    { q: 'He died ____ cancer last year.', ans: 'of', wrong: ['from', 'with', 'by'] },
    { q: 'She is capable ____ doing the work.', ans: 'of', wrong: ['to', 'for', 'in'] },
    { q: 'The problem has been discussed ____ the committee.', ans: 'by', wrong: ['from', 'at', 'on'] },
    { q: 'He was accused ____ theft.', ans: 'of', wrong: ['with', 'for', 'at'] },
    { q: 'She prevented him ____ going out.', ans: 'from', wrong: ['to', 'of', 'at'] },
    { q: 'I am proud ____ my country.', ans: 'of', wrong: ['for', 'at', 'in'] },
    { q: 'He jumped ____ the river to save the child.', ans: 'into', wrong: ['at', 'from', 'onto'] },
    { q: 'The cat jumped ____ the table.', ans: 'onto', wrong: ['into', 'at', 'from'] },
    { q: 'We sat ____ the shade of a tree.', ans: 'in', wrong: ['under', 'at', 'on'] },
    { q: 'He works ____ a bank.', ans: 'at', wrong: ['in', 'on', 'with'] },
    { q: 'She lives ____ Chennai.', ans: 'in', wrong: ['at', 'on', 'by'] },
    { q: 'He is weak ____ English.', ans: 'in', wrong: ['at', 'on', 'with'] },
    { q: 'I agree ____ your proposal.', ans: 'to', wrong: ['with', 'at', 'on'] },
    { q: 'He is adept ____ making excuses.', ans: 'at', wrong: ['in', 'of', 'with'] },
    { q: 'He is ____ honest man.', ans: 'an', wrong: ['a', 'the', 'no article'] },
    { q: 'She is ____ university student.', ans: 'a', wrong: ['an', 'the', 'no article'] },
    { q: '____ Ganges is a holy river.', ans: 'the', wrong: ['a', 'an', 'no article'] },
    { q: 'He gave me ____ piece of useful advice.', ans: 'a', wrong: ['an', 'the', 'no article'] },
    { q: 'She plays ____ piano well.', ans: 'the', wrong: ['a', 'an', 'no article'] },
    { q: 'I had ____ egg for breakfast.', ans: 'an', wrong: ['a', 'the', 'no article'] },
    { q: 'He is ____ MLA.', ans: 'an', wrong: ['a', 'the', 'no article'] },
    { q: '____ honest answer is always appreciated.', ans: 'an', wrong: ['a', 'the', 'no article'] },
    { q: 'She bought ____ umbrella.', ans: 'an', wrong: ['a', 'the', 'no article'] },
    { q: '____ sun rises in the east.', ans: 'the', wrong: ['a', 'an', 'no article'] },
    { q: 'He is ____ European.', ans: 'a', wrong: ['an', 'the', 'no article'] },
    { q: 'This is ____ most interesting book.', ans: 'the', wrong: ['a', 'an', 'no article'] },
    { q: 'We saw ____ one-eyed man.', ans: 'a', wrong: ['an', 'the', 'no article'] },
    { q: 'He is ____ heir to the throne.', ans: 'the', wrong: ['a', 'an', 'no article'] },
    { q: 'India won ____ match yesterday.', ans: 'the', wrong: ['a', 'an', 'no article'] },
    { q: 'He is ____ best player in the team.', ans: 'the', wrong: ['a', 'an', 'no article'] },
    { q: 'I need ____ new car.', ans: 'a', wrong: ['an', 'the', 'no article'] },
    { q: 'She gave me ____ hour to decide.', ans: 'an', wrong: ['a', 'the', 'no article'] },
    { q: 'He is ____ honest officer.', ans: 'an', wrong: ['a', 'the', 'no article'] },
    { q: 'Do you have ____ pen?', ans: 'a', wrong: ['an', 'the', 'no article'] },
    { q: 'Work hard ____ you will fail.', ans: 'or', wrong: ['and', 'but', 'so'] },
    { q: 'He is poor ____ happy.', ans: 'but', wrong: ['and', 'or', 'so'] },
    { q: 'She sings ____ dances well.', ans: 'and', wrong: ['but', 'or', 'so'] },
    { q: 'I waited ____ he came.', ans: 'until', wrong: ['but', 'and', 'so'] },
    { q: '____ he is old, he is active.', ans: 'though', wrong: ['because', 'since', 'if'] },
    { q: 'He ran fast ____ he could catch the train.', ans: 'so that', wrong: ['because', 'although', 'unless'] },
    { q: 'I will not go ____ you come.', ans: 'unless', wrong: ['because', 'if', 'although'] },
    { q: '____ you work hard, you will pass.', ans: 'if', wrong: ['unless', 'though', 'because'] },
    { q: 'She is neither smart ____ hardworking.', ans: 'nor', wrong: ['or', 'and', 'but'] },
    { q: 'He is both intelligent ____ hardworking.', ans: 'and', wrong: ['but', 'or', 'nor'] },
    { q: 'No sooner did he see me ____ he ran away.', ans: 'than', wrong: ['then', 'when', 'that'] },
    { q: 'Hardly had I left ____ it started raining.', ans: 'when', wrong: ['than', 'then', 'that'] },
    { q: 'He is not only a singer ____ a dancer.', ans: 'but also', wrong: ['but', 'and also', 'or'] },
    { q: 'Take an umbrella ____ it rains.', ans: 'in case', wrong: ['so that', 'because', 'unless'] },
    { q: '____ the rain, the match continued.', ans: 'despite', wrong: ['although', 'because', 'unless'] },
    { q: 'He worked hard ____ he failed.', ans: 'but', wrong: ['and', 'so', 'or'] },
    { q: 'She is tired ____ she slept well.', ans: 'although', wrong: ['because', 'so', 'and'] },
    { q: 'She kept smiling ____ she was in pain.', ans: 'although', wrong: ['because', 'so', 'unless'] },
    { q: 'I will help you ____ you need me.', ans: 'whenever', wrong: ['whatever', 'wherever', 'however'] },
    { q: 'You must leave now ____ you will miss the bus.', ans: 'or', wrong: ['and', 'but', 'so'] },
    { q: 'She ____ to school every day.', ans: 'goes', wrong: ['go', 'going', 'gone'] },
    { q: 'They ____ a movie last night.', ans: 'watched', wrong: ['watch', 'watches', 'watching'] },
    { q: 'He ____ his homework before dinner.', ans: 'finished', wrong: ['finish', 'finishes', 'finishing'] },
    { q: 'I ____ my lunch when the phone rang.', ans: 'was having', wrong: ['have', 'had', 'having'] },
    { q: 'By next year, she ____ in Delhi for ten years.', ans: 'will have lived', wrong: ['will live', 'has lived', 'will living'] },
    { q: 'We ____ this project by tomorrow.', ans: 'will finish', wrong: ['finish', 'finishing', 'finished'] },
    { q: 'She ____ in this company since 2015.', ans: 'has worked', wrong: ['is working', 'worked', 'works'] },
    { q: 'The train ____ before we reached the station.', ans: 'had left', wrong: ['left', 'leaves', 'has left'] },
    { q: 'If I ____ you, I would accept the offer.', ans: 'were', wrong: ['was', 'am', 'be'] },
    { q: 'He ____ tennis every Sunday.', ans: 'plays', wrong: ['play', 'playing', 'played'] },
    { q: 'She ____ a letter to her friend last week.', ans: 'wrote', wrong: ['write', 'writes', 'writing'] },
    { q: 'I ____ this movie already.', ans: 'have seen', wrong: ['saw', 'seen', 'seeing'] },
    { q: 'They ____ in this city since 2010.', ans: 'have lived', wrong: ['are living', 'lived', 'were living'] },
    { q: 'Look! It ____ outside.', ans: 'is raining', wrong: ['rains', 'rained', 'raining'] },
    { q: 'The sun ____ in the east.', ans: 'rises', wrong: ['rise', 'rising', 'rose'] },
    { q: 'He ____ when the accident happened.', ans: 'was driving', wrong: ['drove', 'drives', 'has driven'] },
    { q: 'She ____ dinner by the time I arrived.', ans: 'had cooked', wrong: ['cooked', 'cooks', 'is cooking'] },
    { q: 'I ____ to the market tomorrow.', ans: 'will go', wrong: ['go', 'went', 'going'] },
    { q: 'They ____ the project when the power went off.', ans: 'were completing', wrong: ['completed', 'completes', 'have completed'] },
    { q: 'He ____ to the office at 9 am daily.', ans: 'goes', wrong: ['go', 'going', 'gone'] },
    { q: 'We ____ each other for years.', ans: 'have known', wrong: ['know', 'knew', 'are knowing'] },
    { q: 'She ____ her car when it started raining.', ans: 'was washing', wrong: ['washes', 'washed', 'is washing'] },
    { q: 'I ____ the book twice already.', ans: 'have read', wrong: ['reads', 'reading', 'was reading'] },
    { q: 'He ____ his keys somewhere in the house.', ans: 'has lost', wrong: ['lose', 'loses', 'losing'] },
    { q: 'They ____ a new house next month.', ans: 'will buy', wrong: ['buy', 'bought', 'buying'] },
    { q: 'She ____ English for five years now.', ans: 'has been learning', wrong: ['learns', 'learned', 'is learning'] },
    { q: 'I ____ my grandparents every summer.', ans: 'visit', wrong: ['visits', 'visited', 'visiting'] },
    { q: 'He ____ the letter before I arrived.', ans: 'had posted', wrong: ['posted', 'posts', 'is posting'] },
    { q: 'We ____ our dinner when the guests arrived.', ans: 'were having', wrong: ['have', 'had', 'having'] },
    { q: 'She ____ to become a doctor.', ans: 'wants', wrong: ['want', 'wanting', 'wanted'] },
    { q: 'The committee ____ decided to hold the meeting.', ans: 'has', wrong: ['have', 'are', 'were'] },
    { q: 'Neither of the boys ____ present.', ans: 'was', wrong: ['were', 'are', 'have been'] },
    { q: 'Each of the students ____ given a book.', ans: 'was', wrong: ['were', 'are', 'have'] },
    { q: 'The news ____ true.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'Mathematics ____ my favourite subject.', ans: 'is', wrong: ['are', 'were', 'am'] },
    { q: 'Ten rupees ____ not much nowadays.', ans: 'is', wrong: ['are', 'were', 'have'] },
    { q: 'A number of students ____ absent today.', ans: 'are', wrong: ['is', 'was', 'has'] },
    { q: 'The number of students ____ increasing.', ans: 'is', wrong: ['are', 'were', 'have'] },
    { q: 'Bread and butter ____ my breakfast.', ans: 'is', wrong: ['are', 'were', 'have'] },
    { q: 'The teacher along with the students ____ present.', ans: 'was', wrong: ['were', 'are', 'have'] },
    { q: 'Either Ram or his friends ____ responsible.', ans: 'are', wrong: ['is', 'was', 'has'] },
    { q: 'The cattle ____ grazing in the field.', ans: 'are', wrong: ['is', 'was', 'has'] },
    { q: 'Everyone ____ to follow the rules.', ans: 'has', wrong: ['have', 'are', 'were'] },
    { q: 'Some of the milk ____ spilt.', ans: 'was', wrong: ['were', 'are', 'have'] },
    { q: 'Many a man ____ died in the war.', ans: 'has', wrong: ['have', 'are', 'were'] },
    { q: 'The police ____ investigating the case.', ans: 'are', wrong: ['is', 'was', 'has'] },
    { q: 'There is ____ water in the glass.', ans: 'a little', wrong: ['a few', 'many', 'several'] },
    { q: 'She has ____ friends in the city.', ans: 'few', wrong: ['little', 'much', 'less'] },
    { q: 'I need ____ more time to finish.', ans: 'a little', wrong: ['a few', 'several', 'many'] },
    { q: 'There are not ____ apples left.', ans: 'many', wrong: ['much', 'little', 'some'] },
    { q: '____ of the students passed the exam.', ans: 'most', wrong: ['much', 'little', 'few'] },
    { q: 'Can I have ____ milk in my tea?', ans: 'some', wrong: ['few', 'many', 'several'] },
    { q: 'He has ____ money to buy a car.', ans: 'enough', wrong: ['too', 'much', 'many'] },
    { q: 'There is ____ sugar in the jar.', ans: 'a little', wrong: ['a few', 'many', 'several'] },
    { q: 'I have ____ work to do today.', ans: 'a lot of', wrong: ['many', 'a few', 'several'] },
    { q: '____ people came to the meeting.', ans: 'few', wrong: ['little', 'much', 'less'] },
    { q: 'The man ____ helped me was a stranger.', ans: 'who', wrong: ['whom', 'which', 'whose'] },
    { q: 'The book ____ you gave me is interesting.', ans: 'that', wrong: ['who', 'whom', 'whose'] },
    { q: 'This is the house ____ my father was born.', ans: 'where', wrong: ['who', 'whom', 'when'] },
    { q: 'The girl ____ car was stolen called the police.', ans: 'whose', wrong: ['who', 'whom', 'which'] },
    { q: 'He is the person ____ I met yesterday.', ans: 'whom', wrong: ['who', 'which', 'whose'] },
    { q: 'I know the reason ____ he left early.', ans: 'why', wrong: ['who', 'which', 'whom'] },
    { q: 'This is the pen ____ I wrote the letter.', ans: 'with which', wrong: ['who', 'whom', 'whose'] },
    { q: 'The children ____ play here are from our school.', ans: 'who', wrong: ['whom', 'which', 'whose'] },
    { q: 'I remember the day ____ we first met.', ans: 'when', wrong: ['who', 'whom', 'whose'] },
    { q: 'The book ____ cover is red is mine.', ans: 'whose', wrong: ['who', 'whom', 'which'] },
    { q: 'If I ____ you, I would accept the offer.', ans: 'were', wrong: ['was', 'am', 'be'] },
    { q: 'I wish I ____ harder last year.', ans: 'had studied', wrong: ['studied', 'would study', 'have studied'] },
    { q: 'She insisted that he ____ with them.', ans: 'come', wrong: ['came', 'comes', 'would come'] },
    { q: 'It is high time we ____ this project.', ans: 'completed', wrong: ['complete', 'will complete', 'would complete'] },
    { q: 'He asked me where ____ going.', ans: 'I was', wrong: ['was I', 'I were', 'am I'] },
    { q: 'The news ____ true.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'Each of the players ____ a medal.', ans: 'has received', wrong: ['have received', 'are receiving', 'were receiving'] },
    { q: 'Neither of the answers ____ correct.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'The police ____ looking for the thief.', ans: 'are', wrong: ['is', 'was', 'has been'] },
    { q: 'A number of students ____ absent today.', ans: 'were', wrong: ['was', 'is', 'has been'] },
    { q: 'The number of students ____ increasing every year.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'Either he or I ____ responsible.', ans: 'am', wrong: ['is', 'are', 'was'] },
    { q: 'The scissors ____ on the table.', ans: 'are', wrong: ['is', 'was', 'has been'] },
    { q: 'Bread and butter ____ a healthy breakfast.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'Slow and steady ____ the race.', ans: 'wins', wrong: ['win', 'won', 'has won'] },
    { q: 'Ten kilometres ____ a long distance.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'The committee ____ divided in its opinion.', ans: 'was', wrong: ['were', 'have been', 'are'] },
    { q: 'One of my friends ____ abroad.', ans: 'lives', wrong: ['live', 'are living', 'have lived'] },
    { q: 'Physics ____ an interesting subject.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'The mob ____ dispersed by the police.', ans: 'was', wrong: ['were', 'have been', 'are'] },
    { q: 'The staff ____ gone home for the day.', ans: 'have', wrong: ['has', 'is', 'was'] },
    { q: 'Half of the mangoes ____ rotten.', ans: 'were', wrong: ['was', 'is', 'has been'] },
    { q: 'Either of the two roads ____ to the station.', ans: 'leads', wrong: ['lead', 'are leading', 'have led'] },
    { q: 'The jury ____ divided in their opinion.', ans: 'were', wrong: ['was', 'is', 'has been'] },
    { q: 'Every boy and every girl ____ expected to attend.', ans: 'was', wrong: ['were', 'have been', 'are'] },
    { q: 'No one ____ allowed to enter without a pass.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'Many a student ____ this mistake.', ans: 'makes', wrong: ['make', 'have made', 'are making'] },
    { q: 'He is one of the best players who ____ ever played for India.', ans: 'have', wrong: ['has', 'was', 'were'] },
    { q: 'The government ____ announced new reforms.', ans: 'has', wrong: ['have', 'were', 'are'] },
    { q: 'The audience ____ clapping loudly.', ans: 'was', wrong: ['were', 'have been', 'are'] },
    { q: 'Neither the teacher nor the students ____ present.', ans: 'were', wrong: ['was', 'is', 'has been'] },
    { q: 'The United States ____ a powerful nation.', ans: 'is', wrong: ['are', 'were', 'have been'] },
    { q: 'The little ____ is better than the little we have.', ans: 'that', wrong: ['which', 'what', 'who'] },
    { q: 'He is senior ____ me in age.', ans: 'to', wrong: ['than', 'from', 'of'] },
    { q: 'She prefers tea ____ coffee.', ans: 'to', wrong: ['than', 'over', 'from'] },
    { q: 'The bridge was built ____ 1920.', ans: 'in', wrong: ['on', 'at', 'by'] },
    { q: 'He has been waiting ____ Monday.', ans: 'since', wrong: ['for', 'from', 'by'] },
    { q: 'The cat jumped ____ the table.', ans: 'onto', wrong: ['on', 'into', 'over'] },
    { q: 'She is afraid ____ dogs.', ans: 'of', wrong: ['from', 'with', 'about'] }
  ],
  SENTENCE: [
    { q: 'He has went to the market yesterday.', ans: 'He went to the market yesterday.', wrong: ['He has go to the market yesterday.', 'He has gone to the market yesterday.', 'He gone to the market yesterday.'] },
    { q: 'She do not like to wake up early.', ans: 'She does not like to wake up early.', wrong: ['She do not likes to wake up early.', 'She does not likes to wake up early.', 'She not like to wake up early.'] },
    { q: 'Each of the boys were given a prize.', ans: 'Each of the boys was given a prize.', wrong: ['Each of the boys are given a prize.', 'Each of the boys have been given a prize.', 'Each of the boys was give a prize.'] },
    { q: 'The furniture in this room are very old.', ans: 'The furniture in this room is very old.', wrong: ['The furniture in this room are being very old.', 'The furnitures in this room are very old.', 'The furniture in this room are very olden.'] },
    { q: 'He is one of the best player in the team.', ans: 'He is one of the best players in the team.', wrong: ['He is one of the best player of the team.', 'He is one of best players in the team.', 'He are one of the best players in the team.'] },
    { q: 'Neither of the answers were correct.', ans: 'Neither of the answers was correct.', wrong: ['Neither of the answer was correct.', 'Neither of the answers are correct.', 'Neither of the answers was not correct.'] },
    { q: 'She speaks English very fluent.', ans: 'She speaks English very fluently.', wrong: ['She speak English very fluently.', 'She speaks English more fluent.', 'She speaks English very fluency.'] },
    { q: 'The news are good today.', ans: 'The news is good today.', wrong: ['The news are being good today.', 'The news is good todays.', 'The news am good today.'] },
    { q: 'I have visited Goa last year.', ans: 'I visited Goa last year.', wrong: ['I have been visiting Goa last year.', 'I has visited Goa last year.', 'I visited Goa in last year.'] },
    { q: 'The children was playing in the garden.', ans: 'The children were playing in the garden.', wrong: ['The children was playing in the gardens.', 'The child were playing in the garden.', 'The children were plays in the garden.'] },
    { q: 'He asked me that where I lived.', ans: 'He asked me where I lived.', wrong: ['He asked me that where do I live.', 'He asked me where did I live.', 'He asked to me where I lived.'] },
    { q: 'The man whom came here is my uncle.', ans: 'The man who came here is my uncle.', wrong: ['The man whose came here is my uncle.', 'The man which came here is my uncle.', 'The man who come here is my uncle.'] },
    { q: 'I prefer tea than coffee.', ans: 'I prefer tea to coffee.', wrong: ['I prefer tea from coffee.', 'I prefer tea with coffee.', 'I prefer tea than coffees.'] },
    { q: 'He is senior than me.', ans: 'He is senior to me.', wrong: ['He is senior from me.', 'He is senior of me.', 'He is senior then me.'] },
    { q: 'She has been working in this office for 2015.', ans: 'She has been working in this office since 2015.', wrong: ['She has been working in this office for the 2015.', 'She has been working in this office since two years.', 'She have been working in this office since 2015.'] },
    { q: 'One of my friend lives in Delhi.', ans: 'One of my friends lives in Delhi.', wrong: ['One of my friend live in Delhi.', 'One of my friends lives Delhi.', 'One of my friends does lives in Delhi.'] },
    { q: 'The sceneries of Kashmir are beautiful.', ans: 'The scenery of Kashmir is beautiful.', wrong: ['The sceneries of Kashmir is beautiful.', 'The scenery of Kashmir are being beautiful.', 'The scenery of Kashmir are beautiful.'] },
    { q: 'He has a white hair.', ans: 'He has white hair.', wrong: ['He has a white hairs.', 'He have a white hair.', 'He has an white hair.'] },
    { q: 'I bought some scissor yesterday.', ans: 'I bought some scissors yesterday.', wrong: ['I bought a scissor yesterday.', 'I bought some pair of scissors yesterday.', 'I buys some scissors yesterday.'] },
    { q: 'She advised me to not go there.', ans: 'She advised me not to go there.', wrong: ['She advised me to not going there.', 'She advised me for not go there.', 'She advised me not go there.'] },
    { q: 'It is raining since morning.', ans: 'It has been raining since morning.', wrong: ['It is rained since morning.', 'It has raining since morning.', 'It have been raining since morning.'] },
    { q: 'The teacher told to the students to be quiet.', ans: 'The teacher told the students to be quiet.', wrong: ['The teacher told to the students be quiet.', 'The teacher told the students for being quiet.', 'The teacher told to the students for quiet.'] },
    { q: 'He does not knows the answer.', ans: 'He does not know the answer.', wrong: ['He do not knows the answer.', 'He does not knows the answers.', 'He does not knew the answer.'] },
    { q: 'Whom do you think is the culprit?', ans: 'Who do you think is the culprit?', wrong: ['Whom do you think is the culprits?', 'Whom do you think are the culprit?', 'Whose do you think is the culprit?'] },
    { q: 'She is married with a rich businessman.', ans: 'She is married to a rich businessman.', wrong: ['She is married with a rich businessmen.', 'She is married to a rich businessmen.', 'She is marry to a rich businessman.'] },
    { q: 'Neither the teacher nor the students was present.', ans: 'Neither the teacher nor the students were present.', wrong: ['Neither the teacher nor the students was present now.', 'Neither the teacher nor the student were present.', 'Either the teacher nor the students were present.'] },
    { q: 'He asked whether I am going to the party.', ans: 'He asked whether I was going to the party.', wrong: ['He asked that whether I was going to the party.', 'He asked whether was I going to the party.', 'He asked whether I were going to the party.'] },
    { q: 'The information given by him were wrong.', ans: 'The information given by him was wrong.', wrong: ['The informations given by him were wrong.', 'The information given by him were being wrong.', 'The information given by him was wrongs.'] },
    { q: 'He told that he will come tomorrow.', ans: 'He said that he would come the next day.', wrong: ['He told that he would come the next day.', 'He said that he will come the next day.', 'He said to that he would come the next day.'] },
    { q: 'If I was you, I would not accept this offer.', ans: 'If I were you, I would not accept this offer.', wrong: ['If I was you, I would not accepts this offer.', 'If I were you, I will not accept this offer.', 'If I were you, I would not accepted this offer.'] },
    { q: 'The prices of essential commodities have raised recently.', ans: 'The prices of essential commodities have risen recently.', wrong: ['The prices of essential commodities have raised recently up.', 'The prices of essential commodity have risen recently.', 'The prices of essential commodities has risen recently.'] },
    { q: 'He laid down for a rest after lunch.', ans: 'He lay down for a rest after lunch.', wrong: ['He laid down for an rest after lunch.', 'He lie down for a rest after lunch.', 'He laid down for a rest after the lunch.'] },
    { q: 'The boy dived in the pool.', ans: 'The boy dived into the pool.', wrong: ['The boy dived in to the pool.', 'The boy dive into the pool.', 'The boys dived into the pool.'] },
    { q: 'She can sings very well.', ans: 'She can sing very well.', wrong: ['She cans sing very well.', 'She can sang very well.', 'She can singing very well.'] },
    { q: 'This is the same watch which I lost.', ans: 'This is the same watch that I lost.', wrong: ['This is the same watch which I losed.', 'This is the same watches which I lost.', 'This is the same watch which me lost.'] },
    { q: 'Me and my friend went to the market.', ans: 'My friend and I went to the market.', wrong: ['I and my friend went to the market.', 'My friend and me went to the market.', 'My friend and I goes to the market.'] },
    { q: 'The mother along with her children were present.', ans: 'The mother along with her children was present.', wrong: ['The mother along with her children was being present.', 'The mother with her children were present.', 'The mother along with her child were present.'] },
    { q: 'He is suffering from fever since Monday.', ans: 'He has been suffering from fever since Monday.', wrong: ['He is suffering with fever since Monday.', 'He was suffering from fever since Monday.', 'He is suffering from fever from Monday.'] },
    { q: 'The jury was divided in their opinion.', ans: 'The jury were divided in their opinion.', wrong: ['The jury was divided in his opinion.', 'The jury were divided in its opinion.', 'The jury was divided in their opinions.'] },
    { q: 'She is more taller than her sister.', ans: 'She is taller than her sister.', wrong: ['She is more tall than her sister.', 'She is more taller than her sister does.', 'She is taller of her sister.'] },
    { q: 'He succeeded by dint of hard working.', ans: 'He succeeded by dint of hard work.', wrong: ['He succeeded by dint of hard works.', 'He succeeded in dint of hard work.', 'He succeeds by dint of hard work.'] },
    { q: 'No sooner did the bell ring then the students left.', ans: 'No sooner did the bell ring than the students left.', wrong: ['No sooner the bell rang than the students left.', 'No sooner did the bell ring that the students left.', 'No sooner did the bell rings than the students left.'] },
    { q: 'He is elder than his brother.', ans: 'He is elder to his brother.', wrong: ['He is elder than his brother.', 'He is elder from his brother.', 'He is more elder to his brother.'] },
    { q: 'She is looking forward to meet you.', ans: 'She is looking forward to meeting you.', wrong: ['She is looking forward for meet you.', 'She is looking forward to meets you.', 'She is looking forward to met you.'] },
    { q: 'He is good in mathematics.', ans: 'He is good at mathematics.', wrong: ['He is good to mathematics.', 'He is good in the mathematics.', 'He is good at the mathematics.'] },
    { q: 'The two first chapters are easy.', ans: 'The first two chapters are easy.', wrong: ['The first two chapters is easy.', 'The first two chapter are easy.', 'The first two chapters are easily.'] },
    { q: 'He is enough strong to lift the box.', ans: 'He is strong enough to lift the box.', wrong: ['He is enough strong to lifts the box.', 'He is strong enough to lifting the box.', 'He is strong enough for to lift the box.'] },
    { q: 'The teacher, as well as the students, are going.', ans: 'The teacher, as well as the students, is going.', wrong: ['The teacher, as well as the students, were going.', 'The teacher, as well as the students, is go.', 'The teachers, as well as the students, is going.'] },
    { q: 'It is I who is responsible.', ans: 'It is I who am responsible.', wrong: ['It is me who am responsible.', 'It is I who are responsible.', 'It is I whom is responsible.'] },
    { q: 'Each of the students have submitted their work.', ans: 'Each of the students has submitted his work.', wrong: ['Each of the students has submitted their works.', 'Each of the student has submitted his work.', 'Each of the students have submitted his work.'] },
    { q: 'He took the book from the table and leave the room.', ans: 'He took the book from the table and left the room.', wrong: ['He takes the book from the table and left the room.', 'He took the book from the table and leaves the room.', 'He took the book from the table and leave the rooms.'] },
    { q: 'She is one of the tallest girl in her class.', ans: 'She is one of the tallest girls in her class.', wrong: ['She is the tallest girls in her class.', 'She is one of the tallest girls of her class.', 'She is one of the tallest girl in their class.'] },
    { q: 'He told her that she has passed the exam.', ans: 'He told her that she had passed the exam.', wrong: ['He told her that she have passed the exam.', 'He told her that she has pass the exam.', 'He told to her that she had passed the exam.'] },
    { q: 'The scissors is not sharp.', ans: 'The scissors are not sharp.', wrong: ['The scissor are not sharp.', 'The scissors are not sharpen.', 'The scissors be not sharp.'] },
    { q: 'A large number of people was present.', ans: 'A large number of people were present.', wrong: ['A large number of people were being present.', 'A large numbers of people were present.', 'A large number of the people were present.'] },
    { q: 'He works hardly to support his family.', ans: 'He works hard to support his family.', wrong: ['He works hardly to supporting his family.', 'He work hard to support his family.', 'He works hard for to support his family.'] },
    { q: 'She wore a blue beautiful saree.', ans: 'She wore a beautiful blue saree.', wrong: ['She wore a beautiful saree blue.', 'She wore a blue beautiful sarees.', 'She wore beautiful blue saree.'] },
    { q: 'It was the most unique experience of my life.', ans: 'It was a unique experience of my life.', wrong: ['It was the most uniquest experience of my life.', 'It was a very unique experiences of my life.', 'It was the most unique experience of my lives.'] },
    { q: 'She not only lost her purse but also her mobile.', ans: 'She lost not only her purse but also her mobile.', wrong: ['She lost her purse not only but also her mobile.', 'She not only lost her purse but her mobile also.', 'She not only lost her purse but also lost her mobiles.'] },
    { q: 'He does not know nothing about it.', ans: 'He does not know anything about it.', wrong: ['He does not know nothing about the it.', 'He do not know anything about it.', 'He does not knows anything about it.'] },
    { q: "She don't like coffee at all.", ans: "She doesn't like coffee at all.", wrong: ['She do not like coffee at all.', 'She does not liking coffee at all.', 'She are not liking coffee at all.'] },
    { q: 'I am knowing him since 2010.', ans: 'I have known him since 2010.', wrong: ['I know him since 2010.', 'I am knowing him since 2010.', 'I has known him since 2010.'] },
    { q: 'Neither of the boys have come.', ans: 'Neither of the boys has come.', wrong: ['Neither of the boys have came.', 'Neither of the boys are coming.', 'Neither of the boys has came.'] },
    { q: 'The sceneries of Kashmir are beautiful.', ans: 'The scenery of Kashmir is beautiful.', wrong: ['The scenery of Kashmir are beautiful.', 'The sceneries of Kashmir is beautiful.', 'The scenery of the Kashmir is beautiful.'] },
    { q: 'He told that he was busy.', ans: 'He said that he was busy.', wrong: ['He told me that he was busy.', 'He said to that he was busy.', 'He told that he is busy.'] },
    { q: 'One of my friend is coming today.', ans: 'One of my friends is coming today.', wrong: ['One of my friend are coming today.', 'One of my friends are coming today.', 'One of my friend is come today.'] },
    { q: 'The news are not good.', ans: 'The news is not good.', wrong: ['The news are not good.', 'The news were not good.', 'A news is not good.'] },
    { q: 'I prefer tea than coffee.', ans: 'I prefer tea to coffee.', wrong: ['I prefer tea over coffee.', 'I prefer tea from coffee.', 'I prefer tea and coffee.'] },
    { q: 'No sooner did he arrive than the meeting started.', ans: 'No sooner had he arrived than the meeting started.', wrong: ['No sooner did he arrive then the meeting started.', 'No sooner he arrived than the meeting started.', 'No sooner he had arrived when the meeting started.'] },
    { q: "She is senior than me.", ans: "She is senior to me.", wrong: ["She is senior than I.", "She is more senior than me.", "She is senior from me."] },
    { q: 'If he had worked hard he would pass.', ans: 'If he had worked hard he would have passed.', wrong: ['If he had worked hard he would pass.', 'If he had worked hard he will pass.', 'If he worked hard he would have passed.'] },
    { q: 'He has completed his work yesterday.', ans: 'He completed his work yesterday.', wrong: ['He has completed his work yesterday.', 'He had complete his work yesterday.', 'He completed his works yesterday.'] },
    { q: 'The committee are of the same opinion.', ans: 'The committee is of the same opinion.', wrong: ['The committee have of the same opinion.', 'The committee were of the same opinion.', 'The committees is of the same opinion.'] },
    { q: 'I asked him that what he wanted.', ans: 'I asked him what he wanted.', wrong: ['I asked him that what he wanted.', 'I asked to him what he wanted.', 'I asked him that he wanted what.'] },
    { q: 'He is the tallest of all the boys.', ans: 'He is the tallest of all boys.', wrong: ['He is the tallest of all the boys.', 'He is tallest of all the boys.', 'He is the most tallest of all boys.'] },
    { q: 'She as well as her friends are coming.', ans: 'She as well as her friends is coming.', wrong: ['She as well as her friends are coming.', 'She as well as her friends have coming.', 'She as well as her friends were coming.'] },
    { q: 'The students along with the teacher has left.', ans: 'The students along with the teacher have left.', wrong: ['The students along with the teacher has left.', 'The students along with teacher have left.', 'The students along the teacher have left.'] },
    { q: 'He denied to accept the gift.', ans: 'He refused to accept the gift.', wrong: ['He denied to accept the gift.', 'He refused accepting the gift.', 'He denied accepting the gifts.'] },
    { q: 'The weather was too hot to go out.', ans: 'The weather was too hot to go out.', wrong: ['The weather was too hot to going out.', 'The weather was too hot for go out.', 'The weather was so hot to go out.'] },
    { q: 'I have not met him since two years.', ans: 'I have not met him for two years.', wrong: ['I have not met him since two years.', 'I had not met him since two years.', 'I have not met him from two years.'] },
    { q: "He works hardly to support his family.", ans: "He works hard to support his family.", wrong: ["He works hardly to support his family.", "He hard works to support his family.", "He works hardest to support his family."] },
    { q: 'The boy fell down from the bicycle.', ans: 'The boy fell off the bicycle.', wrong: ['The boy fell down from the bicycle.', 'The boy fell of the bicycle.', 'The boy fell down off the bicycle.'] },
    { q: 'I cannot cope up with this pressure.', ans: 'I cannot cope with this pressure.', wrong: ['I cannot cope up with this pressure.', 'I cannot cope on this pressure.', 'I cannot cope of this pressure.'] },
    { q: 'Do you know where is the station?', ans: 'Do you know where the station is?', wrong: ['Do you know where is the station?', 'Do you know that where is the station?', 'Do you know where the station are?'] },
    { q: 'She asked me why did I go there.', ans: 'She asked me why I went there.', wrong: ['She asked me why did I go there.', 'She asked me why did I went there.', 'She asked me that why I went there.'] },
    { q: 'There are fewer people in the hall today.', ans: 'There are fewer people in the hall today.', wrong: ['There are less people in the hall today.', 'There is fewer people in the hall today.', 'There are fewer person in the hall today.'] },
    { q: 'The house is built of bricks.', ans: 'The house is built of bricks.', wrong: ['The house is built by bricks.', 'The house is built from bricks.', 'The house is built with bricks.'] },
    { q: 'He succeeded because of his hard work.', ans: 'He succeeded because of his hard work.', wrong: ['He succeeded because his hard work.', 'He succeeded on account his hard work.', 'He succeeded due his hard work.'] },
    { q: 'I want to buy a pair of scissors.', ans: 'I want to buy a pair of scissors.', wrong: ['I want to buy a scissors.', 'I want to buy a pair of scissor.', 'I want to buy two scissors.'] }
  ]
};
