module.exports = {
  GA: [
    { q: 'In which year was the Reserve Bank of India established?', ans: '1935', wrong: ['1921', '1949', '1947'] },
    { q: 'Where is the headquarters of the Reserve Bank of India located?', ans: 'Mumbai', wrong: ['New Delhi', 'Kolkata', 'Chennai'] },
    { q: 'In which year was the Reserve Bank of India nationalized?', ans: '1949', wrong: ['1955', '1947', '1960'] },
    { q: 'Who was the first Governor of the Reserve Bank of India?', ans: 'Sir Osborne Smith', wrong: ['C. D. Deshmukh', 'H. V. R. Iengar', 'L. K. Jha'] },
    { q: 'Who was the first Indian Governor of the Reserve Bank of India?', ans: 'C. D. Deshmukh', wrong: ['Raghuram Rajan', 'Bimal Jalan', 'S. Jagannathan'] },
    { q: 'What does CRR stand for?', ans: 'Cash Reserve Ratio', wrong: ['Capital Reserve Ratio', 'Cash Reserve Rate', 'Central Reserve Rate'] },
    { q: 'Banks are required to maintain CRR with whom?', ans: 'Reserve Bank of India', wrong: ['Government of India', 'NABARD', 'State Bank of India'] },
    { q: 'What does SLR stand for?', ans: 'Statutory Liquidity Ratio', wrong: ['Statutory Liquidity Reserve', 'Savings Liquidity Ratio', 'Statutory Loan Ratio'] },
    { q: 'Banks maintain SLR in the form of', ans: 'Cash, gold and approved government securities', wrong: ['Only cash kept in the vault', 'Only foreign currencies', 'Shares of other companies'] },
    { q: 'Repo rate is the rate at which', ans: 'RBI lends short-term funds to banks', wrong: ['RBI borrows funds from banks', 'Banks lend to the public', 'RBI lends to the government'] },
    { q: 'Reverse repo rate is the rate at which', ans: 'RBI borrows funds from banks', wrong: ['RBI lends funds to banks', 'Banks borrow from the public', 'RBI lends to the government'] },
    { q: 'What does MSF stand for?', ans: 'Marginal Standing Facility', wrong: ['Major Standing Facility', 'Marginal Savings Facility', 'Market Standing Fund'] },
    { q: 'The Bank Rate is the rate at which', ans: 'RBI lends long-term funds to banks', wrong: ['RBI borrows from banks', 'Banks pay on fixed deposits', 'Banks lend to customers'] },
    { q: 'What does NEFT stand for?', ans: 'National Electronic Funds Transfer', wrong: ['National Electronic Financial Transfer', 'National Emergency Fund Transfer', 'National Electronic Foreign Transfer'] },
    { q: 'What does RTGS stand for?', ans: 'Real Time Gross Settlement', wrong: ['Real Time Group Settlement', 'Rapid Time Gross Settlement', 'Real Time General Settlement'] },
    { q: 'The minimum amount for RTGS transactions in India is', ans: 'Rs 2 lakh', wrong: ['Rs 1 lakh', 'Rs 50,000', 'Rs 5 lakh'] },
    { q: 'What does UPI stand for?', ans: 'Unified Payments Interface', wrong: ['Universal Payment Interface', 'Unified Payment Index', 'Universal Payment Index'] },
    { q: 'UPI is operated and developed by', ans: 'NPCI', wrong: ['SEBI', 'SIDBI', 'IRDAI'] },
    { q: 'What does IMPS stand for?', ans: 'Immediate Payment Service', wrong: ['Instant Money Payment System', 'Immediate Money Payment Service', 'Internet Mobile Payment Service'] },
    { q: 'What does AePS stand for?', ans: 'Aadhaar Enabled Payment System', wrong: ['Aadhaar Electronic Payment Service', 'Authenticated Electronic Payment System', 'Aadhaar Enabled Personal System'] },
    { q: 'The Basel Committee on Banking Supervision is headquartered in', ans: 'Basel, Switzerland', wrong: ['Geneva, Switzerland', 'Zurich, Switzerland', 'Paris, France'] },
    { q: 'Basel III norms were introduced in response to', ans: 'the 2008 global financial crisis', wrong: ['the 1997 Asian financial crisis', 'the 1973 oil crisis', 'the 2015 European debt crisis'] },
    { q: 'What does NPA stand for?', ans: 'Non-Performing Asset', wrong: ['National Performing Asset', 'Non-Provisioned Account', 'Net Performing Asset'] },
    { q: 'A loan is treated as an NPA when its payment is overdue for at least', ans: '90 days', wrong: ['30 days', '60 days', '180 days'] },
    { q: 'Which account is mainly meant for personal savings and earns interest?', ans: 'Savings account', wrong: ['Current account', 'Overdraft account', 'Cash credit account'] },
    { q: 'Which account is meant for daily business transactions and normally earns no interest?', ans: 'Current account', wrong: ['Savings account', 'Recurring deposit account', 'Fixed deposit account'] },
    { q: 'A fixed deposit is best described as', ans: 'a deposit locked for a fixed tenure at a higher rate', wrong: ['a deposit withdrawable anytime', 'an account for daily business use', 'a monthly recurring deposit'] },
    { q: 'A recurring deposit is best described as', ans: 'a deposit made in fixed monthly instalments', wrong: ['a one-time lump sum deposit', 'an account with no interest', 'a credit card repayment'] },
    { q: 'In 2020 Punjab National Bank was merged with', ans: 'Oriental Bank of Commerce and United Bank of India', wrong: ['Canara Bank and Syndicate Bank', 'Bank of India and IDBI Bank', 'Dena Bank and Vijaya Bank'] },
    { q: 'Canara Bank was merged with which bank in 2020?', ans: 'Syndicate Bank', wrong: ['Oriental Bank of Commerce', 'United Bank of India', 'Andhra Bank'] },
    { q: 'HDFC Bank was merged with which company in 2023?', ans: 'HDFC Ltd', wrong: ['ICICI Ltd', 'LIC Housing Finance', 'Kotak Mahindra Bank'] },
    { q: 'State Bank of India merged its associate banks in which year?', ans: '2017', wrong: ['2015', '2019', '2020'] },
    { q: 'Where is the headquarters of the State Bank of India?', ans: 'Mumbai', wrong: ['New Delhi', 'Kolkata', 'Hyderabad'] },
    { q: 'Where is the headquarters of Bank of Baroda?', ans: 'Vadodara', wrong: ['Ahmedabad', 'Mumbai', 'New Delhi'] },
    { q: 'Where is the headquarters of Canara Bank?', ans: 'Bengaluru', wrong: ['Mumbai', 'Hyderabad', 'Chennai'] },
    { q: 'Where is the headquarters of Punjab National Bank?', ans: 'New Delhi', wrong: ['Mumbai', 'Lucknow', 'Kolkata'] },
    { q: 'Where is the headquarters of ICICI Bank?', ans: 'Mumbai', wrong: ['Ahmedabad', 'Bengaluru', 'New Delhi'] },
    { q: 'Where is the headquarters of HDFC Bank?', ans: 'Mumbai', wrong: ['Pune', 'Chennai', 'Gurugram'] },
    { q: 'Which was the first bank established in India?', ans: 'Bank of Hindostan', wrong: ['Reserve Bank of India', 'State Bank of India', 'Punjab National Bank'] },
    { q: 'Which is regarded as the first fully Indian-owned bank?', ans: 'Punjab National Bank', wrong: ['Bank of Baroda', 'Canara Bank', 'Allahabad Bank'] },
    { q: 'Which was the first Regional Rural Bank in India?', ans: 'Prathama Bank', wrong: ['Grameen Bank', 'Land Development Bank', 'State Bank of Bikaner'] },
    { q: 'Regional Rural Banks were established in which year?', ans: '1975', wrong: ['1980', '1969', '1990'] },
    { q: 'Deposits in banks are insured by DICGC up to', ans: 'Rs 5 lakh', wrong: ['Rs 1 lakh', 'Rs 2 lakh', 'Rs 10 lakh'] },
    { q: 'What does DICGC stand for?', ans: 'Deposit Insurance and Credit Guarantee Corporation', wrong: ['Deposit Investment and Credit Guarantee Corporation', 'Deposit Insurance and Central Guarantee Corporation', 'Deposit Insurance Corporation of India'] },
    { q: 'SEBI obtained statutory powers in which year?', ans: '1992', wrong: ['1988', '1994', '1998'] },
    { q: 'SEBI is the regulator of', ans: 'the securities market', wrong: ['the insurance sector', 'agriculture credit', 'microfinance institutions'] },
    { q: 'IRDAI is the regulator of', ans: 'the insurance sector', wrong: ['the securities market', 'stock exchanges', 'regional rural banks'] },
    { q: 'NABARD was established in which year?', ans: '1982', wrong: ['1975', '1969', '1990'] },
    { q: 'NABARD mainly focuses on', ans: 'agriculture and rural development', wrong: ['urban housing finance', 'export credit', 'infrastructure in cities'] },
    { q: 'SIDBI was established in which year?', ans: '1990', wrong: ['1982', '1975', '1995'] },
    { q: 'SIDBI mainly promotes', ans: 'small and medium industries', wrong: ['agriculture', 'exports of services', 'insurance business'] },
    { q: 'EXIM Bank of India mainly focuses on', ans: 'foreign trade', wrong: ['agriculture finance', 'housing finance', 'small industry loans'] },
    { q: 'The one rupee note in India is issued by', ans: 'the Government of India', wrong: ['the Reserve Bank of India', 'the State Bank of India', 'NABARD'] },
    { q: 'Currency notes in India are signed by', ans: 'the Governor of RBI', wrong: ['the Finance Minister', 'the President of India', 'the Finance Secretary'] },
    { q: 'Scheduled banks in India are listed in', ans: 'the Second Schedule of the RBI Act 1934', wrong: ['the First Schedule of the RBI Act', 'the Banking Regulation Act 1949', 'the Companies Act 2013'] },
    { q: 'Cooperative banks in India are regulated by', ans: 'the Reserve Bank of India', wrong: ['SEBI', 'IRDAI', 'NITI Aayog'] },
    { q: 'The tagline Pure Banking Nothing Else belongs to', ans: 'State Bank of India', wrong: ['ICICI Bank', 'HDFC Bank', 'Axis Bank'] },
    { q: 'Which bank uses the tagline Hum Hain Na?', ans: 'ICICI Bank', wrong: ['HDFC Bank', 'Axis Bank', 'Kotak Mahindra Bank'] },
    { q: 'What does BHIM stand for?', ans: 'Bharat Interface for Money', wrong: ['Banking Help Interface for Money', 'Bharat Investment Money', 'Basic Interface of Money'] },
    { q: 'Which of the following is an example of a Payments Bank?', ans: 'Airtel Payments Bank', wrong: ['State Bank of India', 'HDFC Bank', 'Bank of Baroda'] },
    { q: 'What does GDP stand for?', ans: 'Gross Domestic Product', wrong: ['Gross Domestic Production', 'General Domestic Product', 'Gross Developed Product'] },
    { q: 'GDP measures', ans: 'the total value of goods and services produced within the country', wrong: ['total exports only', 'the population of the country', 'total foreign exchange reserves'] },
    { q: 'What does GNP stand for?', ans: 'Gross National Product', wrong: ['General National Product', 'Gross National Production', 'Gross National Price'] },
    { q: 'GNP is equal to', ans: 'GDP plus net income from abroad', wrong: ['GDP minus total exports', 'total taxes collected', 'total foreign debt'] },
    { q: 'NNP is calculated as', ans: 'GNP minus depreciation', wrong: ['GDP plus subsidies', 'GNP plus taxes', 'GDP minus imports'] },
    { q: 'WPI measures changes in', ans: 'wholesale prices', wrong: ['retail prices', 'stock market prices', 'wages of workers'] },
    { q: 'CPI measures changes in', ans: 'retail prices', wrong: ['wholesale prices', 'producer prices', 'import prices'] },
    { q: 'Inflation measured through CPI is commonly called', ans: 'retail inflation', wrong: ['wholesale inflation', 'core inflation', 'wage inflation'] },
    { q: 'Core inflation excludes the prices of', ans: 'food and fuel', wrong: ['housing and rent', 'education services', 'clothing'] },
    { q: 'Fiscal policy is concerned with', ans: 'government revenue and expenditure', wrong: ['money supply in the economy', 'interest rates', 'foreign exchange rates'] },
    { q: 'Monetary policy is concerned with', ans: 'money supply and interest rates', wrong: ['government spending', 'taxation policy', 'customs duties'] },
    { q: 'In India monetary policy is decided by', ans: 'the Reserve Bank of India', wrong: ['the Ministry of Finance', 'SEBI', 'NITI Aayog'] },
    { q: 'Fiscal deficit is', ans: 'total expenditure minus total receipts excluding borrowings', wrong: ['expenditure minus tax revenue', 'exports minus imports', 'revenue expenditure minus revenue receipts'] },
    { q: 'Revenue deficit is', ans: 'revenue expenditure minus revenue receipts', wrong: ['capital expenditure minus capital receipts', 'total expenditure minus borrowings', 'fiscal deficit plus interest payments'] },
    { q: 'GST came into effect in India on', ans: '1 July 2017', wrong: ['1 April 2017', '1 January 2017', '1 April 2016'] },
    { q: 'The GST Council is chaired by', ans: 'the Union Finance Minister', wrong: ['the Prime Minister', 'the RBI Governor', 'the President of India'] },
    { q: 'Which is the highest GST slab in India?', ans: '28 percent', wrong: ['20 percent', '30 percent', '40 percent'] },
    { q: 'Which of the following is a direct tax?', ans: 'Income tax', wrong: ['GST', 'Excise duty', 'Customs duty'] },
    { q: 'Which of the following is an indirect tax?', ans: 'GST', wrong: ['Income tax', 'Corporate tax', 'Wealth tax'] },
    { q: 'Income tax in India is administered by', ans: 'the CBDT', wrong: ['the CBIC', 'SEBI', 'the Reserve Bank of India'] },
    { q: 'Customs and excise duties are administered by', ans: 'the CBIC', wrong: ['the CBDT', 'the RBI', 'NITI Aayog'] },
    { q: 'The Planning Commission of India was set up in', ans: '1950', wrong: ['1947', '1951', '1955'] },
    { q: 'NITI Aayog replaced the Planning Commission in', ans: '2015', wrong: ['2014', '2016', '2017'] },
    { q: 'NITI Aayog is chaired by', ans: 'the Prime Minister', wrong: ['the President of India', 'the Finance Minister', 'the RBI Governor'] },
    { q: 'The first Five Year Plan of India covered the period', ans: '1951 to 1956', wrong: ['1947 to 1952', '1956 to 1961', '1950 to 1955'] },
    { q: 'Bombay Stock Exchange was established in', ans: '1875', wrong: ['1895', '1905', '1935'] },
    { q: 'The Bombay Stock Exchange is the oldest stock exchange in', ans: 'Asia', wrong: ['Europe', 'Africa', 'North America'] },
    { q: 'The National Stock Exchange was established in', ans: '1992', wrong: ['1985', '1995', '1998'] },
    { q: 'The SENSEX is an index of', ans: 'the Bombay Stock Exchange', wrong: ['the National Stock Exchange', 'the Multi Commodity Exchange', 'the Calcutta Stock Exchange'] },
    { q: 'The NIFTY 50 is an index of', ans: 'the National Stock Exchange', wrong: ['the Bombay Stock Exchange', 'the Calcutta Stock Exchange', 'the Multi Commodity Exchange'] },
    { q: 'The SENSEX comprises how many stocks?', ans: '30', wrong: ['50', '100', '500'] },
    { q: 'The Union Budget is presented on', ans: '1 February', wrong: ['1 March', '15 August', '28 February'] },
    { q: 'The Economic Survey is presented', ans: 'one day before the Union Budget', wrong: ['on the day of the Union Budget', 'one week after the Union Budget', 'in the month of December'] },
    { q: 'What does FDI stand for?', ans: 'Foreign Direct Investment', wrong: ['Foreign Domestic Investment', 'Financial Direct Investment', 'Foreign Direct Income'] },
    { q: 'What does FPI stand for?', ans: 'Foreign Portfolio Investment', wrong: ['Foreign Public Investment', 'Financial Portfolio Income', 'Foreign Private Investment'] },
    { q: 'FDI refers to', ans: 'direct investment in business enterprises by a foreign entity', wrong: ['buying a small portfolio of shares', 'lending money to the government', 'depositing money in banks'] },
    { q: 'India foreign exchange reserves are held by', ans: 'the Reserve Bank of India', wrong: ['the Ministry of Finance', 'SEBI', 'the State Bank of India'] },
    { q: 'Primary deficit is equal to fiscal deficit minus', ans: 'interest payments', wrong: ['tax revenue', 'government borrowings', 'capital expenditure'] },
    { q: 'Disinflation means', ans: 'a fall in the rate of inflation', wrong: ['a rise in the rate of inflation', 'an abrupt fall in prices', 'zero inflation for a year'] },
    { q: 'Repo operations are used by the RBI to', ans: 'inject liquidity into the banking system', wrong: ['withdraw all liquidity from banks', 'print new currency notes', 'set income tax rates'] },
    { q: 'Who is known as the Father of the Indian Constitution?', ans: 'Dr B. R. Ambedkar', wrong: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Sardar Patel'] },
    { q: 'Who is regarded as the Father of the Nation in India?', ans: 'Mahatma Gandhi', wrong: ['Jawaharlal Nehru', 'Subhas Chandra Bose', 'Sardar Patel'] },
    { q: 'Who was the first President of India?', ans: 'Dr Rajendra Prasad', wrong: ['Dr S. Radhakrishnan', 'Zakir Husain', 'V. V. Giri'] },
    { q: 'Who was the first Prime Minister of India?', ans: 'Jawaharlal Nehru', wrong: ['Lal Bahadur Shastri', 'Indira Gandhi', 'Rajendra Prasad'] },
    { q: 'Who is the current President of India?', ans: 'Droupadi Murmu', wrong: ['Ram Nath Kovind', 'Pranab Mukherjee', 'Pratibha Patil'] },
    { q: 'Who was the first woman President of India?', ans: 'Pratibha Patil', wrong: ['Indira Gandhi', 'Sonia Gandhi', 'Droupadi Murmu'] },
    { q: 'Who was the first woman Prime Minister of India?', ans: 'Indira Gandhi', wrong: ['Sonia Gandhi', 'Pratibha Patil', 'Sucheta Kripalani'] },
    { q: 'Who was the first woman Chief Minister of an Indian state?', ans: 'Sucheta Kripalani', wrong: ['Indira Gandhi', 'Mayawati', 'Sarojini Naidu'] },
    { q: 'The national animal of India is the', ans: 'Royal Bengal Tiger', wrong: ['Indian Lion', 'Asian Elephant', 'Indian Peacock'] },
    { q: 'The national bird of India is the', ans: 'Indian peacock', wrong: ['Parrot', 'Pigeon', 'House sparrow'] },
    { q: 'The national flower of India is the', ans: 'Lotus', wrong: ['Rose', 'Jasmine', 'Marigold'] },
    { q: 'The national tree of India is the', ans: 'Banyan tree', wrong: ['Neem tree', 'Mango tree', 'Peepal tree'] },
    { q: 'The national fruit of India is the', ans: 'Mango', wrong: ['Banana', 'Apple', 'Papaya'] },
    { q: 'The national anthem of India is', ans: 'Jana Gana Mana', wrong: ['Vande Mataram', 'Sare Jahan Se Achha', 'Hum Honge Kamyab'] },
    { q: 'The national song of India is', ans: 'Vande Mataram', wrong: ['Jana Gana Mana', 'Sare Jahan Se Achha', 'Ae Mere Watan Ke Logon'] },
    { q: 'The national anthem of India was composed by', ans: 'Rabindranath Tagore', wrong: ['Bankim Chandra Chatterjee', 'Sarojini Naidu', 'Subramania Bharati'] },
    { q: 'Vande Mataram was written by', ans: 'Bankim Chandra Chatterjee', wrong: ['Rabindranath Tagore', 'Sarojini Naidu', 'Ramdhari Singh Dinkar'] },
    { q: 'The national river of India is the', ans: 'Ganga', wrong: ['Yamuna', 'Godavari', 'Brahmaputra'] },
    { q: 'The national aquatic animal of India is the', ans: 'Ganges river dolphin', wrong: ['Blue whale', 'Great white shark', 'Olive ridley turtle'] },
    { q: 'The national reptile of India is the', ans: 'King Cobra', wrong: ['Indian python', 'Mugger crocodile', 'Indian tortoise'] },
    { q: 'The Ashoka Chakra on the Indian flag has', ans: '24 spokes', wrong: ['12 spokes', '20 spokes', '16 spokes'] },
    { q: 'The Constitution of India was adopted on', ans: '26 November 1949', wrong: ['15 August 1947', '26 January 1950', '2 October 1950'] },
    { q: 'The Constitution of India came into force on', ans: '26 January 1950', wrong: ['15 August 1947', '26 November 1949', '2 October 1949'] },
    { q: 'The longest river of India is the', ans: 'Ganga', wrong: ['Godavari', 'Krishna', 'Narmada'] },
    { q: 'The highest mountain peak in India is', ans: 'Kangchenjunga', wrong: ['Mount Everest', 'Nanda Devi', 'Anamudi'] },
    { q: 'The largest state of India by area is', ans: 'Rajasthan', wrong: ['Uttar Pradesh', 'Maharashtra', 'Madhya Pradesh'] },
    { q: 'The largest state of India by population is', ans: 'Uttar Pradesh', wrong: ['Maharashtra', 'Bihar', 'West Bengal'] },
    { q: 'How many states are there in India?', ans: '28', wrong: ['27', '29', '30'] },
    { q: 'How many Union Territories are there in India?', ans: '8', wrong: ['6', '7', '9'] },
    { q: 'The capital of India is', ans: 'New Delhi', wrong: ['Mumbai', 'Kolkata', 'Chandigarh'] },
    { q: 'How many Fundamental Rights are guaranteed by the Indian Constitution?', ans: '6', wrong: ['5', '7', '8'] },
    { q: 'The Right to Life and Personal Liberty is guaranteed under', ans: 'Article 21', wrong: ['Article 14', 'Article 19', 'Article 32'] },
    { q: 'The Right to Constitutional Remedies is guaranteed under', ans: 'Article 32', wrong: ['Article 21', 'Article 14', 'Article 44'] },
    { q: 'The Fundamental Duties were added to the Constitution by', ans: 'the 42nd Amendment Act', wrong: ['the 44th Amendment Act', 'the 73rd Amendment Act', 'the 86th Amendment Act'] },
    { q: 'The Panchayati Raj system got constitutional status through', ans: 'the 73rd Amendment Act', wrong: ['the 42nd Amendment Act', 'the 74th Amendment Act', 'the 44th Amendment Act'] },
    { q: 'The municipality system got constitutional status through', ans: 'the 74th Amendment Act', wrong: ['the 73rd Amendment Act', 'the 42nd Amendment Act', 'the 86th Amendment Act'] },
    { q: 'The Panchayati Raj system in India has how many tiers?', ans: '3', wrong: ['2', '4', '5'] },
    { q: 'Who was the first Indian to go into space?', ans: 'Rakesh Sharma', wrong: ['Kalpana Chawla', 'Vikram Sarabhai', 'A. P. J. Abdul Kalam'] },
    { q: 'Who was the first Indian to win a Nobel Prize?', ans: 'Rabindranath Tagore', wrong: ['C. V. Raman', 'Mother Teresa', 'Amartya Sen'] },
    { q: 'Who was the first woman of Indian origin to go into space?', ans: 'Kalpana Chawla', wrong: ['Sunita Williams', 'Rakesh Sharma', 'Indira Gandhi'] },
    { q: 'Who was the first Governor-General of independent India?', ans: 'Lord Mountbatten', wrong: ['C. Rajagopalachari', 'Warren Hastings', 'Lord Canning'] },
    { q: 'Who was the first Indian to serve as Governor-General of India?', ans: 'C. Rajagopalachari', wrong: ['Lord Mountbatten', 'Dr Rajendra Prasad', 'Sardar Patel'] },
    { q: 'The Taj Mahal in Agra stands on the banks of which river?', ans: 'Yamuna', wrong: ['Ganga', 'Godavari', 'Kaveri'] },
    { q: 'Jog Falls is located on which river?', ans: 'Sharavati', wrong: ['Kaveri', 'Krishna', 'Godavari'] },
    { q: 'The largest coastal lagoon of India is', ans: 'Chilika Lake', wrong: ['Wular Lake', 'Vembanad Lake', 'Dal Lake'] },
    { q: 'The Bharat Ratna is awarded for', ans: 'highest civilian service', wrong: ['highest military gallantry', 'sporting achievements', 'literary works only'] },
    { q: 'The Param Vir Chakra is awarded for', ans: 'highest gallantry in wartime', wrong: ['gallantry in peacetime', 'civilian service', 'sports performance'] },
    { q: 'The three colours of the Indian national flag are', ans: 'saffron, white and green', wrong: ['saffron, red and green', 'orange, white and blue', 'yellow, white and green'] },
    { q: 'The Thar desert is mainly located in', ans: 'Rajasthan', wrong: ['West Bengal', 'Kerala', 'Assam'] },
    { q: 'The Sundarbans mangrove forest is located in', ans: 'West Bengal', wrong: ['Odisha', 'Kerala', 'Goa'] },
    { q: 'Kuchipudi is a classical dance form of which state?', ans: 'Andhra Pradesh', wrong: ['Tamil Nadu', 'Kerala', 'Odisha'] },
    { q: 'Bharatanatyam is a classical dance form of which state?', ans: 'Tamil Nadu', wrong: ['Andhra Pradesh', 'Kerala', 'Karnataka'] },
    { q: 'What does PMJDY stand for?', ans: 'Pradhan Mantri Jan Dhan Yojana', wrong: ['Pradhan Mantri Jan Dhan Bima', 'Pradhan Mantri Jeevan Dhan Yojana', 'Pradhan Mantri Janta Dhan Yojana'] },
    { q: 'The Pradhan Mantri Jan Dhan Yojana mainly aims at', ans: 'financial inclusion', wrong: ['health insurance', 'housing for all', 'farmers welfare'] },
    { q: 'PMJJBY provides a life insurance cover of', ans: 'Rs 2 lakh', wrong: ['Rs 5 lakh', 'Rs 1 lakh', 'Rs 10 lakh'] },
    { q: 'What does PMJJBY stand for?', ans: 'Pradhan Mantri Jeevan Jyoti Bima Yojana', wrong: ['Pradhan Mantri Jeevan Jeevan Yojana', 'Pradhan Mantri Jan Jyoti Bima Yojana', 'Pradhan Mantri Jeevan Bima Yojana'] },
    { q: 'PMSBY provides an accident insurance cover of', ans: 'Rs 2 lakh', wrong: ['Rs 5 lakh', 'Rs 1 lakh', 'Rs 10 lakh'] },
    { q: 'PM-KISAN provides an annual income support of', ans: 'Rs 6,000', wrong: ['Rs 12,000', 'Rs 5,000', 'Rs 10,000'] },
    { q: 'The benefit of PM-KISAN is given to', ans: 'farmers', wrong: ['students', 'senior citizens', 'government employees'] },
    { q: 'Ayushman Bharat provides health cover of', ans: 'Rs 5 lakh per family per year', wrong: ['Rs 1 lakh per family', 'Rs 2 lakh per family', 'Rs 10 lakh per family'] },
    { q: 'MUDRA loans can be availed up to', ans: 'Rs 10 lakh', wrong: ['Rs 5 lakh', 'Rs 25 lakh', 'Rs 1 crore'] },
    { q: 'The three categories of MUDRA loans are', ans: 'Shishu, Kishor and Tarun', wrong: ['Micro, Small and Medium', 'Shishu, Bal and Yuva', 'Small, Medium and Large'] },
    { q: 'The Startup India campaign was launched in', ans: '2016', wrong: ['2014', '2015', '2017'] },
    { q: 'The Digital India campaign was launched in', ans: '2015', wrong: ['2014', '2016', '2013'] },
    { q: 'The Sukanya Samriddhi Yojana is meant for', ans: 'the girl child', wrong: ['the boy child', 'senior citizens', 'landless farmers'] },
    { q: 'A Sukanya Samriddhi account can be opened for a girl child up to the age of', ans: '10 years', wrong: ['5 years', '12 years', '18 years'] },
    { q: 'The Atmanirbhar Bharat package was announced in', ans: '2020', wrong: ['2018', '2019', '2021'] },
    { q: 'The Atal Pension Yojana is mainly for', ans: 'workers in the unorganised sector', wrong: ['government employees', 'school children', 'retired army personnel'] },
    { q: 'The Pradhan Mantri Ujjwala Yojana provides', ans: 'free LPG connections to poor households', wrong: ['free electricity connections', 'free water connections', 'free smartphones'] },
    { q: 'Beti Bachao Beti Padhao mainly focuses on', ans: 'the welfare of the girl child', wrong: ['the education of senior citizens', 'the welfare of farmers', 'rural road construction'] },
    { q: 'Swachh Bharat Abhiyan mainly focuses on', ans: 'cleanliness and sanitation', wrong: ['digital literacy', 'tree plantation', 'women safety'] },
    { q: 'Make in India is mainly aimed at', ans: 'boosting domestic manufacturing', wrong: ['expanding agricultural output', 'promoting tourism', 'importing foreign goods'] },
    { q: 'The Pradhan Mantri Fasal Bima Yojana is', ans: 'a crop insurance scheme', wrong: ['a health insurance scheme', 'a pension scheme', 'a housing scheme'] },
    { q: 'The PM Vishwakarma scheme is meant for', ans: 'artisans and craftspeople', wrong: ['farmers', 'school students', 'government employees'] },
    { q: 'In finance, liquidity means', ans: 'the ease with which an asset can be converted into cash', wrong: ['the total wealth of a person', 'the profit earned by a company', 'the total debt of a firm'] },
    { q: 'Insolvency means', ans: 'the inability to pay debts', wrong: ['excess profit', 'high liquidity', 'rising inflation'] },
    { q: 'Deflation means', ans: 'a sustained fall in the general price level', wrong: ['a sustained rise in prices', 'a fall in unemployment', 'a rise in wages'] },
    { q: 'Disinvestment means', ans: 'the government selling its stake in public enterprises', wrong: ['the government buying new assets', 'printing more currency', 'raising tax rates'] },
    { q: 'Stagflation means', ans: 'inflation combined with economic stagnation', wrong: ['inflation combined with growth', 'deflation combined with growth', 'recession with falling prices'] },
    { q: 'A recession is commonly defined as', ans: 'two consecutive quarters of negative GDP growth', wrong: ['one week of low economic growth', 'a rise in the inflation rate', 'a fall in stock prices'] },
    { q: 'Depreciation of a currency means', ans: 'a fall in its value against another currency', wrong: ['a rise in its value', 'no change in its value', 'an increase in exports'] },
    { q: 'Balance of Trade is the difference between', ans: 'exports and imports of goods', wrong: ['exports and government spending', 'savings and investment', 'receipts and payments of the budget'] },
    { q: 'Balance of Payments records', ans: 'all economic transactions of a country with the rest of the world', wrong: ['only trade in goods', 'only remittances', 'only government borrowings'] },
    { q: 'Demand deposits are mainly held in', ans: 'savings and current accounts', wrong: ['fixed deposits', 'recurring deposits', 'PPF accounts'] },
    { q: 'Time deposits are mainly held in', ans: 'fixed and recurring deposits', wrong: ['savings accounts', 'current accounts', 'cash in hand'] },
    { q: 'What does KYC stand for?', ans: 'Know Your Customer', wrong: ['Keep Your Cash', 'Know Your Capital', 'Keep Your Customer'] },
    { q: 'Bancassurance is a combination of', ans: 'banking and insurance services', wrong: ['banking and stock broking', 'insurance and mutual funds', 'banking and real estate'] },
    { q: 'A credit rating assesses', ans: 'the creditworthiness of a borrower', wrong: ['the market share of a company', 'the number of employees', 'the profit margin'] },
    { q: 'The GDP deflator measures', ans: 'the overall price level of all goods and services', wrong: ['only food prices', 'only export prices', 'stock market prices'] },
    { q: 'The capital market deals in', ans: 'long-term funds', wrong: ['short-term funds', 'daily wage payments', 'foreign remittances'] },
    { q: 'The money market deals in', ans: 'short-term funds', wrong: ['long-term funds', 'real estate', 'gold bullion'] },
    { q: 'SLR is maintained by banks to ensure', ans: 'a minimum holding of liquid assets', wrong: ['higher lending to customers', 'more currency printing', 'higher tax collection'] },
    { q: 'Reserve Money (M0) is issued by', ans: 'the Reserve Bank of India', wrong: ['the State Bank of India', 'the Government of India', 'commercial banks'] },
    { q: 'Money withdrawn through a debit card is taken from', ans: 'the savings account of the customer', wrong: ['a credit limit given by the bank', 'a loan sanctioned by the bank', 'the bank reserves'] },
    { q: 'An increase in the repo rate generally makes', ans: 'borrowing by banks costlier', wrong: ['borrowing by banks cheaper', 'inflation rise instantly', 'exports rise automatically'] }
  ]
};
