module.exports = {
  SPELLING: [
    { word: 'ACCOMMODATION', wrong: ['ACCOMODATION', 'ACCOMMODATON', 'ACOMODATION'] },
    { word: 'COMMITTEE', wrong: ['COMMITE', 'COMMITEE', 'COMITEE'] },
    { word: 'EMBARRASS', wrong: ['EMBARASS', 'EMBARRAS', 'EMBARAS'] },
    { word: 'OCCURRENCE', wrong: ['OCCURENCE', 'OCURRENCE', 'OCCURANCE'] },
    { word: 'SEPARATE', wrong: ['SEPERATE', 'SEPARETE', 'SEAPRATE'] },
    { word: 'NECESSARY', wrong: ['NECESARY', 'NECESSERY', 'NECESARRY'] },
    { word: 'VACUUM', wrong: ['VACUM', 'VACCUM', 'VACCUUM'] },
    { word: 'PRIVILEGE', wrong: ['PRIVILEDGE', 'PRIVELEDGE', 'PRIVELEGE'] },
    { word: 'GUARANTEE', wrong: ['GUARENTEE', 'GUARANTE', 'GURANTEE'] },
    { word: 'LIAISON', wrong: ['LIAISSON', 'LIASON', 'LIAIZON'] },
    { word: 'QUESTIONNAIRE', wrong: ['QUESTIONAIRE', 'QUESTIONNARIE', 'QUESTIONNAIR'] },
    { word: 'MILLENNIUM', wrong: ['MILLENIUM', 'MILENNIUM', 'MILLENNIM'] },
    { word: 'OCCASION', wrong: ['OCASION', 'OCCASIAN', 'OCCASSION'] },
    { word: 'DEFINITELY', wrong: ['DEFINIETLY', 'DEFINAITELY', 'DEFINTELY'] },
    { word: 'EXAGGERATE', wrong: ['EXAGERATE', 'EXAGERRATE', 'EXAGGRATE'] },
    { word: 'PARALLEL', wrong: ['PARALEL', 'PARALELL', 'PARALLELL'] },
    { word: 'OCCUPIED', wrong: ['OCUPIED', 'OCCUPPIED', 'OCCUPID'] },
    { word: 'RECEIPT', wrong: ['RECIEPT', 'RECEIT', 'RECIPT'] },
    { word: 'WEIRD', wrong: ['WIERD', 'WEARD', 'WERID'] },
    { word: 'CONSENSUS', wrong: ['CONSENCUS', 'CONCENSUS', 'CONSENUS'] },
    { word: 'RHINOCEROS', wrong: ['RHINOCEROUS', 'RHINOCERAS', 'RHINOCERUS'] },
    { word: 'PSYCHOLOGY', wrong: ['PSYCOLOGY', 'SICOLOGY', 'PSYCHOLGY'] },
    { word: 'MISSPELL', wrong: ['MISPELL', 'MISPEL', 'MISPLE'] },
    { word: 'NOTORIOUS', wrong: ['NOTORIUS', 'NATORIOUS', 'NOTOROUS'] },
    { word: 'INNOCENT', wrong: ['INOCENT', 'INNOCANT', 'INOSENT'] },
    { word: 'IMMEDIATELY', wrong: ['IMEDIATELY', 'IMMEDIATLY', 'IMMEDEATELY'] },
    { word: 'POSSESSION', wrong: ['POSESSION', 'POSSESION', 'POSSESIN'] },
    { word: 'ACQUAINTANCE', wrong: ['ACQUAINTENCE', 'AQUAINTANCE', 'ACQUAINTAINCE'] },
    { word: 'EXHILARATE', wrong: ['EXHILERATE', 'EXHILIRATE', 'EXHILARETE'] },
    { word: 'UNNECESSARY', wrong: ['UNECESSARY', 'UNNECESSERY', 'UNNECCESARY'] },
    { word: 'DISAPPOINT', wrong: ['DISAPOINT', 'DISSAPPOINT', 'DISAPPIONT'] },
    { word: 'OCCASIONALLY', wrong: ['OCASIONALLY', 'OCCASSIONALLY', 'OCCASIONALY'] },
    { word: 'BUREAUCRACY', wrong: ['BUREACRACY', 'BUREUCRACY', 'BEAUROCRACY'] },
    { word: 'SUPERSEDE', wrong: ['SUPERCEED', 'SUPERSEED', 'SUPERCEDE'] },
    { word: 'PERSISTENT', wrong: ['PERSISTANT', 'PERSISTINT', 'PERSESTENT'] },
    { word: 'RESISTANCE', wrong: ['RESISTENCE', 'RESISTENSE', 'RESISTANSE'] },
    { word: 'ASSASSIN', wrong: ['ASSASIN', 'ASSASINN', 'ASSASSSIN'] },
    { word: 'COMMEMORATE', wrong: ['COMEMORATE', 'COMMEMORAT', 'COMMEMARATE'] },
    { word: 'INTELLIGENT', wrong: ['INTELIGENT', 'INTELLIGANT', 'INTELEGENT'] },
    { word: 'PHILOSOPHY', wrong: ['PHYLOSOPHY', 'PHILOSOFY', 'PHILOSPHY'] },
    { word: 'TOMORROW', wrong: ['TOMOROW', 'TOMMORROW', 'TOMORO'] },
    { word: 'RESTAURANT', wrong: ['RESTAURENT', 'RESTUARANT', 'RESTURANT'] },
    { word: 'RECOMMEND', wrong: ['RECOMEND', 'RECOMMEN', 'RECOMAND'] },
    { word: 'OPPORTUNITY', wrong: ['OPPERTUNITY', 'OPPURTUNITY', 'OPPORTUNITI'] },
    { word: 'MAINTENANCE', wrong: ['MAINTENENCE', 'MAINTAINENCE', 'MAINTANENCE'] },
    { word: 'PERSEVERANCE', wrong: ['PERSEVERENCE', 'PERSERVERANCE', 'PERSEVARANCE'] },
    { word: 'INCONVENIENCE', wrong: ['INCONVIENENCE', 'INCONVENIANCE', 'INCONVENENCE'] },
    { word: 'PRONUNCIATION', wrong: ['PRONOUNCIATION', 'PROUNCIATION', 'PRONUNCATION'] },
    { word: 'ARGUMENT', wrong: ['ARGUEMENT', 'ARGUMANT', 'ARGEMENT'] },
    { word: 'ENVIRONMENT', wrong: ['ENVIROMENT', 'ENVIORNMENT', 'ENVIRNMENT'] },
    { word: 'GOVERNMENT', wrong: ['GOVERMENT', 'GOVERNMANT', 'GOVERMANT'] },
    { word: 'HUMOROUS', wrong: ['HUMEROUS', 'HUMORUS', 'HUMOURUS'] },
    { word: 'RHYTHM', wrong: ['RHYTHEM', 'RITHYM', 'RHYTHIM'] },
    { word: 'AUTHENTIC', wrong: ['AUTHENTICK', 'AUTHENTIK', 'AUTHANTIC'] },
    { word: 'BOOKKEEPER', wrong: ['BOOKKEPER', 'BOOKEEPER', 'BOOKEKEEPER'] },
    { word: 'CEMETERY', wrong: ['CEMETARY', 'CEMETEREY', 'CEMETRY'] },
    { word: 'CONFIDENTIAL', wrong: ['CONFIDENCIAL', 'CONFIDANTIAL', 'CONFIDENCTIAL'] },
    { word: 'FORTUNATELY', wrong: ['FORTUNETLY', 'FORTUNATLEY', 'FORTUNATLLY'] },
    { word: 'GRAMMAR', wrong: ['GRAMMER', 'GRAMAR', 'GRAMER'] },
    { word: 'INDEPENDENT', wrong: ['INDEPENDANT', 'INDEPENDANTE', 'INDEPENDEND'] },
    { word: 'HAPPINESS', wrong: ['HAPINESS', 'HAPPINES', 'HAPPIINESS'] },
    { word: 'INTELLECTUAL', wrong: ['INTELECTUAL', 'INTELLECTUALL', 'INTELEKTUAL'] },
    { word: 'MARRIAGE', wrong: ['MARRIEGE', 'MARIAGE', 'MARIGE'] },
    { word: 'NEIGHBOUR', wrong: ['NEIGHBOR', 'NEIGHBOURE', 'NEIGBOUR'] },
    { word: 'NOTICEABLE', wrong: ['NOTICABLE', 'NOTICEABEL', 'NOTICEBLE'] },
    { word: 'PARLIAMENT', wrong: ['PARLIMENT', 'PARLIAMENTE', 'PARLIMANT'] },
    { word: 'PERPENDICULAR', wrong: ['PERPENDICULER', 'PERPENDICULR', 'PERPINDICULAR'] },
    { word: 'PRESENTATION', wrong: ['PRESENTAION', 'PRESENTATON', 'PRESANTATION'] },
    { word: 'PROCEDURE', wrong: ['PROCEEDURE', 'PROCIDURE', 'PROCEDER'] },
    { word: 'PURSUE', wrong: ['PERSUE', 'PURUSE', 'PURSU'] },
    { word: 'RARELY', wrong: ['RARLEY', 'RARILY', 'RAERELY'] },
    { word: 'REFERENCE', wrong: ['REFERANCE', 'REFERENSE', 'REFRENCE'] },
    { word: 'REMEMBRANCE', wrong: ['REMEMBERANCE', 'REMEBRANCE', 'REMEMBRENCE'] },
    { word: 'SCHOLARSHIP', wrong: ['SCHOLORSHIP', 'SCHOLERSHIP', 'SCHOLLARSHIP'] },
    { word: 'SURPRISE', wrong: ['SURPRIZE', 'SUPRISE', 'SURPPRISE'] },
    { word: 'THRESHOLD', wrong: ['THREHOLD', 'THRESHHOLD', 'THRESHOLDE'] },
    { word: 'TRAFFIC', wrong: ['TRAFIC', 'TRAAFIC', 'TRAFFIK'] },
    { word: 'UNIQUE', wrong: ['UNIQUUE', 'UNIEQUE', 'UNIQE'] },
    { word: 'VISIBLE', wrong: ['VISABLE', 'VISIBEL', 'VISIBBLE'] },
    { word: 'WRITTEN', wrong: ['WRITEN', 'WRITTIN', 'WRIITEN'] },
    { word: 'ZEALOUS', wrong: ['ZELOUS', 'ZEALUOS', 'ZEALOS'] },
    { word: 'ABANDONED', wrong: ['ABANDANDONED', 'ABONDONED', 'ABANDONNED'] },
    { word: 'ACHIEVE', wrong: ['ACHIVE', 'ACHEIVE', 'ACHIEV'] },
    { word: 'ACKNOWLEDGE', wrong: ['ACKNOWLEGE', 'AKNOWLEDGE', 'ACKNOWLADGE'] },
    { word: 'ACQUIRE', wrong: ['ACQIRE', 'AQUIRE', 'ACQUIER'] },
    { word: 'ADDRESS', wrong: ['ADRESS', 'ADDREES', 'ADRES'] },
    { word: 'ADVERTISEMENT', wrong: ['ADVERTISMENT', 'ADVERTIZEMENT', 'ADVERTAISEMENT'] },
    { word: 'AGGRAVATE', wrong: ['AGRRAVATE', 'AGGRAVETE', 'AGGRAVAT'] },
    { word: 'AGGRESSION', wrong: ['AGRESSION', 'AGGRESION', 'AGGREESSION'] },
    { word: 'ALLEGIANCE', wrong: ['ALEGIANCE', 'ALLEGENCE', 'ALLEGIENCE'] },
    { word: 'AMATEUR', wrong: ['AMATURE', 'AMETEUR', 'AMATUER'] },
    { word: 'ANCIENT', wrong: ['ANCIANT', 'ANSIENT', 'ANSCIENT'] },
    { word: 'ANNIVERSARY', wrong: ['ANNIVERSERY', 'ANNIVERARY', 'ANIVERSARY'] },
    { word: 'APPARENTLY', wrong: ['APPARANTLY', 'APPARENTALY', 'APARENTLY'] },
    { word: 'APPRECIATE', wrong: ['APPRECATE', 'APPRECIET', 'APRECIATE'] },
    { word: 'ARGUMENT', wrong: ['ARGUEMENT', 'ARGUMENTT', 'ARGUMANT'] },
    { word: 'ASSASSINATION', wrong: ['ASSASINATION', 'ASSASSINATON', 'ASSASINNATION'] },
    { word: 'ATTORNEY', wrong: ['ATTORNY', 'ATTURNEE', 'ATTORENY'] },
    { word: 'AUTHENTIC', wrong: ['AUTENTIC', 'AUTHENTIK', 'AUTHANTIC'] },
    { word: 'AUTHORITIES', wrong: ['AUTHORITES', 'AUTHORETIES', 'AUTHARITIES'] },
    { word: 'BARGAIN', wrong: ['BARGIN', 'BARGEIN', 'BARGAANE'] },
    { word: 'BEAUTIFUL', wrong: ['BEAUTIFULL', 'BEAUTIFUUL', 'BUETIFUL'] },
    { word: 'BEGINNING', wrong: ['BEGINING', 'BEGINNINNG', 'BEAGINNING'] },
    { word: 'BELIEVE', wrong: ['BELIVE', 'BELEIVE', 'BELIEV'] },
    { word: 'BENEFIT', wrong: ['BENIFIT', 'BENEFITT', 'BENAFIT'] },
    { word: 'BOUNDARY', wrong: ['BOUNDERY', 'BOUDARY', 'BOOUNDARY'] },
    { word: 'BRILLIANT', wrong: ['BRILLIENT', 'BRILLANT', 'BILLIANT'] },
    { word: 'BUSINESS', wrong: ['BUSSINESS', 'BUSSINES', 'BUISNESS'] },
    { word: 'CALENDAR', wrong: ['CALANDER', 'CALANDR', 'CALENDOR'] },
    { word: 'CANDIDATE', wrong: ['CANDIDET', 'CANDADATE', 'CANIDATE'] },
    { word: 'CATASTROPHE', wrong: ['CATASTROPHY', 'CATASTROFE', 'CATASSTROPHE'] },
    { word: 'CEMETERY', wrong: ['CEMETARY', 'CEMITERY', 'CEMATERY'] },
    { word: 'CHALLENGE', wrong: ['CHALLANGE', 'CHALLENG', 'CHELLENGE'] },
    { word: 'CHAMPIONSHIP', wrong: ['CHAMPIONSHP', 'CHAMPINOSHIP', 'CHAMPEONSHIP'] },
    { word: 'CHARACTER', wrong: ['CHARECTER', 'CHARACTERR', 'CARACTER'] },
    { word: 'CITIZEN', wrong: ['CITISEN', 'CITEZEN', 'CITIZENN'] },
    { word: 'COLLECTION', wrong: ['COLECTION', 'COLLECTON', 'COLLECTIN'] },
    { word: 'COMMERCIAL', wrong: ['COMERCIAL', 'COMMERCIL', 'COMMERIAL'] },
    { word: 'COMPETITION', wrong: ['COMPETITON', 'COMPETISION', 'COMPITITION'] },
    { word: 'CONCENTRATION', wrong: ['CONCENTARTION', 'CONCENTRATON', 'CONCENTRAION'] },
    { word: 'CONSCIOUS', wrong: ['CONCIOUS', 'CONSCIOUSE', 'CONSIOUS'] }
  ],
  SYNONYMS: [
    { word: 'ABANDON', ans: 'FORSAKE', wrong: ['KEEP', 'RETAIN', 'HOLD'] },
    { word: 'ABASE', ans: 'HUMILIATE', wrong: ['EXALT', 'RAISE', 'PRAISE'] },
    { word: 'ABHOR', ans: 'DETEST', wrong: ['LOVE', 'ADMIRE', 'CHERISH'] },
    { word: 'ABRIDGE', ans: 'SHORTEN', wrong: ['LENGTHEN', 'EXTEND', 'EXPAND'] },
    { word: 'ABSOLVE', ans: 'EXONERATE', wrong: ['BLAME', 'ACCUSE', 'CHARGE'] },
    { word: 'ABSTAIN', ans: 'REFRAIN', wrong: ['INDULGE', 'PARTAKE', 'PARTICIPATE'] },
    { word: 'ACCELERATE', ans: 'HASTEN', wrong: ['DELAY', 'RETARD', 'SLOW'] },
    { word: 'ACUMEN', ans: 'SHREWDNESS', wrong: ['DULLNESS', 'STUPIDITY', 'IGNORANCE'] },
    { word: 'ADMONISH', ans: 'REPRIMAND', wrong: ['APPLAUD', 'PRAISE', 'COMMEND'] },
    { word: 'ADVERSITY', ans: 'MISFORTUNE', wrong: ['PROSPERITY', 'SUCCESS', 'GOODFORTUNE'] },
    { word: 'AFFABLE', ans: 'FRIENDLY', wrong: ['HOSTILE', 'RUDE', 'UNFRIENDLY'] },
    { word: 'AGHAST', ans: 'HORRIFIED', wrong: ['CALM', 'SERENE', 'UNFAZED'] },
    { word: 'ALACRITY', ans: 'EAGERNESS', wrong: ['RELUCTANCE', 'HESITATION', 'SLOWNESS'] },
    { word: 'ALLEVIATE', ans: 'RELIEVE', wrong: ['AGGRAVATE', 'WORSEN', 'INTENSIFY'] },
    { word: 'AMICABLE', ans: 'FRIENDLY', wrong: ['HOSTILE', 'UNFRIENDLY', 'ANTAGONISTIC'] },
    { word: 'ANIMOSITY', ans: 'HOSTILITY', wrong: ['FRIENDSHIP', 'GOODWILL', 'AFFECTION'] },
    { word: 'ANTIDOTE', ans: 'REMEDY', wrong: ['POISON', 'VENOM', 'TOXIN'] },
    { word: 'APATHY', ans: 'INDIFFERENCE', wrong: ['ENTHUSIASM', 'PASSION', 'ZEAL'] },
    { word: 'ARDENT', ans: 'PASSIONATE', wrong: ['APATHETIC', 'INDIFFERENT', 'COLD'] },
    { word: 'ARROGANT', ans: 'HAUGHTY', wrong: ['HUMBLE', 'MODEST', 'MEEK'] },
    { word: 'ASTUTE', ans: 'SHREWD', wrong: ['FOOLISH', 'STUPID', 'NAIVE'] },
    { word: 'AUGMENT', ans: 'INCREASE', wrong: ['DECREASE', 'REDUCE', 'DIMINISH'] },
    { word: 'AUTONOMY', ans: 'INDEPENDENCE', wrong: ['DEPENDENCE', 'SUBORDINATION', 'SLAVERY'] },
    { word: 'BALEFUL', ans: 'HARMFUL', wrong: ['BENEFICIAL', 'HARMLESS', 'SAFE'] },
    { word: 'BANISH', ans: 'EXILE', wrong: ['WELCOME', 'ADMIT', 'ACCEPT'] },
    { word: 'BARTER', ans: 'TRADE', wrong: ['GIFT', 'DONATE', 'BESTOW'] },
    { word: 'BELLIGERENT', ans: 'AGGRESSIVE', wrong: ['PEACEFUL', 'GENTLE', 'PACIFIC'] },
    { word: 'BENEVOLENT', ans: 'KIND', wrong: ['CRUEL', 'MALEVOLENT', 'HARSH'] },
    { word: 'BEWILDER', ans: 'CONFUSE', wrong: ['CLARIFY', 'ENLIGHTEN', 'EXPLAIN'] },
    { word: 'BLAND', ans: 'INSIPID', wrong: ['SPICY', 'TANGY', 'FLAVORFUL'] },
    { word: 'BLEAK', ans: 'DESOLATE', wrong: ['CHEERFUL', 'BRIGHT', 'PROMISING'] },
    { word: 'BRAVE', ans: 'COURAGEOUS', wrong: ['COWARDLY', 'FEARFUL', 'TIMID'] },
    { word: 'BRUTAL', ans: 'CRUEL', wrong: ['GENTLE', 'KIND', 'MERCIFUL'] },
    { word: 'BURDEN', ans: 'ONUS', wrong: ['RELIEF', 'BOON', 'BLESSING'] },
    { word: 'CALAMITY', ans: 'DISASTER', wrong: ['BLESSING', 'BOON', 'MIRACLE'] },
    { word: 'CALLOW', ans: 'IMMATURE', wrong: ['MATURE', 'EXPERIENCED', 'SOPHISTICATED'] },
    { word: 'CAPTIVATE', ans: 'ENCHANT', wrong: ['REPEL', 'DISGUST', 'BORE'] },
    { word: 'CATASTROPHE', ans: 'CALAMITY', wrong: ['SUCCESS', 'BLESSING', 'FORTUNE'] },
    { word: 'CAUTIOUS', ans: 'WARY', wrong: ['RECKLESS', 'CARELESS', 'RASH'] },
    { word: 'CELESTIAL', ans: 'HEAVENLY', wrong: ['EARTHLY', 'MUNDANE', 'TERRESTRIAL'] },
    { word: 'CESSATION', ans: 'TERMINATION', wrong: ['BEGINNING', 'START', 'ONSET'] },
    { word: 'CHASTISE', ans: 'SCOLD', wrong: ['PRAISE', 'COMMEND', 'LAUD'] },
    { word: 'CIRCUITOUS', ans: 'ROUNDABOUT', wrong: ['DIRECT', 'STRAIGHT', 'SHORT'] },
    { word: 'COERCION', ans: 'FORCE', wrong: ['PERSUASION', 'CHOICE', 'FREEDOM'] },
    { word: 'COGNIZANT', ans: 'AWARE', wrong: ['IGNORANT', 'OBLIVIOUS', 'UNAWARE'] },
    { word: 'COMPASSION', ans: 'SYMPATHY', wrong: ['CRUELTY', 'INDIFFERENCE', 'COLDNESS'] },
    { word: 'COMPLACENT', ans: 'SMUG', wrong: ['DISSATISFIED', 'UNEASY', 'WORRIED'] },
    { word: 'CONCILIATE', ans: 'APPEASE', wrong: ['PROVOKE', 'IRRITATE', 'ANGER'] },
    { word: 'CONCISE', ans: 'BRIEF', wrong: ['LONG', 'WORDY', 'PROLONGED'] },
    { word: 'CONDEMN', ans: 'CENSURE', wrong: ['PRAISE', 'APPLAUD', 'COMMEND'] },
    { word: 'CONGEAL', ans: 'SOLIDIFY', wrong: ['MELT', 'LIQUEFY', 'DISSOLVE'] },
    { word: 'CONJECTURE', ans: 'GUESS', wrong: ['FACT', 'CERTAINTY', 'TRUTH'] },
    { word: 'CONSEQUENCE', ans: 'RESULT', wrong: ['CAUSE', 'ORIGIN', 'SOURCE'] },
    { word: 'CONTENTIOUS', ans: 'QUARRELSOME', wrong: ['PEACEABLE', 'AGREEABLE', 'AMIABLE'] },
    { word: 'CONTRITE', ans: 'REMORSEFUL', wrong: ['UNREPENTANT', 'DEFIANT', 'ARROGANT'] },
    { word: 'CORROBORATE', ans: 'CONFIRM', wrong: ['DISPROVE', 'CONTRADICT', 'DENY'] },
    { word: 'CREDIBLE', ans: 'BELIEVABLE', wrong: ['INCREDIBLE', 'UNLIKELY', 'DUBIOUS'] },
    { word: 'CURSORY', ans: 'SUPERFICIAL', wrong: ['THOROUGH', 'DETAILED', 'EXHAUSTIVE'] },
    { word: 'DEARTH', ans: 'SCARCITY', wrong: ['PLENTY', 'ABUNDANCE', 'SURPLUS'] },
    { word: 'DECADENT', ans: 'CORRUPT', wrong: ['MORAL', 'VIRTUOUS', 'PURE'] },
    { word: 'DECEPTIVE', ans: 'MISLEADING', wrong: ['HONEST', 'TRUTHFUL', 'STRAIGHTFORWARD'] },
    { word: 'DEDUCE', ans: 'INFER', wrong: ['MISUNDERSTAND', 'MISTAKE', 'CONFUSE'] },
    { word: 'DEFER', ans: 'POSTPONE', wrong: ['EXPEDITE', 'HASTEN', 'ADVANCE'] },
    { word: 'DEFIANT', ans: 'REBELLIOUS', wrong: ['OBEDIENT', 'SUBMISSIVE', 'COMPLIANT'] },
    { word: 'DEJECTED', ans: 'DOWNCAST', wrong: ['CHEERFUL', 'HOPEFUL', 'OPTIMISTIC'] },
    { word: 'DELETERIOUS', ans: 'HARMFUL', wrong: ['BENEFICIAL', 'HEALTHFUL', 'WHOLESOME'] },
    { word: 'DEMURE', ans: 'MODEST', wrong: ['BOLD', 'SHAMELESS', 'IMMODEST'] },
    { word: 'DENOUNCE', ans: 'CONDEMN', wrong: ['PRAISE', 'ENDORSE', 'SUPPORT'] },
    { word: 'DEPLETE', ans: 'EXHAUST', wrong: ['REVITALIZE', 'RENEW', 'REPLENISH'] },
    { word: 'DEPRAVED', ans: 'WICKED', wrong: ['VIRTUOUS', 'RIGHTEOUS', 'MORAL'] },
    { word: 'DERIDE', ans: 'MOCK', wrong: ['RESPECT', 'HONOR', 'ADMIRE'] },
    { word: 'DESPONDENT', ans: 'DEJECTED', wrong: ['OPTIMISTIC', 'CHEERFUL', 'HOPEFUL'] },
    { word: 'DETEST', ans: 'ABHOR', wrong: ['LOVE', 'ADORE', 'CHERISH'] },
    { word: 'DEVOID', ans: 'BARREN', wrong: ['FILLED', 'ABUNDANT', 'FERTILE'] },
    { word: 'DILIGENT', ans: 'INDUSTRIOUS', wrong: ['LAZY', 'IDLE', 'INDOLENT'] },
    { word: 'DIMINISH', ans: 'DECREASE', wrong: ['INCREASE', 'EXPAND', 'ENLARGE'] },
    { word: 'DIRE', ans: 'DREADFUL', wrong: ['WONDERFUL', 'SPLENDID', 'DELIGHTFUL'] },
    { word: 'DISCERN', ans: 'PERCEIVE', wrong: ['OVERLOOK', 'MISS', 'IGNORE'] },
    { word: 'DISPEL', ans: 'DISPERSE', wrong: ['GATHER', 'COLLECT', 'CONCENTRATE'] },
    { word: 'DISSENT', ans: 'DISAGREE', wrong: ['AGREE', 'CONCUR', 'ACCEDE'] },
    { word: 'DOGMATIC', ans: 'OPINIONATED', wrong: ['FLEXIBLE', 'OPENMINDED', 'TOLERANT'] },
    { word: 'DUBIOUS', ans: 'DOUBTFUL', wrong: ['CERTAIN', 'CONFIDENT', 'SURE'] },
    { word: 'DURABLE', ans: 'LASTING', wrong: ['FRAGILE', 'TEMPORARY', 'FLEETING'] },
    { word: 'EBULLIENT', ans: 'ENTHUSIASTIC', wrong: ['DEPRESSED', 'GLOOMY', 'LETHARGIC'] },
    { word: 'ECCENTRIC', ans: 'ODD', wrong: ['NORMAL', 'CONVENTIONAL', 'TYPICAL'] },
    { word: 'EFFICACIOUS', ans: 'EFFECTIVE', wrong: ['INEFFECTIVE', 'FUTILE', 'USELESS'] },
    { word: 'ELATED', ans: 'OVERJOYED', wrong: ['DEPRESSED', 'SAD', 'GLUM'] },
    { word: 'ELUCIDATE', ans: 'CLARIFY', wrong: ['CONFUSE', 'OBSCURE', 'MYSTIFY'] },
    { word: 'EMACIATED', ans: 'GAUNT', wrong: ['PLUMP', 'STOUT', 'HEALTHY'] },
    { word: 'EMINENT', ans: 'RENOWNED', wrong: ['OBSCURE', 'UNKNOWN', 'FAMELESS'] },
    { word: 'ENERVATE', ans: 'WEAKEN', wrong: ['STRENGTHEN', 'INVIGORATE', 'ENERGIZE'] },
    { word: 'ENIGMATIC', ans: 'MYSTERIOUS', wrong: ['CLEAR', 'OBVIOUS', 'PLAIN'] },
    { word: 'ENORMOUS', ans: 'HUGE', wrong: ['TINY', 'SMALL', 'MINUTE'] },
    { word: 'ENTICE', ans: 'TEMPT', wrong: ['DETER', 'DISCOURAGE', 'REPEL'] },
    { word: 'EPHEMERAL', ans: 'FLEETING', wrong: ['ETERNAL', 'PERMANENT', 'LASTING'] },
    { word: 'EQUANIMITY', ans: 'COMPOSURE', wrong: ['AGITATION', 'ANXIETY', 'NERVOUSNESS'] },
    { word: 'ERUDITE', ans: 'LEARNED', wrong: ['IGNORANT', 'UNEDUCATED', 'ILLITERATE'] },
    { word: 'ESSENCE', ans: 'SUBSTANCE', wrong: ['EXTERIOR', 'SURFACE', 'OUTSIDE'] },
    { word: 'EXONERATE', ans: 'ACQUIT', wrong: ['CONVICT', 'BLAME', 'INCULPATE'] },
    { word: 'EXUBERANT', ans: 'LIVELY', wrong: ['LETHARGIC', 'APATHETIC', 'LISTLESS'] },
    { word: 'FALLACIOUS', ans: 'UNTRUE', wrong: ['TRUE', 'CORRECT', 'ACCURATE'] },
    { word: 'FEASIBLE', ans: 'PRACTICABLE', wrong: ['IMPOSSIBLE', 'IMPRACTICAL', 'UNFEASIBLE'] },
    { word: 'FICKLE', ans: 'CAPRICIOUS', wrong: ['STEADFAST', 'STABLE', 'CONSTANT'] },
    { word: 'FLOURISH', ans: 'THRIVE', wrong: ['WITHER', 'DECLINE', 'PERISH'] },
    { word: 'FRAGILE', ans: 'DELICATE', wrong: ['STRONG', 'STURDY', 'ROBUST'] },
    { word: 'FURTIVE', ans: 'STEALTHY', wrong: ['OPEN', 'OVERT', 'BLATANT'] },
    { word: 'GENUINE', ans: 'AUTHENTIC', wrong: ['FAKE', 'FALSE', 'BOGUS'] },
    { word: 'GHASTLY', ans: 'HORRIBLE', wrong: ['PLEASANT', 'DELIGHTFUL', 'LOVELY'] },
    { word: 'GLUTTONOUS', ans: 'GREEDY', wrong: ['MODERATE', 'TEMPERATE', 'SPARING'] },
    { word: 'GRUESOME', ans: 'HORRIBLE', wrong: ['PLEASANT', 'ATTRACTIVE', 'CHARMING'] },
    { word: 'HAPHAZARD', ans: 'RANDOM', wrong: ['SYSTEMATIC', 'ORDERLY', 'METHODICAL'] },
    { word: 'HARMONY', ans: 'ACCORD', wrong: ['CONFLICT', 'DISCORD', 'DISPUTE'] },
    { word: 'HAZARD', ans: 'DANGER', wrong: ['SAFETY', 'SECURITY', 'PROTECTION'] },
    { word: 'HEEDLESS', ans: 'CARELESS', wrong: ['CAREFUL', 'CAUTIOUS', 'ATTENTIVE'] },
    { word: 'HOSTILE', ans: 'UNFRIENDLY', wrong: ['FRIENDLY', 'CORDIAL', 'AMIABLE'] },
    { word: 'HUMBLE', ans: 'MODEST', wrong: ['PROUD', 'ARROGANT', 'CONCEITED'] },
    { word: 'IMPEDE', ans: 'HINDER', wrong: ['FACILITATE', 'ASSIST', 'AID'] },
    { word: 'IMPLACABLE', ans: 'UNFORGIVING', wrong: ['FORGIVING', 'LENIENT', 'MERCIFUL'] },
    { word: 'IMPROMPTU', ans: 'SPONTANEOUS', wrong: ['PLANNED', 'REHEARSED', 'PREARRANGED'] },
    { word: 'INANE', ans: 'SILLY', wrong: ['SERIOUS', 'SENSIBLE', 'WISE'] },
    { word: 'INCESSANT', ans: 'CONTINUAL', wrong: ['INTERMITTENT', 'OCCASIONAL', 'SPORADIC'] },
    { word: 'INCLINATION', ans: 'LEANING', wrong: ['DISINCLINATION', 'AVERSION', 'RELUCTANCE'] },
    { word: 'INDIGENT', ans: 'POOR', wrong: ['WEALTHY', 'RICH', 'AFFLUENT'] },
    { word: 'INDUSTRIOUS', ans: 'HARDWORKING', wrong: ['LAZY', 'IDLE', 'INDOLENT'] },
    { word: 'INFALLIBLE', ans: 'UNERRING', wrong: ['FALLIBLE', 'ERRING', 'FAULTY'] },
    { word: 'INGENIOUS', ans: 'CLEVER', wrong: ['STUPID', 'DULL', 'UNIMAGINATIVE'] },
    { word: 'INHERENT', ans: 'INTRINSIC', wrong: ['EXTERNAL', 'EXTRANEOUS', 'FOREIGN'] },
    { word: 'INNOCUOUS', ans: 'HARMLESS', wrong: ['HARMFUL', 'NOXIOUS', 'DANGEROUS'] },
    { word: 'INSULAR', ans: 'NARROWMINDED', wrong: ['BROADMINDED', 'COSMOPOLITAN', 'OPEN'] },
    { word: 'INTREPID', ans: 'FEARLESS', wrong: ['TIMID', 'FEARFUL', 'COWARDLY'] },
    { word: 'JUBILANT', ans: 'TRIUMPHANT', wrong: ['DESPONDENT', 'GLOOMY', 'SAD'] },
    { word: 'LAMENT', ans: 'MOURN', wrong: ['REJOICE', 'CELEBRATE', 'CHEER'] },
    { word: 'LETHARGIC', ans: 'SLUGGISH', wrong: ['ENERGETIC', 'ACTIVE', 'LIVELY'] },
    { word: 'LUGUBRIOUS', ans: 'MOURNFUL', wrong: ['JOYFUL', 'MERRY', 'CHEERFUL'] },
    { word: 'MALICIOUS', ans: 'SPITEFUL', wrong: ['KIND', 'BENEVOLENT', 'GOOD'] },
    { word: 'MARVEL', ans: 'WONDER', wrong: ['BORE', 'DISGUST', 'OFFEND'] },
    { word: 'MEAGER', ans: 'SCANTY', wrong: ['PLENTIFUL', 'ABUNDANT', 'AMPLE'] },
    { word: 'MERCENARY', ans: 'GREEDY', wrong: ['GENEROUS', 'ALTRUISTIC', 'SELFLESS'] },
    { word: 'METICULOUS', ans: 'CAREFUL', wrong: ['CARELESS', 'SLOPPY', 'NEGLIGENT'] },
    { word: 'MIRACULOUS', ans: 'WONDROUS', wrong: ['ORDINARY', 'COMMON', 'USUAL'] },
    { word: 'MOLLIFY', ans: 'PACIFY', wrong: ['ANGER', 'ENRAGE', 'AGITATE'] },
    { word: 'MUNDANE', ans: 'ORDINARY', wrong: ['EXTRAORDINARY', 'EXOTIC', 'UNUSUAL'] },
    { word: 'NOVICE', ans: 'BEGINNER', wrong: ['EXPERT', 'VETERAN', 'MASTER'] },
    { word: 'NUISANCE', ans: 'BOTHER', wrong: ['PLEASURE', 'DELIGHT', 'JOY'] },
    { word: 'OBSCURE', ans: 'UNCLEAR', wrong: ['CLEAR', 'EVIDENT', 'OBVIOUS'] },
    { word: 'OBSTINATE', ans: 'STUBBORN', wrong: ['OBEDIENT', 'COMPLIANT', 'YIELDING'] },
    { word: 'OMINOUS', ans: 'THREATENING', wrong: ['PROMISING', 'AUSPICIOUS', 'FAVORABLE'] },
    { word: 'OPULENT', ans: 'WEALTHY', wrong: ['POOR', 'IMPOVERISHED', 'DESTITUTE'] },
    { word: 'ORIGIN', ans: 'SOURCE', wrong: ['END', 'CONCLUSION', 'TERMINATION'] },
    { word: 'OUTRAGEOUS', ans: 'SHOCKING', wrong: ['MILD', 'TAME', 'MODERATE'] },
    { word: 'PALTRY', ans: 'TRIVIAL', wrong: ['SUBSTANTIAL', 'CONSIDERABLE', 'SIGNIFICANT'] },
    { word: 'PARAMOUNT', ans: 'SUPREME', wrong: ['MINOR', 'INFERIOR', 'SUBORDINATE'] },
    { word: 'PARSIMONIOUS', ans: 'MISERLY', wrong: ['GENEROUS', 'EXTRAVAGANT', 'LAVISH'] },
    { word: 'PERTURB', ans: 'UPSET', wrong: ['CALM', 'SOOTHE', 'REASSURE'] },
    { word: 'PLACID', ans: 'CALM', wrong: ['AGITATED', 'TURBULENT', 'STORMY'] },
    { word: 'PLETHORA', ans: 'EXCESS', wrong: ['SCARCITY', 'SHORTAGE', 'DEARTH'] },
    { word: 'PRECARIOUS', ans: 'UNSAFE', wrong: ['SAFE', 'SECURE', 'STABLE'] },
    { word: 'PREDICAMENT', ans: 'DILEMMA', wrong: ['SOLUTION', 'RESOLUTION', 'ANSWER'] },
    { word: 'PREVALENT', ans: 'WIDESPREAD', wrong: ['RARE', 'UNCOMMON', 'SCARCE'] },
    { word: 'PRODIGAL', ans: 'WASTEFUL', wrong: ['FRUGAL', 'THRIFTY', 'ECONOMICAL'] },
    { word: 'PROLIFIC', ans: 'FERTILE', wrong: ['BARREN', 'UNPRODUCTIVE', 'STERILE'] },
    { word: 'PROMPT', ans: 'PUNCTUAL', wrong: ['SLOW', 'LATE', 'TARDY'] },
    { word: 'PRUDENT', ans: 'WISE', wrong: ['FOOLISH', 'RECKLESS', 'RASH'] },
    { word: 'QUELL', ans: 'SUPPRESS', wrong: ['PROVOKE', 'INCITE', 'STIR'] },
    { word: 'QUERULOUS', ans: 'COMPLAINING', wrong: ['CONTENTED', 'CHEERFUL', 'SATISFIED'] },
    { word: 'RANCOR', ans: 'RESENTMENT', wrong: ['GOODWILL', 'AFFECTION', 'FRIENDSHIP'] },
    { word: 'RAVAGE', ans: 'DEVASTATE', wrong: ['REPAIR', 'RESTORE', 'BUILD'] },
    { word: 'RECALCITRANT', ans: 'DEFIANT', wrong: ['OBEDIENT', 'COMPLIANT', 'COOPERATIVE'] },
    { word: 'RECLUSE', ans: 'HERMIT', wrong: ['SOCIALITE', 'GADABOUT', 'EXTROVERT'] },
    { word: 'REFUTE', ans: 'DISPROVE', wrong: ['PROVE', 'CONFIRM', 'SUPPORT'] },
    { word: 'RELEVANT', ans: 'PERTINENT', wrong: ['IRRELEVANT', 'INAPPLICABLE', 'UNRELATED'] },
    { word: 'REMORSE', ans: 'REGRET', wrong: ['SATISFACTION', 'CONTENTMENT', 'PRIDE'] },
    { word: 'RENOWN', ans: 'FAME', wrong: ['OBSCURITY', 'INFAMY', 'NOTORIETY'] },
    { word: 'REPLENISH', ans: 'RESTOCK', wrong: ['DEPLETE', 'EMPTY', 'DRAIN'] },
    { word: 'REPRIMAND', ans: 'REBUKE', wrong: ['PRAISE', 'COMMEND', 'APPLAUD'] },
    { word: 'RESILIENT', ans: 'FLEXIBLE', wrong: ['RIGID', 'INFLEXIBLE', 'STIFF'] },
    { word: 'RIVAL', ans: 'COMPETITOR', wrong: ['ALLY', 'PARTNER', 'ASSOCIATE'] },
    { word: 'RUGGED', ans: 'ROUGH', wrong: ['SMOOTH', 'SOFT', 'GENTLE'] },
    { word: 'SAGACIOUS', ans: 'WISE', wrong: ['FOOLISH', 'STUPID', 'DULL'] },
    { word: 'SEDATE', ans: 'SOBER', wrong: ['EXCITED', 'LIVELY', 'FLAMBOYANT'] },
    { word: 'SENSIBLE', ans: 'PRUDENT', wrong: ['FOOLISH', 'RECKLESS', 'ABSURD'] },
    { word: 'SERENE', ans: 'TRANQUIL', wrong: ['AGITATED', 'TURBULENT', 'NOISY'] },
    { word: 'SHREWD', ans: 'CUNNING', wrong: ['NAIVE', 'GULLIBLE', 'TRUSTING'] },
    { word: 'SLUGGISH', ans: 'LAZY', wrong: ['ENERGETIC', 'ACTIVE', 'LIVELY'] },
    { word: 'SOLACE', ans: 'COMFORT', wrong: ['AGONY', 'SUFFERING', 'PAIN'] },
    { word: 'SORDID', ans: 'FILTHY', wrong: ['CLEAN', 'PURE', 'SPOTLESS'] },
    { word: 'SPURIOUS', ans: 'FAKE', wrong: ['GENUINE', 'AUTHENTIC', 'REAL'] },
    { word: 'STERLING', ans: 'EXCELLENT', wrong: ['INFERIOR', 'MEDIOCRE', 'POOR'] },
    { word: 'STRINGENT', ans: 'STRICT', wrong: ['LENIENT', 'RELAXED', 'PERMISSIVE'] },
    { word: 'SUBTLE', ans: 'SLIGHT', wrong: ['OBVIOUS', 'NOTICEABLE', 'CONSPICUOUS'] },
    { word: 'SUPERFLUOUS', ans: 'EXCESSIVE', wrong: ['ESSENTIAL', 'NECESSARY', 'REQUIRED'] },
    { word: 'SUPPRESS', ans: 'CONCEAL', wrong: ['REVEAL', 'EXPOSE', 'DISCLOSE'] },
    { word: 'SURFEIT', ans: 'EXCESS', wrong: ['DEFICIT', 'SCARCITY', 'SHORTAGE'] },
    { word: 'SURMOUNT', ans: 'OVERCOME', wrong: ['SURRENDER', 'YIELD', 'FAIL'] },
    { word: 'TACITURN', ans: 'RESERVED', wrong: ['TALKATIVE', 'LOQUACIOUS', 'GARRULOUS'] },
    { word: 'TEDIOUS', ans: 'MONOTONOUS', wrong: ['INTERESTING', 'EXCITING', 'ENTHRALLING'] },
    { word: 'TENACIOUS', ans: 'PERSISTENT', wrong: ['YIELDING', 'WEAK', 'WAVERING'] },
    { word: 'THRIFTY', ans: 'ECONOMICAL', wrong: ['WASTEFUL', 'EXTRAVAGANT', 'PRODIGAL'] },
    { word: 'TORPOR', ans: 'LETHARGY', wrong: ['ENERGY', 'VIGOR', 'LIVELINESS'] },
    { word: 'TRIVIAL', ans: 'INSIGNIFICANT', wrong: ['IMPORTANT', 'SIGNIFICANT', 'CRITICAL'] },
    { word: 'TYRANNICAL', ans: 'DESPOTIC', wrong: ['MERCIFUL', 'LENIENT', 'DEMOCRATIC'] },
    { word: 'UNANIMOUS', ans: 'AGREED', wrong: ['DIVIDED', 'SPLIT', 'DISAGREEING'] },
    { word: 'UNRUFFLED', ans: 'CALM', wrong: ['AGITATED', 'FLUSTERED', 'PERTURBED'] },
    { word: 'UNSCATHED', ans: 'UNHARMED', wrong: ['INJURED', 'WOUNDED', 'HURT'] },
    { word: 'UPROAR', ans: 'CHAOS', wrong: ['ORDER', 'PEACE', 'QUIET'] },
    { word: 'URBANE', ans: 'POLISHED', wrong: ['RUSTIC', 'ROUGH', 'VULGAR'] },
    { word: 'USURP', ans: 'SEIZE', wrong: ['RESTORE', 'RETURN', 'SURRENDER'] },
    { word: 'UTILIZE', ans: 'EMPLOY', wrong: ['DISCARD', 'ABANDON', 'WASTE'] },
    { word: 'VAGUE', ans: 'UNCLEAR', wrong: ['CLEAR', 'DEFINITE', 'PRECISE'] },
    { word: 'VALIANT', ans: 'BRAVE', wrong: ['COWARDLY', 'TIMID', 'FEARFUL'] },
    { word: 'VEHEMENT', ans: 'INTENSE', wrong: ['MILD', 'WEAK', 'LUKEWARM'] },
    { word: 'VENERATE', ans: 'REVERE', wrong: ['DESPISE', 'SCORN', 'DISREGARD'] },
    { word: 'VERBOSE', ans: 'WORDY', wrong: ['CONCISE', 'BRIEF', 'SUCCINCT'] },
    { word: 'VEX', ans: 'ANNOY', wrong: ['PLEASE', 'SOOTHE', 'COMFORT'] },
    { word: 'VIGILANT', ans: 'WATCHFUL', wrong: ['CARELESS', 'NEGLIGENT', 'HEEDLESS'] },
    { word: 'VINDICATE', ans: 'JUSTIFY', wrong: ['ACCUSE', 'BLAME', 'CONDEMN'] },
    { word: 'WANE', ans: 'DECLINE', wrong: ['INCREASE', 'GROW', 'RISE'] },
    { word: 'WILY', ans: 'CUNNING', wrong: ['NAIVE', 'GULLIBLE', 'INNOCENT'] },
    { word: 'YEARN', ans: 'LONG', wrong: ['SPURN', 'REJECT', 'DESPISE'] },
    { word: 'ZEALOUS', ans: 'ENTHUSIASTIC', wrong: ['APATHETIC', 'INDIFFERENT', 'LAZY'] },
    { word: 'ABHOR', ans: 'DETEST', wrong: ['ADMIRE', 'LOVE', 'LIKE'] },
    { word: 'ABIDE', ans: 'ENDURE', wrong: ['DEPART', 'REJECT', 'ABANDON'] },
    { word: 'ABLE', ans: 'CAPABLE', wrong: ['UNABLE', 'WEAK', 'INCAPABLE'] },
    { word: 'ABRIDGE', ans: 'SHORTEN', wrong: ['EXTEND', 'LENGTHEN', 'EXPAND'] },
    { word: 'ABSURD', ans: 'RIDICULOUS', wrong: ['SENSIBLE', 'RATIONAL', 'LOGICAL'] },
    { word: 'ABUNDANT', ans: 'PLENTIFUL', wrong: ['SCARCE', 'MEAGRE', 'SCANTY'] },
    { word: 'ACCELERATE', ans: 'HASTEN', wrong: ['SLOW', 'DELAY', 'RETARD'] },
    { word: 'ACCOMPLISH', ans: 'ACHIEVE', wrong: ['FAIL', 'ABANDON', 'QUIT'] },
    { word: 'ACQUIT', ans: 'EXONERATE', wrong: ['CONVICT', 'CONDEMN', 'ACCUSE'] },
    { word: 'ADEPT', ans: 'SKILLED', wrong: ['INEPT', 'CLUMSY', 'AWKWARD'] },
    { word: 'ADEQUATE', ans: 'SUFFICIENT', wrong: ['INSUFFICIENT', 'INADEQUATE', 'DEFICIENT'] },
    { word: 'ADHERENT', ans: 'FOLLOWER', wrong: ['LEADER', 'OPPONENT', 'CRITIC'] },
    { word: 'ADORATION', ans: 'WORSHIP', wrong: ['DISDAIN', 'CONTEMPT', 'SCORN'] },
    { word: 'ADORN', ans: 'DECORATE', wrong: ['DISFIGURE', 'STRIP', 'BARE'] },
    { word: 'ADVERSITY', ans: 'MISFORTUNE', wrong: ['PROSPERITY', 'FORTUNE', 'LUCK'] },
    { word: 'ADVOCATE', ans: 'SUPPORTER', wrong: ['OPPONENT', 'ADVERSARY', 'DETRACTOR'] },
    { word: 'AFFABLE', ans: 'FRIENDLY', wrong: ['HOSTILE', 'RUDE', 'UNFRIENDLY'] },
    { word: 'AFFLUENT', ans: 'WEALTHY', wrong: ['POOR', 'DESTITUTE', 'IMPOVERISHED'] },
    { word: 'AGHAST', ans: 'HORRIFIED', wrong: ['DELIGHTED', 'UNFAZED', 'UNMOVED'] },
    { word: 'AGILE', ans: 'NIMBLE', wrong: ['SLOW', 'CLUMSY', 'STIFF'] },
    { word: 'ALOOF', ans: 'DISTANT', wrong: ['FRIENDLY', 'SOCIABLE', 'WARM'] },
    { word: 'AMBIGUOUS', ans: 'UNCLEAR', wrong: ['CLEAR', 'DEFINITE', 'UNAMBIGUOUS'] },
    { word: 'AMELIORATE', ans: 'IMPROVE', wrong: ['WORSEN', 'DETERIORATE', 'AGGRAVATE'] },
    { word: 'AMIABLE', ans: 'PLEASANT', wrong: ['UNPLEASANT', 'HOSTILE', 'GRUMPY'] },
    { word: 'ANIMOSITY', ans: 'HOSTILITY', wrong: ['FRIENDSHIP', 'GOODWILL', 'AFFECTION'] },
    { word: 'ANNIHILATE', ans: 'DESTROY', wrong: ['PRESERVE', 'PROTECT', 'SAVE'] },
    { word: 'ANOMALY', ans: 'ABNORMALITY', wrong: ['NORMALITY', 'ROUTINE', 'STANDARD'] },
    { word: 'APATHY', ans: 'INDIFFERENCE', wrong: ['INTEREST', 'PASSION', 'ENTHUSIASM'] },
    { word: 'APPALL', ans: 'HORRIFY', wrong: ['PLEASE', 'DELIGHT', 'REASSURE'] },
    { word: 'ARDENT', ans: 'PASSIONATE', wrong: ['APATHETIC', 'INDIFFERENT', 'COLD'] },
    { word: 'ARDUOUS', ans: 'LABORIOUS', wrong: ['EASY', 'EFFORTLESS', 'SIMPLE'] },
    { word: 'ARROGANT', ans: 'HAUGHTY', wrong: ['HUMBLE', 'MODEST', 'MEEK'] },
    { word: 'ASCEND', ans: 'CLIMB', wrong: ['DESCEND', 'DROP', 'FALL'] },
    { word: 'ASSIDUOUS', ans: 'DILIGENT', wrong: ['LAZY', 'IDLE', 'CARELESS'] },
    { word: 'ASTONISH', ans: 'AMAZE', wrong: ['BORE', 'TIRE', 'WEARY'] },
    { word: 'AUGMENT', ans: 'INCREASE', wrong: ['DECREASE', 'REDUCE', 'DIMINISH'] },
    { word: 'AUSPICIOUS', ans: 'FAVOURABLE', wrong: ['UNFAVOURABLE', 'INOPPORTUNE', 'OMINOUS'] },
    { word: 'AUSTERE', ans: 'SEVERE', wrong: ['LAVISH', 'LUXURIOUS', 'INDULGENT'] },
    { word: 'AUTONOMY', ans: 'INDEPENDENCE', wrong: ['DEPENDENCE', 'SUBORDINATION', 'CONTROL'] },
    { word: 'BANAL', ans: 'TRITE', wrong: ['ORIGINAL', 'NOVEL', 'FRESH'] },
    { word: 'BANEFUL', ans: 'HARMFUL', wrong: ['BENEFICIAL', 'HARMLESS', 'HELPFUL'] },
    { word: 'BARRIER', ans: 'OBSTACLE', wrong: ['OPENING', 'PASSAGE', 'ENTRY'] },
    { word: 'BARTER', ans: 'EXCHANGE', wrong: ['KEEP', 'HOARD', 'RETAIN'] },
    { word: 'BEWILDER', ans: 'CONFUSE', wrong: ['CLARIFY', 'ENLIGHTEN', 'GUIDE'] },
    { word: 'BIAS', ans: 'PREJUDICE', wrong: ['FAIRNESS', 'IMPARTIALITY', 'OBJECTIVITY'] },
    { word: 'BLAND', ans: 'INSIPID', wrong: ['FLAVOURFUL', 'TASTY', 'SAVOURY'] },
    { word: 'BLATANT', ans: 'OBVIOUS', wrong: ['SUBTLE', 'HIDDEN', 'CONCEALED'] },
    { word: 'BOAST', ans: 'BRAG', wrong: ['BELITTLE', 'DISPARAGE', 'DOWNPLAY'] },
    { word: 'BOUNDLESS', ans: 'ENDLESS', wrong: ['LIMITED', 'BOUNDED', 'FINITE'] },
    { word: 'BRIEF', ans: 'CONCISE', wrong: ['LENGTHY', 'VERBOSE', 'LONG'] },
    { word: 'BRUTAL', ans: 'CRUEL', wrong: ['KIND', 'GENTLE', 'MERCIFUL'] },
    { word: 'CALAMITY', ans: 'DISASTER', wrong: ['BLESSING', 'BOON', 'FORTUNE'] },
    { word: 'CALLOUS', ans: 'INSENSITIVE', wrong: ['CARING', 'SENSITIVE', 'COMPASSIONATE'] },
    { word: 'CAPTIVATE', ans: 'ENCHANT', wrong: ['REPEL', 'DISGUST', 'BORE'] },
    { word: 'CATASTROPHE', ans: 'TRAGEDY', wrong: ['SUCCESS', 'TRIUMPH', 'VICTORY'] },
    { word: 'CAUTIOUS', ans: 'CAREFUL', wrong: ['RECKLESS', 'CARELESS', 'RASH'] },
    { word: 'CELESTIAL', ans: 'HEAVENLY', wrong: ['EARTHLY', 'WORLDLY', 'TERRESTRIAL'] },
    { word: 'CESSATION', ans: 'END', wrong: ['BEGINNING', 'START', 'COMMENCEMENT'] },
    { word: 'CHASTISE', ans: 'PUNISH', wrong: ['REWARD', 'PRAISE', 'COMMEND'] },
    { word: 'CHRONIC', ans: 'PERSISTENT', wrong: ['TEMPORARY', 'BRIEF', 'SHORT-TERM'] },
    { word: 'CIVIL', ans: 'COURTEOUS', wrong: ['RUDE', 'IMPOLITE', 'DISCOURTEOUS'] },
    { word: 'CLEMENCY', ans: 'MERCY', wrong: ['CRUELTY', 'HARSHNESS', 'SEVERITY'] },
    { word: 'COHERENT', ans: 'LOGICAL', wrong: ['CONFUSED', 'DISJOINTED', 'ILLOGICAL'] },
    { word: 'COLLABORATE', ans: 'COOPERATE', wrong: ['COMPETE', 'CONFLICT', 'CLASH'] },
    { word: 'COMMENCE', ans: 'BEGIN', wrong: ['END', 'FINISH', 'CONCLUDE'] },
    { word: 'COMPASSION', ans: 'SYMPATHY', wrong: ['INDIFFERENCE', 'APATHY', 'COLDNESS'] },
    { word: 'COMPENSATE', ans: 'REIMBURSE', wrong: ['DEPRIVE', 'CHEAT', 'DEFRAUD'] },
    { word: 'COMPLACENT', ans: 'SMUG', wrong: ['ANXIOUS', 'WORRIED', 'HUMBLE'] },
    { word: 'COMPRISE', ans: 'INCLUDE', wrong: ['EXCLUDE', 'OMIT', 'EXCEPT'] },
    { word: 'CONCISE', ans: 'BRIEF', wrong: ['VERBOSE', 'WORDY', 'DRAWN-OUT'] },
    { word: 'CONDEMN', ans: 'DENOUNCE', wrong: ['PRAISE', 'APPLAUD', 'COMMEND'] },
    { word: 'CONSEQUENCE', ans: 'RESULT', wrong: ['CAUSE', 'ORIGIN', 'SOURCE'] },
    { word: 'CONSTRAIN', ans: 'RESTRICT', wrong: ['FREE', 'RELEASE', 'LIBERATE'] },
    { word: 'CONTEMPT', ans: 'SCORN', wrong: ['RESPECT', 'ADMIRATION', 'REGARD'] },
    { word: 'CONTRADICT', ans: 'DENY', wrong: ['AGREE', 'CONFIRM', 'AFFIRM'] },
    { word: 'CONVENIENT', ans: 'SUITABLE', wrong: ['INCONVENIENT', 'INAPPROPRIATE', 'UNSUITABLE'] },
    { word: 'CONVENTIONAL', ans: 'TRADITIONAL', wrong: ['UNCONVENTIONAL', 'MODERN', 'INNOVATIVE'] },
    { word: 'COPIOUS', ans: 'ABUNDANT', wrong: ['SCANTY', 'MEAGRE', 'SPARSE'] },
    { word: 'CORROBORATE', ans: 'CONFIRM', wrong: ['REFUTE', 'DENY', 'DISPROVE'] }
  ],
  ANTONYMS: [
    { word: 'ABUNDANT', ans: 'SCARCE', wrong: ['PLENTIFUL', 'AMPLE', 'RICH'] },
    { word: 'ABSURD', ans: 'SENSIBLE', wrong: ['RIDICULOUS', 'FOOLISH', 'IRRATIONAL'] },
    { word: 'ACCURATE', ans: 'INEXACT', wrong: ['EXACT', 'PRECISE', 'CORRECT'] },
    { word: 'ACTIVE', ans: 'IDLE', wrong: ['ENERGETIC', 'LIVELY', 'ALERT'] },
    { word: 'ADEPT', ans: 'INEPT', wrong: ['SKILLED', 'PROFICIENT', 'EXPERT'] },
    { word: 'ADMIRE', ans: 'DESPISE', wrong: ['RESPECT', 'HONOR', 'PRAISE'] },
    { word: 'AFFLUENT', ans: 'POOR', wrong: ['WEALTHY', 'RICH', 'PROSPEROUS'] },
    { word: 'AGREEABLE', ans: 'DISAGREEABLE', wrong: ['PLEASANT', 'AMIABLE', 'CORDIAL'] },
    { word: 'ALWAYS', ans: 'NEVER', wrong: ['FOREVER', 'EVER', 'CONSTANTLY'] },
    { word: 'AMATEUR', ans: 'PROFESSIONAL', wrong: ['NOVICE', 'BEGINNER', 'ROOKIE'] },
    { word: 'ANCIENT', ans: 'MODERN', wrong: ['ANTIQUE', 'OLD', 'ARCHAIC'] },
    { word: 'ANGER', ans: 'CALM', wrong: ['FURIOUS', 'ENRAGED', 'IRRITATED'] },
    { word: 'ARRIVE', ans: 'DEPART', wrong: ['COME', 'REACH', 'APPEAR'] },
    { word: 'ARTIFICIAL', ans: 'NATURAL', wrong: ['SYNTHETIC', 'MANMADE', 'FAKE'] },
    { word: 'ASK', ans: 'ANSWER', wrong: ['REQUEST', 'INQUIRE', 'QUESTION'] },
    { word: 'ASSEMBLE', ans: 'DISPERSE', wrong: ['GATHER', 'COLLECT', 'CONGREGATE'] },
    { word: 'ATTACK', ans: 'DEFEND', wrong: ['ASSAULT', 'STRIKE', 'ASSAIL'] },
    { word: 'AUTHENTIC', ans: 'FORGED', wrong: ['GENUINE', 'REAL', 'TRUE'] },
    { word: 'AWKWARD', ans: 'GRACEFUL', wrong: ['CLUMSY', 'GAUCHE', 'UNGAINLY'] },
    { word: 'BARBAROUS', ans: 'CIVILIZED', wrong: ['SAVAGE', 'CRUEL', 'BRUTAL'] },
    { word: 'BEAUTIFUL', ans: 'UGLY', wrong: ['PRETTY', 'GORGEOUS', 'STUNNING'] },
    { word: 'BOLD', ans: 'TIMID', wrong: ['BRAVE', 'FEARLESS', 'COURAGEOUS'] },
    { word: 'BRIGHT', ans: 'DULL', wrong: ['SHINING', 'RADIANT', 'BRILLIANT'] },
    { word: 'CALM', ans: 'TURBULENT', wrong: ['PEACEFUL', 'SERENE', 'QUIET'] },
    { word: 'CAPABLE', ans: 'INCOMPETENT', wrong: ['ABLE', 'SKILLED', 'QUALIFIED'] },
    { word: 'CAUTIOUS', ans: 'RECKLESS', wrong: ['CAREFUL', 'WARY', 'PRUDENT'] },
    { word: 'CEASE', ans: 'BEGIN', wrong: ['STOP', 'END', 'TERMINATE'] },
    { word: 'CHEERFUL', ans: 'GLOOMY', wrong: ['JOYFUL', 'MERRY', 'HAPPY'] },
    { word: 'CIVILIZED', ans: 'BARBAROUS', wrong: ['CULTURED', 'POLISHED', 'REFINED'] },
    { word: 'CLARITY', ans: 'CONFUSION', wrong: ['CLEARNESS', 'PRECISION', 'LUCIDITY'] },
    { word: 'CLEAN', ans: 'FILTHY', wrong: ['SPOTLESS', 'IMMACULATE', 'PRISTINE'] },
    { word: 'CLEVER', ans: 'STUPID', wrong: ['INTELLIGENT', 'SMART', 'BRILLIANT'] },
    { word: 'COARSE', ans: 'FINE', wrong: ['ROUGH', 'RUGGED', 'HARSH'] },
    { word: 'COMFORT', ans: 'DISCOMFORT', wrong: ['EASE', 'RELIEF', 'CONSOLATION'] },
    { word: 'COMPULSORY', ans: 'OPTIONAL', wrong: ['REQUIRED', 'MANDATORY', 'OBLIGATORY'] },
    { word: 'CONCEAL', ans: 'REVEAL', wrong: ['HIDE', 'COVER', 'MASK'] },
    { word: 'CONCISE', ans: 'VERBOSE', wrong: ['BRIEF', 'SUCCINCT', 'TERSE'] },
    { word: 'CONNECT', ans: 'DISCONNECT', wrong: ['JOIN', 'ATTACH', 'LINK'] },
    { word: 'CONQUER', ans: 'SURRENDER', wrong: ['DEFEAT', 'OVERCOME', 'SUBDUE'] },
    { word: 'CONSERVATIVE', ans: 'LIBERAL', wrong: ['TRADITIONAL', 'CONVENTIONAL', 'ORTHODOX'] },
    { word: 'CONSIDERATE', ans: 'THOUGHTLESS', wrong: ['THOUGHTFUL', 'KIND', 'ATTENTIVE'] },
    { word: 'CONSTANT', ans: 'VARIABLE', wrong: ['STEADY', 'UNCHANGING', 'STABLE'] },
    { word: 'CONTENTED', ans: 'DISSATISFIED', wrong: ['SATISFIED', 'HAPPY', 'PLEASED'] },
    { word: 'COURAGE', ans: 'COWARDICE', wrong: ['BRAVERY', 'VALOR', 'FEARLESSNESS'] },
    { word: 'COURTEOUS', ans: 'RUDE', wrong: ['POLITE', 'CIVIL', 'WELLMANNERED'] },
    { word: 'CRUEL', ans: 'MERCIFUL', wrong: ['BRUTAL', 'SAVAGE', 'HEARTLESS'] },
    { word: 'CURIOSITY', ans: 'INDIFFERENCE', wrong: ['INTEREST', 'INQUISITIVENESS', 'EAGERNESS'] },
    { word: 'DANGEROUS', ans: 'SAFE', wrong: ['PERILOUS', 'HAZARDOUS', 'RISKY'] },
    { word: 'DARKNESS', ans: 'LIGHT', wrong: ['GLOOM', 'SHADOW', 'OBSCURITY'] },
    { word: 'DAWN', ans: 'DUSK', wrong: ['SUNRISE', 'MORNING', 'DAYBREAK'] },
    { word: 'DECAY', ans: 'GROWTH', wrong: ['ROT', 'DECLINE', 'DECOMPOSITION'] },
    { word: 'DECEITFUL', ans: 'HONEST', wrong: ['DISHONEST', 'FALSE', 'DECEPTIVE'] },
    { word: 'DEFICIT', ans: 'SURPLUS', wrong: ['SHORTAGE', 'LOSS', 'DEFICIENCY'] },
    { word: 'DEFIANT', ans: 'SUBMISSIVE', wrong: ['REBELLIOUS', 'DISOBEDIENT', 'OBSTINATE'] },
    { word: 'DELICATE', ans: 'ROBUST', wrong: ['FRAGILE', 'FRAIL', 'SLENDER'] },
    { word: 'DEMAND', ans: 'SUPPLY', wrong: ['REQUIRE', 'REQUEST', 'CLAIM'] },
    { word: 'DEPART', ans: 'ARRIVE', wrong: ['LEAVE', 'GO', 'WITHDRAW'] },
    { word: 'DEPENDENT', ans: 'INDEPENDENT', wrong: ['RELIANT', 'NEEDY', 'HELPLESS'] },
    { word: 'DESPAIR', ans: 'HOPE', wrong: ['DESPONDENCY', 'MISERY', 'GLOOM'] },
    { word: 'DESTROY', ans: 'CREATE', wrong: ['DEMOLISH', 'WRECK', 'RUIN'] },
    { word: 'DIMINISH', ans: 'AUGMENT', wrong: ['DECREASE', 'REDUCE', 'LESSEN'] },
    { word: 'DIPLOMATIC', ans: 'TACTLESS', wrong: ['TACTFUL', 'POLITE', 'DISCREET'] },
    { word: 'DISAGREE', ans: 'CONCUR', wrong: ['DIFFER', 'DISSENT', 'OBJECT'] },
    { word: 'DISMAL', ans: 'CHEERFUL', wrong: ['GLOOMY', 'BLEAK', 'SOMBER'] },
    { word: 'DISPEL', ans: 'GATHER', wrong: ['DISPERSE', 'SCATTER', 'DISSOLVE'] },
    { word: 'DIVERSE', ans: 'SIMILAR', wrong: ['VARIED', 'DIFFERENT', 'MANIFOLD'] },
    { word: 'DORMANT', ans: 'ACTIVE', wrong: ['INACTIVE', 'LATENT', 'QUIESCENT'] },
    { word: 'DULL', ans: 'SHARP', wrong: ['BORING', 'TEDIOUS', 'BLUNT'] },
    { word: 'EAGER', ans: 'RELUCTANT', wrong: ['ENTHUSIASTIC', 'KEEN', 'ARDENT'] },
    { word: 'EASY', ans: 'DIFFICULT', wrong: ['SIMPLE', 'EFFORTLESS', 'ELEMENTARY'] },
    { word: 'ECONOMICAL', ans: 'EXTRAVAGANT', wrong: ['THRIFTY', 'FRUGAL', 'SPARING'] },
    { word: 'EDIBLE', ans: 'POISONOUS', wrong: ['EATABLE', 'WHOLESOME', 'NOURISHING'] },
    { word: 'EGOISM', ans: 'ALTRUISM', wrong: ['SELFISHNESS', 'CONCEIT', 'VANITY'] },
    { word: 'ELEGANT', ans: 'GAUDY', wrong: ['GRACEFUL', 'REFINED', 'CHIC'] },
    { word: 'EMPHASIZE', ans: 'DOWNPLAY', wrong: ['STRESS', 'ACCENTUATE', 'UNDERSCORE'] },
    { word: 'EMPTY', ans: 'FULL', wrong: ['VACANT', 'VOID', 'BARE'] },
    { word: 'ENCOURAGE', ans: 'DISCOURAGE', wrong: ['MOTIVATE', 'INSPIRE', 'URGE'] },
    { word: 'ENDURING', ans: 'FLEETING', wrong: ['LASTING', 'PERMANENT', 'ETERNAL'] },
    { word: 'ENEMY', ans: 'ALLY', wrong: ['FOE', 'ADVERSARY', 'OPPONENT'] },
    { word: 'ENORMOUS', ans: 'MINUTE', wrong: ['HUGE', 'GIGANTIC', 'VAST'] },
    { word: 'ENVIOUS', ans: 'CONTENTED', wrong: ['JEALOUS', 'COVETOUS', 'RESENTFUL'] },
    { word: 'ERRATIC', ans: 'STEADY', wrong: ['IRREGULAR', 'UNPREDICTABLE', 'VOLATILE'] },
    { word: 'EXCITE', ans: 'CALM', wrong: ['AGITATE', 'STIMULATE', 'AROUSE'] },
    { word: 'EXPAND', ans: 'CONTRACT', wrong: ['ENLARGE', 'EXTEND', 'STRETCH'] },
    { word: 'EXPENSIVE', ans: 'CHEAP', wrong: ['COSTLY', 'PRICEY', 'DEAR'] },
    { word: 'EXPLICIT', ans: 'VAGUE', wrong: ['CLEAR', 'DEFINITE', 'UNAMBIGUOUS'] },
    { word: 'EXTRAVAGANT', ans: 'FRUGAL', wrong: ['PROFLIGATE', 'WASTEFUL', 'SPENDTHRIFT'] },
    { word: 'FABULOUS', ans: 'ORDINARY', wrong: ['AMAZING', 'ASTONISHING', 'REMARKABLE'] },
    { word: 'FACT', ans: 'FICTION', wrong: ['REALITY', 'TRUTH', 'CERTAINTY'] },
    { word: 'FAILURE', ans: 'SUCCESS', wrong: ['DEFEAT', 'DISASTER', 'FLOP'] },
    { word: 'FAITHFUL', ans: 'TREACHEROUS', wrong: ['LOYAL', 'DEVOTED', 'TRUSTWORTHY'] },
    { word: 'FAMILIAR', ans: 'STRANGE', wrong: ['WELLKNOWN', 'ACCUSTOMED', 'USUAL'] },
    { word: 'FATIGUE', ans: 'ENERGY', wrong: ['EXHAUSTION', 'TIREDNESS', 'WEARINESS'] },
    { word: 'FEARLESS', ans: 'COWARDLY', wrong: ['BRAVE', 'BOLD', 'DARING'] },
    { word: 'FERTILE', ans: 'BARREN', wrong: ['FRUITFUL', 'PRODUCTIVE', 'RICH'] },
    { word: 'FIERCE', ans: 'GENTLE', wrong: ['FEROCIOUS', 'SAVAGE', 'VIOLENT'] },
    { word: 'FLEXIBLE', ans: 'RIGID', wrong: ['PLIANT', 'SUPPLE', 'ADAPTABLE'] },
    { word: 'FLOURISH', ans: 'DECAY', wrong: ['THRIVE', 'PROSPER', 'BLOSSOM'] },
    { word: 'FOCUS', ans: 'DISTRACT', wrong: ['CONCENTRATE', 'CONVERGE', 'CENTER'] },
    { word: 'FOLLOW', ans: 'LEAD', wrong: ['PURSUE', 'TRACK', 'CHASE'] },
    { word: 'FOUND', ans: 'DESTROY', wrong: ['ESTABLISH', 'CREATE', 'INVENT'] },
    { word: 'FREEDOM', ans: 'BONDAGE', wrong: ['LIBERTY', 'INDEPENDENCE', 'AUTONOMY'] },
    { word: 'FRESH', ans: 'STALE', wrong: ['NEW', 'CRISP', 'RECENT'] },
    { word: 'FRIEND', ans: 'FOE', wrong: ['COMPANION', 'ALLY', 'CONFIDANT'] },
    { word: 'FRUGAL', ans: 'EXTRAVAGANT', wrong: ['THRIFTY', 'ECONOMICAL', 'SPARING'] },
    { word: 'GENEROUS', ans: 'STINGY', wrong: ['LIBERAL', 'BOUNTIFUL', 'CHARITABLE'] },
    { word: 'GENTLE', ans: 'ROUGH', wrong: ['MILD', 'SOFT', 'TENDER'] },
    { word: 'GENUINE', ans: 'COUNTERFEIT', wrong: ['REAL', 'AUTHENTIC', 'ACTUAL'] },
    { word: 'GLOOMY', ans: 'CHEERFUL', wrong: ['DARK', 'SOMBER', 'DREARY'] },
    { word: 'GRACEFUL', ans: 'AWKWARD', wrong: ['ELEGANT', 'POISED', 'FLUID'] },
    { word: 'GRATEFUL', ans: 'UNGRATEFUL', wrong: ['THANKFUL', 'APPRECIATIVE', 'OBLIGED'] },
    { word: 'GREED', ans: 'GENEROSITY', wrong: ['CUPIDITY', 'AVARICE', 'COVETOUSNESS'] },
    { word: 'GUILT', ans: 'INNOCENCE', wrong: ['BLAME', 'CULPABILITY', 'RESPONSIBILITY'] },
    { word: 'HAPPINESS', ans: 'MISERY', wrong: ['JOY', 'DELIGHT', 'GLADNESS'] },
    { word: 'HARSH', ans: 'MILD', wrong: ['SEVERE', 'ROUGH', 'CRUEL'] },
    { word: 'HASTE', ans: 'DELIBERATION', wrong: ['RUSH', 'SPEED', 'HURRY'] },
    { word: 'HATEFUL', ans: 'LOVING', wrong: ['ODIOUS', 'DETESTABLE', 'ABHORRENT'] },
    { word: 'HEALTHY', ans: 'ILL', wrong: ['WELL', 'FIT', 'ROBUST'] },
    { word: 'HIDDEN', ans: 'VISIBLE', wrong: ['CONCEALED', 'COVERT', 'SECRET'] },
    { word: 'HONEST', ans: 'DECEITFUL', wrong: ['TRUTHFUL', 'SINCERE', 'FAITHFUL'] },
    { word: 'HUMBLE', ans: 'PROUD', wrong: ['MODEST', 'MEEK', 'UNASSUMING'] },
    { word: 'IGNORANT', ans: 'INFORMED', wrong: ['UNEDUCATED', 'UNINFORMED', 'OBLIVIOUS'] },
    { word: 'IMPORTANT', ans: 'TRIVIAL', wrong: ['SIGNIFICANT', 'CRITICAL', 'VITAL'] },
    { word: 'INACTIVE', ans: 'ACTIVE', wrong: ['IDLE', 'LAZY', 'SLUGGISH'] },
    { word: 'INCLUDE', ans: 'EXCLUDE', wrong: ['CONTAIN', 'ENCOMPASS', 'EMBRACE'] },
    { word: 'INCOME', ans: 'EXPENDITURE', wrong: ['EARNINGS', 'REVENUE', 'PROFIT'] },
    { word: 'INCREASE', ans: 'DECREASE', wrong: ['GROW', 'RISE', 'EXPAND'] },
    { word: 'INDIFFERENT', ans: 'CONCERNED', wrong: ['APATHETIC', 'UNCARING', 'UNINTERESTED'] },
    { word: 'INFLATE', ans: 'DEFLATE', wrong: ['EXPAND', 'SWELL', 'ENLARGE'] },
    { word: 'INNOCENT', ans: 'GUILTY', wrong: ['PURE', 'BLAMELESS', 'VIRTUOUS'] },
    { word: 'INTERIOR', ans: 'EXTERIOR', wrong: ['INSIDE', 'INNER', 'INTERNAL'] },
    { word: 'INTRODUCE', ans: 'CONCLUDE', wrong: ['PRESENT', 'ANNOUNCE', 'USHER'] },
    { word: 'JOYOUS', ans: 'SORROWFUL', wrong: ['JOYFUL', 'HAPPY', 'MERRY'] },
    { word: 'JUVENILE', ans: 'MATURE', wrong: ['YOUTHFUL', 'CHILDISH', 'IMMATURE'] },
    { word: 'KNOWN', ans: 'UNKNOWN', wrong: ['FAMOUS', 'NOTED', 'RECOGNIZED'] },
    { word: 'LAUGH', ans: 'CRY', wrong: ['CHUCKLE', 'GIGGLE', 'SMILE'] },
    { word: 'LAZY', ans: 'INDUSTRIOUS', wrong: ['IDLE', 'SLUGGISH', 'INDOLENT'] },
    { word: 'LEADING', ans: 'FOLLOWING', wrong: ['FOREMOST', 'PRIMARY', 'CHIEF'] },
    { word: 'LENIENT', ans: 'STRICT', wrong: ['INDULGENT', 'MERCIFUL', 'TOLERANT'] },
    { word: 'LIGHT', ans: 'HEAVY', wrong: ['BRIGHT', 'ILLUMINATED', 'LUMINOUS'] },
    { word: 'LIMIT', ans: 'EXTEND', wrong: ['RESTRICT', 'BOUND', 'CONFINE'] },
    { word: 'LIQUID', ans: 'SOLID', wrong: ['FLUID', 'RUNNY', 'WATERY'] },
    { word: 'LIVE', ans: 'DEAD', wrong: ['ALIVE', 'LIVING', 'BREATHING'] },
    { word: 'LOUD', ans: 'QUIET', wrong: ['NOISY', 'SONOROUS', 'RESOUNDING'] },
    { word: 'LUXURIOUS', ans: 'AUSTERE', wrong: ['LAVISH', 'OPULENT', 'PALATIAL'] },
    { word: 'MARRY', ans: 'DIVORCE', wrong: ['WED', 'UNITE', 'ESPOUSE'] },
    { word: 'MATURE', ans: 'IMMATURE', wrong: ['ADULT', 'DEVELOPED', 'RIPE'] },
    { word: 'MEAN', ans: 'GENEROUS', wrong: ['STINGY', 'MISERLY', 'PARSIMONIOUS'] },
    { word: 'MELODY', ans: 'DISCORD', wrong: ['TUNE', 'HARMONY', 'SONG'] },
    { word: 'MIGRATE', ans: 'SETTLE', wrong: ['MOVE', 'RELOCATE', 'EMIGRATE'] },
    { word: 'MINOR', ans: 'MAJOR', wrong: ['SMALL', 'LITTLE', 'PETTY'] },
    { word: 'MODEST', ans: 'VAIN', wrong: ['HUMBLE', 'UNASSUMING', 'RETIRING'] },
    { word: 'MOIST', ans: 'DRY', wrong: ['DAMP', 'WET', 'HUMID'] },
    { word: 'NATIVE', ans: 'FOREIGN', wrong: ['INDIGENOUS', 'LOCAL', 'ABORIGINAL'] },
    { word: 'NEAT', ans: 'MESSY', wrong: ['TIDY', 'ORDERLY', 'CLEAN'] },
    { word: 'NEGLIGENT', ans: 'CAREFUL', wrong: ['CARELESS', 'REMISS', 'HEEDLESS'] },
    { word: 'NOBLE', ans: 'IGNOBLE', wrong: ['HONORABLE', 'DIGNIFIED', 'LOFTY'] },
    { word: 'OBEDIENT', ans: 'DISOBEDIENT', wrong: ['COMPLIANT', 'DUTIFUL', 'SUBMISSIVE'] },
    { word: 'OBSCURE', ans: 'FAMOUS', wrong: ['UNCLEAR', 'AMBIGUOUS', 'VAGUE'] },
    { word: 'OBVIOUS', ans: 'OBSCURE', wrong: ['EVIDENT', 'CLEAR', 'APPARENT'] },
    { word: 'OPTIMISTIC', ans: 'PESSIMISTIC', wrong: ['HOPEFUL', 'POSITIVE', 'CONFIDENT'] },
    { word: 'ORDINARY', ans: 'EXTRAORDINARY', wrong: ['COMMON', 'AVERAGE', 'NORMAL'] },
    { word: 'OUTGOING', ans: 'RESERVED', wrong: ['FRIENDLY', 'SOCIABLE', 'EXTROVERTED'] },
    { word: 'PEACEFUL', ans: 'AGGRESSIVE', wrong: ['CALM', 'QUIET', 'SERENE'] },
    { word: 'PAST', ans: 'FUTURE', wrong: ['FORMER', 'PREVIOUS', 'PRIOR'] },
    { word: 'PATIENT', ans: 'IMPATIENT', wrong: ['TOLERANT', 'ENDURING', 'PERSISTENT'] },
    { word: 'PERMANENT', ans: 'TEMPORARY', wrong: ['ETERNAL', 'LASTING', 'EVERLASTING'] },
    { word: 'PLEASANT', ans: 'UNPLEASANT', wrong: ['AGREEABLE', 'DELIGHTFUL', 'ENJOYABLE'] },
    { word: 'PLENTIFUL', ans: 'SCARCE', wrong: ['ABUNDANT', 'AMPLE', 'COPIOUS'] },
    { word: 'POLITE', ans: 'RUDE', wrong: ['COURTEOUS', 'CIVIL', 'GRACIOUS'] },
    { word: 'POLLUTED', ans: 'PRISTINE', wrong: ['CONTAMINATED', 'TAINTED', 'IMPURE'] },
    { word: 'POOR', ans: 'RICH', wrong: ['DESTITUTE', 'PENNILESS', 'IMPOVERISHED'] },
    { word: 'PRAISE', ans: 'CRITICIZE', wrong: ['COMMEND', 'APPLAUD', 'LAUD'] },
    { word: 'PRESENT', ans: 'ABSENT', wrong: ['CURRENT', 'EXISTING', 'HERE'] },
    { word: 'PROGRESS', ans: 'REGRESS', wrong: ['ADVANCE', 'ADVANCEMENT', 'IMPROVEMENT'] },
    { word: 'PROHIBIT', ans: 'PERMIT', wrong: ['BAN', 'FORBID', 'DISALLOW'] },
    { word: 'PROUD', ans: 'HUMBLE', wrong: ['CONCEITED', 'VAIN', 'ARROGANT'] },
    { word: 'PUNCTUAL', ans: 'TARDY', wrong: ['PROMPT', 'ONTIME', 'TIMELY'] },
    { word: 'QUIET', ans: 'NOISY', wrong: ['SILENT', 'STILL', 'CALM'] },
    { word: 'RAPID', ans: 'SLOW', wrong: ['FAST', 'QUICK', 'SWIFT'] },
    { word: 'RARE', ans: 'COMMON', wrong: ['UNUSUAL', 'UNCOMMON', 'SCARCE'] },
    { word: 'REAL', ans: 'IMAGINARY', wrong: ['ACTUAL', 'TRUE', 'GENUINE'] },
    { word: 'REGULAR', ans: 'IRREGULAR', wrong: ['ROUTINE', 'NORMAL', 'USUAL'] },
    { word: 'RELAXED', ans: 'TENSE', wrong: ['EASYGOING', 'CALM', 'UNHURRIED'] },
    { word: 'RENOWNED', ans: 'OBSCURE', wrong: ['FAMOUS', 'CELEBRATED', 'ILLUSTRIOUS'] },
    { word: 'REPAIR', ans: 'DAMAGE', wrong: ['FIX', 'MEND', 'RESTORE'] },
    { word: 'RISE', ans: 'FALL', wrong: ['ASCEND', 'CLIMB', 'ASCENT'] },
    { word: 'RUDE', ans: 'POLITE', wrong: ['IMPOLITE', 'DISCOURTEOUS', 'ROUGH'] },
    { word: 'SACRED', ans: 'PROFANE', wrong: ['HOLY', 'DIVINE', 'BLESSED'] },
    { word: 'SAFETY', ans: 'DANGER', wrong: ['SECURITY', 'PROTECTION', 'SHELTER'] },
    { word: 'SCATTER', ans: 'COLLECT', wrong: ['DISPERSE', 'SPREAD', 'DISSEMINATE'] },
    { word: 'SENSITIVE', ans: 'INSENSITIVE', wrong: ['DELICATE', 'TENDER', 'PERCEPTIVE'] },
    { word: 'SERIOUS', ans: 'TRIVIAL', wrong: ['SOLEMN', 'GRAVE', 'EARNEST'] },
    { word: 'SHALLOW', ans: 'DEEP', wrong: ['SUPERFICIAL', 'SURFACE', 'FRIVOLOUS'] },
    { word: 'SHARP', ans: 'BLUNT', wrong: ['KEEN', 'ACUTE', 'POINTED'] },
    { word: 'SHORT', ans: 'LONG', wrong: ['BRIEF', 'CONCISE', 'TERSE'] },
    { word: 'SKILLED', ans: 'UNSKILLED', wrong: ['EXPERT', 'PROFICIENT', 'ADEPT'] },
    { word: 'SOBER', ans: 'INTOXICATED', wrong: ['SERIOUS', 'STEADY', 'MODERATE'] },
    { word: 'SOFT', ans: 'HARD', wrong: ['TENDER', 'SILKY', 'SMOOTH'] },
    { word: 'SOLID', ans: 'LIQUID', wrong: ['FIRM', 'HARD', 'DENSE'] },
    { word: 'SOURCE', ans: 'END', wrong: ['ORIGIN', 'BEGINNING', 'ROOT'] },
    { word: 'SPARSE', ans: 'DENSE', wrong: ['SCATTERED', 'SCANTY', 'THIN'] },
    { word: 'STABLE', ans: 'UNSTABLE', wrong: ['FIRM', 'SECURE', 'STEADY'] },
    { word: 'STINGY', ans: 'GENEROUS', wrong: ['MISERLY', 'TIGHTFISTED', 'PENURIOUS'] },
    { word: 'STRENGTH', ans: 'WEAKNESS', wrong: ['POWER', 'FORCE', 'MIGHT'] },
    { word: 'SUCCEED', ans: 'FAIL', wrong: ['TRIUMPH', 'PROSPER', 'PREVAIL'] },
    { word: 'SUNRISE', ans: 'SUNSET', wrong: ['DAWN', 'DAYBREAK', 'MORNING'] },
    { word: 'SWEET', ans: 'SOUR', wrong: ['SACCHARINE', 'SYRUPY', 'HONEYED'] },
    { word: 'SYMPATHY', ans: 'ANTIPATHY', wrong: ['PITY', 'COMPASSION', 'MERCY'] },
    { word: 'TALL', ans: 'SHORT', wrong: ['HIGH', 'LOFTY', 'TOWERING'] },
    { word: 'TEMPORARY', ans: 'PERMANENT', wrong: ['BRIEF', 'FLEETING', 'TRANSITORY'] },
    { word: 'THEORY', ans: 'PRACTICE', wrong: ['PRINCIPLE', 'DOCTRINE', 'HYPOTHESIS'] },
    { word: 'TOLERANT', ans: 'INTOLERANT', wrong: ['FORBEARING', 'PERMISSIVE', 'LENIENT'] },
    { word: 'TRANSPARENT', ans: 'OPAQUE', wrong: ['CLEAR', 'SHEER', 'LUCID'] },
    { word: 'TRUST', ans: 'SUSPECT', wrong: ['BELIEVE', 'RELY', 'DEPEND'] },
    { word: 'UNANIMOUS', ans: 'DISSENTIENT', wrong: ['AGREED', 'UNISON', 'SOLIDARITY'] },
    { word: 'UNCOMFORTABLE', ans: 'COMFORTABLE', wrong: ['UNEASY', 'UNPLEASANT', 'AWKWARD'] },
    { word: 'USUAL', ans: 'UNUSUAL', wrong: ['CUSTOMARY', 'ORDINARY', 'NORMAL'] },
    { word: 'VICTORY', ans: 'DEFEAT', wrong: ['TRIUMPH', 'WIN', 'CONQUEST'] },
    { word: 'VIRTUOUS', ans: 'WICKED', wrong: ['RIGHTEOUS', 'MORAL', 'GOOD'] },
    { word: 'VIVID', ans: 'DULL', wrong: ['BRIGHT', 'LURID', 'INTENSE'] },
    { word: 'VOLUNTARY', ans: 'COMPULSORY', wrong: ['WILLING', 'SPONTANEOUS', 'DELIBERATE'] },
    { word: 'WARM', ans: 'COOL', wrong: ['HOT', 'BALMY', 'TOASTY'] },
    { word: 'WEAK', ans: 'STRONG', wrong: ['FEEBLE', 'FRAIL', 'POWERLESS'] },
    { word: 'WEALTH', ans: 'POVERTY', wrong: ['RICHES', 'FORTUNE', 'AFFLUENCE'] },
    { word: 'WIDE', ans: 'NARROW', wrong: ['BROAD', 'EXPANSIVE', 'SPACIOUS'] },
    { word: 'WILD', ans: 'TAME', wrong: ['FERAL', 'SAVAGE', 'UNTAMED'] },
    { word: 'WISE', ans: 'FOOLISH', wrong: ['SENSIBLE', 'JUDICIOUS', 'PRUDENT'] },
    { word: 'YOUNG', ans: 'OLD', wrong: ['YOUTHFUL', 'JUVENILE', 'IMMATURE'] },
    { word: 'ZEAL', ans: 'APATHY', wrong: ['ARDOR', 'PASSION', 'ENTHUSIASM'] },
    { word: 'ABANDON', ans: 'KEEP', wrong: ['FORSAKE', 'DESERT', 'LEAVE'] },
    { word: 'ABASH', ans: 'ENCOURAGE', wrong: ['EMBARRASS', 'HUMILIATE', 'MORTIFY'] },
    { word: 'ABATE', ans: 'INCREASE', wrong: ['SUBSIDE', 'LESSEN', 'DECLINE'] },
    { word: 'ABERRATION', ans: 'NORMALCY', wrong: ['ANOMALY', 'DEVIATION', 'ODDITY'] },
    { word: 'ABHOR', ans: 'ADMIRE', wrong: ['DETEST', 'LOATHE', 'DESPISE'] },
    { word: 'ABUNDANT', ans: 'SCARCE', wrong: ['PLENTIFUL', 'AMPLE', 'RICH'] },
    { word: 'ACCELERATE', ans: 'DECELERATE', wrong: ['HASTEN', 'QUICKEN', 'SPEED UP'] },
    { word: 'ACCEPT', ans: 'REJECT', wrong: ['WELCOME', 'RECEIVE', 'ADOPT'] },
    { word: 'ACCOUNTABLE', ans: 'IRRESPONSIBLE', wrong: ['ANSWERABLE', 'LIABLE', 'RESPONSIBLE'] },
    { word: 'ACCURATE', ans: 'INACCURATE', wrong: ['CORRECT', 'PRECISE', 'EXACT'] },
    { word: 'ACQUIRE', ans: 'LOSE', wrong: ['OBTAIN', 'GAIN', 'PROCURE'] },
    { word: 'ADEPT', ans: 'INEPT', wrong: ['SKILLED', 'EXPERT', 'ADROIT'] },
    { word: 'ADHERENT', ans: 'OPPONENT', wrong: ['FOLLOWER', 'SUPPORTER', 'DISCIPLE'] },
    { word: 'ADMONISH', ans: 'PRAISE', wrong: ['REPRIMAND', 'REBUKE', 'SCOLD'] },
    { word: 'ADVENT', ans: 'DEPARTURE', wrong: ['ARRIVAL', 'ONSET', 'COMING'] },
    { word: 'ADVERSITY', ans: 'PROSPERITY', wrong: ['MISFORTUNE', 'HARDSHIP', 'TRIBULATION'] },
    { word: 'ADVOCATE', ans: 'OPPOSE', wrong: ['SUPPORT', 'BACK', 'CHAMPION'] },
    { word: 'AFFABLE', ans: 'SURLLY', wrong: ['FRIENDLY', 'CORDIAL', 'GENIAL'] },
    { word: 'AFFLUENT', ans: 'IMPOVERISHED', wrong: ['WEALTHY', 'RICH', 'PROSPEROUS'] },
    { word: 'AGGRESSIVE', ans: 'PASSIVE', wrong: ['ASSERTIVE', 'FORCEFUL', 'MILITANT'] },
    { word: 'AGILE', ans: 'CLUMSY', wrong: ['NIMBLE', 'SPRY', 'QUICK'] },
    { word: 'ALIEN', ans: 'NATIVE', wrong: ['FOREIGN', 'EXTERNAL', 'EXOTIC'] },
    { word: 'ALLEVIATE', ans: 'WORSEN', wrong: ['RELIEVE', 'EASE', 'LESSEN'] },
    { word: 'ALLY', ans: 'ENEMY', wrong: ['PARTNER', 'FRIEND', 'ASSOCIATE'] },
    { word: 'ALOOF', ans: 'SOCIABLE', wrong: ['DISTANT', 'DETACHED', 'RESERVED'] },
    { word: 'AMATEUR', ans: 'PROFESSIONAL', wrong: ['BEGINNER', 'NOVICE', 'DILETTANTE'] },
    { word: 'AMBIGUOUS', ans: 'CLEAR', wrong: ['VAGUE', 'UNCLEAR', 'EQUIVOCAL'] },
    { word: 'AMIABLE', ans: 'HOSTILE', wrong: ['PLEASANT', 'FRIENDLY', 'GENIAL'] },
    { word: 'AMPLE', ans: 'MEAGRE', wrong: ['ABUNDANT', 'PLENTIFUL', 'GENEROUS'] },
    { word: 'ANCIENT', ans: 'MODERN', wrong: ['ANTIQUE', 'ARCHAIC', 'ANTIQUATED'] },
    { word: 'APATHETIC', ans: 'ENTHUSIASTIC', wrong: ['INDIFFERENT', 'UNINTERESTED', 'LISTLESS'] },
    { word: 'APPRECIATE', ans: 'CRITICISE', wrong: ['VALUE', 'ADMIRE', 'ESTEEM'] },
    { word: 'ARDENT', ans: 'COLD', wrong: ['PASSIONATE', 'FERVENT', 'ENTHUSIASTIC'] },
    { word: 'ARDUOUS', ans: 'EASY', wrong: ['LABORIOUS', 'STRENUOUS', 'TOILSOME'] },
    { word: 'ARROGANT', ans: 'HUMBLE', wrong: ['HAUGHTY', 'PROUD', 'CONCEITED'] },
    { word: 'ASCEND', ans: 'DESCEND', wrong: ['CLIMB', 'RISE', 'MOUNT'] },
    { word: 'ASKEW', ans: 'STRAIGHT', wrong: ['CROOKED', 'SLANTED', 'TWISTED'] },
    { word: 'ASTUTE', ans: 'FOOLISH', wrong: ['SHREWD', 'KEEN', 'PERCEPTIVE'] },
    { word: 'ATROCIOUS', ans: 'PLEASANT', wrong: ['HEINOUS', 'ABOMINABLE', 'HORRIBLE'] },
    { word: 'AUSPICIOUS', ans: 'UNFAVOURABLE', wrong: ['FAVOURABLE', 'OPPORTUNE', 'PROMISING'] },
    { word: 'AUTHENTIC', ans: 'FAKE', wrong: ['GENUINE', 'REAL', 'ORIGINAL'] },
    { word: 'AUSTERE', ans: 'EXTRAVAGANT', wrong: ['SEVERE', 'STERN', 'RIGID'] },
    { word: 'AUTHORITARIAN', ans: 'DEMOCRATIC', wrong: ['DICTATORIAL', 'TYRANNICAL', 'AUTOCRATIC'] },
    { word: 'AUTONOMY', ans: 'DEPENDENCE', wrong: ['INDEPENDENCE', 'SELF-RULE', 'SOVEREIGNTY'] },
    { word: 'AVARICE', ans: 'GENEROSITY', wrong: ['GREED', 'CUPIDITY', 'RAPACITY'] },
    { word: 'AVERSION', ans: 'ATTRACTION', wrong: ['DISLIKE', 'REPULSION', 'ANTIPATHY'] },
    { word: 'AWKWARD', ans: 'GRACEFUL', wrong: ['CLUMSY', 'GAUCHE', 'UNGAINLY'] },
    { word: 'BALMY', ans: 'STORMY', wrong: ['MILD', 'TEMPERATE', 'PLEASANT'] },
    { word: 'BANAL', ans: 'ORIGINAL', wrong: ['TRITE', 'CLICHED', 'COMMONPLACE'] },
    { word: 'BARBAROUS', ans: 'CIVILISED', wrong: ['SAVAGE', 'BRUTAL', 'CRUEL'] },
    { word: 'BENEFICIAL', ans: 'HARMFUL', wrong: ['ADVANTAGEOUS', 'HELPFUL', 'FAVOURABLE'] },
    { word: 'BENEVOLENT', ans: 'MALEVOLENT', wrong: ['KIND', 'CHARITABLE', 'GENEROUS'] },
    { word: 'BLATANT', ans: 'SUBTLE', wrong: ['OBVIOUS', 'GLARING', 'CONSPICUOUS'] },
    { word: 'BOLD', ans: 'TIMID', wrong: ['BRAVE', 'COURAGEOUS', 'FEARLESS'] },
    { word: 'BOUND', ans: 'FREE', wrong: ['TIED', 'FETTERED', 'SHACKLED'] },
    { word: 'BRIEF', ans: 'LONG', wrong: ['SHORT', 'CONCISE', 'SUCCINCT'] },
    { word: 'BURDENSOME', ans: 'LIGHT', wrong: ['HEAVY', 'OPPRESSIVE', 'ONEROUS'] },
    { word: 'CANDID', ans: 'EVASIVE', wrong: ['FRANK', 'HONEST', 'STRAIGHTFORWARD'] },
    { word: 'CAPTIVITY', ans: 'FREEDOM', wrong: ['IMPRISONMENT', 'CONFINEMENT', 'BONDAGE'] },
    { word: 'CASUAL', ans: 'FORMAL', wrong: ['INFORMAL', 'RELAXED', 'UNPREMEDITATED'] },
    { word: 'CELERITY', ans: 'SLOWNESS', wrong: ['SPEED', 'SWIFTNESS', 'RAPIDITY'] },
    { word: 'CESSATION', ans: 'RESUMPTION', wrong: ['STOPPAGE', 'HALT', 'TERMINATION'] },
    { word: 'CHAOS', ans: 'ORDER', wrong: ['DISORDER', 'TURMOIL', 'MAYHEM'] },
    { word: 'CHARITY', ans: 'CRUELTY', wrong: ['KINDNESS', 'BENEVOLENCE', 'GENEROSITY'] },
    { word: 'CHRONIC', ans: 'TEMPORARY', wrong: ['PERSISTENT', 'ONGOING', 'LASTING'] },
    { word: 'CIVILITY', ans: 'RUDENESS', wrong: ['COURTESY', 'POLITENESS', 'DECORUM'] },
    { word: 'CLARITY', ans: 'CONFUSION', wrong: ['LUCIDITY', 'CLEARNESS', 'PRECISION'] },
    { word: 'CLAMOUR', ans: 'SILENCE', wrong: ['NOISE', 'DIN', 'UPROAR'] },
    { word: 'COARSE', ans: 'FINE', wrong: ['ROUGH', 'RUGGED', 'UNPOLISHED'] },
    { word: 'COHERENT', ans: 'INCOHERENT', wrong: ['LOGICAL', 'CONSISTENT', 'CLEAR'] },
    { word: 'COLLECT', ans: 'DISTRIBUTE', wrong: ['GATHER', 'ACCUMULATE', 'AMASS'] },
    { word: 'COMMON', ans: 'RARE', wrong: ['USUAL', 'ORDINARY', 'PREVALENT'] },
    { word: 'COMPASSION', ans: 'INDIFFERENCE', wrong: ['SYMPATHY', 'EMPATHY', 'KINDNESS'] },
    { word: 'COMPEL', ans: 'DISSUADE', wrong: ['FORCE', 'COERCE', 'OBLIGE'] },
    { word: 'COMPLACENT', ans: 'DISSATISFIED', wrong: ['SMUG', 'CONTENT', 'SELF-SATISFIED'] },
    { word: 'COMPLEX', ans: 'SIMPLE', wrong: ['COMPLICATED', 'INTRICATE', 'CONVOLUTED'] },
    { word: 'CONCEAL', ans: 'REVEAL', wrong: ['HIDE', 'SECRETE', 'CLOAK'] },
    { word: 'CONCENTRATE', ans: 'DISTRACT', wrong: ['FOCUS', 'FIXATE', 'ATTEND'] }
  ]
};
